### ISSUE TITLE
duplication of phetioDocumentation

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/graphing-quadratics#103]
Related to #43 code review.  @chrisklus added these 2 `REVIEW` comments that I think are worthy of their own issue.   They are both concerned with duplication of documentation for the NumberProperties related to equations.

StandardFormModel.js

```js
//REVIEW: Since aProperty is duplicated in VertexFormModel.js, should there be comments that note that the
//documentation should stay in sync?
...
  phetioDocumentation: 'coefficient a for the interactive quadratic'
```

VertexFormModel.js

```js
//REVIEW: Since h and k are duplicated in FocusAndDirectrixModel.js, should there be comments that note that
//the documentation should stay in sync?
...
  phetioDocumentation: 'coefficient h for the interactive quadratic'
...
  phetioDocumentation: 'coefficient k for the interactive quadratic'
```

**Comment by pixelzoom** [comment]
The duplication wasn't specific to the Properties identified above.  Other than the symbol (a, h, k), the documentation wording is identical.  And in the case of h and k, it's incorrect to call them "coefficients".  So rather than addressing specific Properties, this needed to be addressed more broadly. 

In the above commit, I factored out a pattern that is used for the all `phetioDocumentation` related to values that appear in the interactive equation.  In GQConstants:

```js
    // PhET-iO documentation for NumberProperty instances that correspond to equation values.
    // See https://github.com/phetsims/graphing-quadratics/issues/103
    PHETIO_DOCUMENTATION_PATTERN: 'the value of \'{{symbol}}\' in the interactive equation'
```

This is used for all NumberProperties (a,b,c,p,h,k).  Here's a sample use in `StandardFormModel`:

```js
      const aProperty = new NumberProperty( A_RANGE.defaultValue, _.extend( {
        range: A_RANGE,
        tandem: tandem.createTandem( 'aProperty' ),
        phetioDocumentation: StringUtils.fillIn( GQConstants.PHETIO_DOCUMENTATION_PATTERN, { symbol: 'a' } )
      }, numberPropertyOptions ) );
```

So this ensures that _all_ of these NumberProperties will have consistent documentation, regardless of which screens they appear in.

Over to @chrisklus to review.

**Comment by chrisklus** [comment]
Looks really nice @pixelzoom, I like the fill-in approach you used. Ready to close.
