### ISSUE TITLE
graphingQuadratics.exploreScreen.view.equationAccordionBox.saveEraseButtonGroup isn't under "content" Tandem

### ISSUE THREAD

**Issue by zepumph** [phetsims/graphing-quadratics#109]
Why are aProperty and other letters under the accordionBox content but this group is not?

UPDATE: I mean aSlider

**Comment by pixelzoom** [comment]
@zepumph please clarify.  `aProperty` and "other letters" are not under accordionBox, they are part of the model and are therefore under `graphingQuadratics.exploreScreen.model`, e.g.:

`graphingQuadratics.exploreScreen.model.aProperty`

As for `graphingQuadratics.exploreScreen.view.equationAccordionBox.saveEraseButtonGroup`... Is the convention to put everything under `equationAccordionBox.content`?   If so, how was I supposed to know that?

**Comment by pixelzoom** [comment]
OK, I think I've figured out what you're reporting.  By `aProperty`, you actually mean `aSlider`, e.g.:

`graphingQuadratics.exploreScreen.view.equationAccordionBox.content.aSlider`

And you're saying that the phetioID for `saveEraseButtonGroup` should be:

`graphingQuadratics.exploreScreen.view.equationAccordionBox.content.saveEraseButtonGroup`

Have I interpreted that correctly?

**Comment by pixelzoom** [comment]
@zepumph and I discussed on Slack.   It's problematic to have `equationAccordionBox.contentNode` because the base class (`GQEquationAccordingBox`) and the subclass (e.g. `ExploreEquationAccordingBox`) each create a piece of the content, which is then assembled in `GQEquationAccordingBox`.   So we'll be leaving `contentNode` out of the phetioIDs, and the phetioIDs under `equationAccordionBox` will be (e.g.): 

```
graphingQuadratics.exploreScreen.view.equationAccordionBox.interactiveEquationNode.aSlider
graphingQuadratics.exploreScreen.view.equationAccordionBox.interactiveEquationNode.bSlider
graphingQuadratics.exploreScreen.view.equationAccordionBox.interactiveEquationNode.cSlider
graphingQuadratics.exploreScreen.view.equationAccordionBox.saveEraseButtonGroup
graphingQuadratics.exploreScreen.view.equationAccordionBox.titleNode
```

**Comment by pixelzoom** [comment]
@samreid @chrisklus FYI.  Please review the above comment/conclusion.  Any feedback?

**Comment by samreid** [comment]
The proposed tandems in https://github.com/phetsims/graphing-quadratics/issues/109#issuecomment-439228255 sound reasonable
