### ISSUE TITLE
create screenshots

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/graphing-quadratics#111]
This issue tracks creation of the primary and alternate screenshots.  Primary screenshot is a prerequisite to publishing 1.0.

**Comment by pixelzoom** [comment]
This sim is now in RC testing.  @amanda-phet please specify the configuration for the main screenshot.

**Comment by pixelzoom** [comment]
@amanda-phet The sim is likely to be published later this week, or early next week.  Primary screenshot is a prerequisite to publishing.

**Comment by amanda-phet** [comment]
Somehow I missed the message 5 days ago! Steele and I discussed this and his screenshot above is what we talked about. However.. I'd love to be picky and make one tweak, so that the AOS isn't right over the y-axis. 

![image](https://user-images.githubusercontent.com/7852916/49547487-08268c80-f8a0-11e8-91fd-ba8996eb901f.png)

Slightly different equation and the point tool is at (0,-4). Thanks @KatieWoe

**Comment by amanda-phet** [comment]
If you already committed the one Steele took that's fine too, actually. When I see them side-by-side, mine looks a little cluttered.

**Comment by phet-steele** [comment]
@KatieWoe here are some alts. Pick your favourite three! Please only commit the alts to master after you have taken them.

![image](https://user-images.githubusercontent.com/5863899/49561397-3faf2c00-f8d4-11e8-8354-5fa3dfcee923.png)
![image](https://user-images.githubusercontent.com/5863899/49561438-84d35e00-f8d4-11e8-846f-6cfa3455f3e5.png)
![image](https://user-images.githubusercontent.com/5863899/49561525-f6aba780-f8d4-11e8-9ee1-f6c092373858.png)
![image](https://user-images.githubusercontent.com/5863899/49561640-79346700-f8d5-11e8-81c2-73f4775974dc.png)
(it's a smiley face)
![image](https://user-images.githubusercontent.com/5863899/49561742-f1029180-f8d5-11e8-8602-49e914d4ef6b.png)

**Comment by phet-steele** [comment]
Also @amanda-phet, if you see a screenshot in the above 5 that you think would work better for the main screenshot, let @KatieWoe know asap!

**Comment by KatieWoe** [comment]
Screenshot and 3 alts for approval before upload.  @amanda-phet 
![graphing-quadratics-screenshot](https://user-images.githubusercontent.com/41024075/49598774-98b2aa80-f93c-11e8-979b-da29c081b3f4.png)
![graphing-quadratics-screenshot-alt1](https://user-images.githubusercontent.com/41024075/49598775-98b2aa80-f93c-11e8-8cba-767f680014d5.png)
![graphing-quadratics-screenshot-alt2](https://user-images.githubusercontent.com/41024075/49598776-98b2aa80-f93c-11e8-964d-60a0a1ec1815.png)
![graphing-quadratics-screenshot-alt3](https://user-images.githubusercontent.com/41024075/49598777-994b4100-f93c-11e8-9a46-ca5ab39e7eac.png)

**Comment by amanda-phet** [comment]
@KatieWoe those all look superb to me. Thanks! 

@phet-steele thanks for all the options :)

**Comment by pixelzoom** [comment]
We're getting close to publication, so I've labeled this as "blocks-sim-publication".

**Comment by pixelzoom** [comment]
Slack:

> Chris Malley [12:47 PM]
For GQ, I see the primary screenshot in the 1.0 branch, but none of the alternates.  Is that “in progress” or an oversight?
> 
> Kathryn Woessner [12:48 PM]
Steele told me to only commit them to master, not to 1.0

Not sure why they wouldn't be added to 1.0, since they will certainly be in any future release branches.  So I've added the alt screenshots to the 1.0 branch.

**Comment by pixelzoom** [comment]
Reviewed screenshots, sizes, etc.  All looking good.  Closing.
