### ISSUE TITLE
branch: studioc

### ISSUE THREAD

**Issue by samreid** [phetsims/graphing-quadratics#113]
In discussion on slack, we determined it would be nice to publish a one-off version of Graphing Quadratics with the new phet-io-wrappers studio branch.

Chris Malley [8:27 AM]
> A dev who is familiar with what branches are required (which isn’t me unfortunately) could publish a “one off” PhET-iO version (something supported by the build process) for one of the instrumented sims.  Graphing Quadratics would probably be a good choice since it uses the new `phetioFeatured` option to highlight featured components.

This is the required branch issue for creating a one-off branch.

We can delete this branch when phet-io-wrappers/studioc is merged to master, see https://github.com/phetsims/phet-io-wrappers/issues/202

**Comment by samreid** [comment]
We published a phet-io one-off version here, which shows the new studio branch: https://phet-dev.colorado.edu/html/graphing-quadratics/1.0.0-studioc.1/phet-io

**Comment by samreid** [comment]
Merged to master, closing.

**Comment by pixelzoom** [comment]
Due to https://github.com/phetsims/special-ops/issues/196#issuecomment-823486502, this branch was restored.  It will need to be deleted again.  Reopening and self assigning.

**Comment by pixelzoom** [comment]
Re-deleted using GitHub UI.  Closing.
