### ISSUE TITLE
What is the advantage of GQViewProperties.equationAccordionBoxExpandedProperty?

### ISSUE THREAD

**Issue by samreid** [phetsims/graphing-quadratics#114]
On slack, @kathy-phet reported:

Kathy Perkins [3:26 PM]
I have a scenario I am running with the Studio, and am wondering what I am missing (as I don't see how to access this). Scenario: See the value and change the state of the accordian box for the equation from open to closed? I can see where I read out the value of the accordian box. I would expect to see it in the view tree here:

![image](https://user-images.githubusercontent.com/679486/49050627-7e8d0580-f1a1-11e8-9811-adc2abac90a1.png)

**Comment by samreid** [comment]
I replied:

That is a property that was developed in the “viewProperties” here:

![image](https://user-images.githubusercontent.com/679486/49050648-906ea880-f1a1-11e8-8294-7709f0b04d11.png)

**Comment by samreid** [comment]
@kathy-phet said:

> Kathy Perkins [3:52 PM]
@samreid - OK, I see it there, but I wouldn't think to look there for this value/control. I assume there is some architectural reason its not under the Equation Accordian Box itself? Can you explain? Similar question re all of the values of the checkboxes in the Quadratic Terms accordian box

**Comment by samreid** [comment]
I replied:

The default is for AccordionBox to create its own `expandedProperty` (which would show where you indicated).  Most likely @pixelzoom had some reason for providing an alternate value defined elsewhere.  We should discuss with him to learn more. (edited)

**Comment by samreid** [comment]
I checked usages of `equationAccordionBoxExpandedProperty` and it looks like the main purpose is for resetting. Is that accurate?  If we added `AccordionBox.reset()`, then would this implementation work properly?  This diff shows: removing `expandedProperty: viewProperties.equationAccordionBoxExpandedProperty,` from each screen, deleting `this.equationAccordionBoxExpandedProperty = new BooleanProperty` and adding `equationAccordionBox.reset();`.

```
Index: js/explore/view/ExploreScreenView.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/explore/view/ExploreScreenView.js	(revision 09b8d425b37af9b7c8a413f679de639bdd9e991b)
+++ js/explore/view/ExploreScreenView.js	(date 1543278987000)
@@ -38,7 +38,6 @@
         viewProperties,
         new ExploreGraphNode( model, viewProperties ), // do not instrument for PhET-iO
         new ExploreEquationAccordionBox( model, {
-          expandedProperty: viewProperties.equationAccordionBoxExpandedProperty,
           tandem: tandem.createTandem( 'equationAccordionBox' ),
           phetioDocumentation: 'accordion box that contains the interactive equation'
         } ),
Index: js/standardform/view/StandardFormScreenView.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/standardform/view/StandardFormScreenView.js	(revision 09b8d425b37af9b7c8a413f679de639bdd9e991b)
+++ js/standardform/view/StandardFormScreenView.js	(date 1543278987000)
@@ -38,7 +38,6 @@
         viewProperties,
         new StandardFormGraphNode( model, viewProperties, tandem ),
         new StandardFormEquationAccordionBox( model, {
-          expandedProperty: viewProperties.equationAccordionBoxExpandedProperty,
           tandem: options.tandem.createTandem( 'equationAccordionBox' ),
           phetioDocumentation: 'accordion box that contains the interactive equation'
         } ),
Index: js/common/view/GQScreenView.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/common/view/GQScreenView.js	(revision 09b8d425b37af9b7c8a413f679de639bdd9e991b)
+++ js/common/view/GQScreenView.js	(date 1543279071000)
@@ -112,6 +112,7 @@
           this.interruptSubtreeInput(); // interrupt all listeners for this screen
           model.reset();
           viewProperties.reset();
+          equationAccordionBox.reset();
         },
         right: this.layoutBounds.maxX - GQConstants.SCREEN_VIEW_X_MARGIN,
         bottom: this.layoutBounds.maxY - GQConstants.SCREEN_VIEW_Y_MARGIN,
Index: js/vertexform/view/VertexFormScreenView.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/vertexform/view/VertexFormScreenView.js	(revision 09b8d425b37af9b7c8a413f679de639bdd9e991b)
+++ js/vertexform/view/VertexFormScreenView.js	(date 1543278987000)
@@ -38,7 +38,6 @@
         viewProperties,
         new VertexFormGraphNode( model, viewProperties, tandem ),
         new VertexFormEquationAccordionBox( model, {
-          expandedProperty: viewProperties.equationAccordionBoxExpandedProperty,
           tandem: options.tandem.createTandem( 'equationAccordionBox' ),
           phetioDocumentation: 'accordion box that contains the interactive equation'
         } ),
Index: js/common/view/GQViewProperties.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/common/view/GQViewProperties.js	(revision 09b8d425b37af9b7c8a413f679de639bdd9e991b)
+++ js/common/view/GQViewProperties.js	(date 1543278987000)
@@ -52,12 +52,6 @@
         phetioDocumentation: 'whether the contents of the graph (curves, plotted points, manipulators) are visible'
       } );
 
-      // @public
-      this.equationAccordionBoxExpandedProperty = new BooleanProperty( true, {
-        tandem: options.tandem.createTandem( 'equationAccordionBoxExpandedProperty' ),
-        phetioDocumentation: 'whether the equation accordion box is expanded'
-      } );
-
       // @public
       this.equationsVisibleProperty = new BooleanProperty( false, {
         tandem: options.tandem.createTandem( 'equationsVisibleProperty' ),
@@ -98,7 +92,6 @@
 
       // Properties that are common to all screens
       this.graphContentsVisibleProperty.reset();
-      this.equationAccordionBoxExpandedProperty.reset();
       this.equationsVisibleProperty.reset();
 
       // Properties that are optional
Index: js/focusanddirectrix/view/FocusAndDirectrixScreenView.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/focusanddirectrix/view/FocusAndDirectrixScreenView.js	(revision 09b8d425b37af9b7c8a413f679de639bdd9e991b)
+++ js/focusanddirectrix/view/FocusAndDirectrixScreenView.js	(date 1543278987000)
@@ -38,7 +38,6 @@
         viewProperties,
         new FocusAndDirectrixGraphNode( model, viewProperties, tandem ),
         new FocusAndDirectrixEquationAccordionBox( model, {
-          expandedProperty: viewProperties.equationAccordionBoxExpandedProperty,
           tandem: options.tandem.createTandem( 'equationAccordionBox' ),
           phetioDocumentation: 'accordion box that contains the interactive equation'
         } ),
```

**Comment by pixelzoom** [comment]
Advantages of `GQViewProperties.equationAccordionBoxExpandedProperty`:

* All Properties that are specific to the view are in one place, where they can be easily reset.  You don't have to drill down into UI components to find Properties.
* Since all view Properties are in one place, it's less likely to introduce "Reset All" bugs, and easier to correct such bugs.
* There is no need to implement (and decide how to implement) methods like AccordionBox.reset.  AccordionBox.reset will be deceptively complicated -- you need to determine what to reset, whether Properties were provided by the client or owned by AccordionBox, etc.
* There is no need to implement `reset` for your ScreenView and all descendants in order to call AccordionBox.reset.
* There is no possibility of introducing bugs like the one in the above patch.  It recommends adding `equationAccordionBox.reset()` to `GQScreenView`.  But `equationAccordionBox` is clearly documented as `@param {Node} equationAccordionBox`.
* There is no need to keep a reference to AccordionBox instances (see ExploreScreenView). 
* AccordionBox's default `expandedProperty` does not support an initial value of `false`, which is needed in this sim (_Explore_ screen, "Quadratic Terms" accordion box).

Other points:
* Using AccordionBox's `expandedProperty` option, as is done here, is a perfectly legitimate approach.  Imo, it's the preferred approach most of the time for many of the above reasons.
* I've used this approach to view Properties in all of my recent sims, and I'm using it in Gas Properties. There is consistency here.
* Encapsulating all view-specific Properties arguably makes things easier for the PhET-iO client.

Back to @samreid and @kathy-phet.  High priority, since this sim is on it's way to QA this week.

**Comment by pixelzoom** [comment]
One more point... @kathy-phet said she expected the Property to be under `exploreScreenView.view.equationAccordionBox.expandCollapseButton`.  @samreid's proposal doesn't put it there; it puts it under `exploreScreenView.view.equationAccordionBox`.  So using AccordionBox's default `expandedProperty` really does nothing to address what was reported.

**Comment by pixelzoom** [comment]
In @kathy-phet's original report, she also said:
>  Similar question re all of the values of the checkboxes in the Quadratic Terms accordion box

So I think that this issue is actually a conceptual problem with how PhET sims are implemented using MVC.

**Comment by pixelzoom** [comment]
In @kathy-phet's original report, she also said:
>  Similar question re all of the values of the checkboxes in the Quadratic Terms accordion box

So I think that this issue is actually a conceptual problem with how PhET sims are implemented using MVC.  Because we would never consider making a Checkbox the owner of the Property that controls its state.

**Comment by pixelzoom** [comment]
Relevant comment by @samreid in Slack phet-io channel:

> From a phet-io standpoint, it seems we could use the same pattern as accordionBox and let the Checkboxes create their own “model” properties (checked/unchecked), but this would go against the grain of the typical PhET MVC architecture in which we create models first separately from views, then create the views and wire them to the models.

Absolutely not, this is unnecessary/undesirable coupling. 

> I wonder if we can reach the the best of both worlds by making “links” in studio work better, or even making “symbolic links” in the tree view.

If we are consistent in encapsulating view Properties, this is imo unnecessary.  It's also more undesirable complexity.

**Comment by pixelzoom** [comment]
Since this wasn't a point of discussion during today's PhET-iO call, I'm guessing that we can close this with no changes.  @samreid is that also your conclusion?

**Comment by samreid** [comment]
We did cover this topic during Tuesday's call (before you arrived).  We need the ability to support passed-in Properties for data (like valueProperty) and metadata (like enabledProperty), so we are going to investigate symbolic links or the like for navigating them in the tree.  

> I've used this approach to view Properties in all of my recent sims, and I'm using it in Gas Properties. There is consistency here.

It's good that there will be consistency across Gas Properties and Graphing Quadratics, but I'm not aware that other developers are using this pattern.  Other than that general topic, this issue is ready to close.  I'll leave the issue reassigned to @pixelzoom to decide if this warrants developer team discussion, code review documentation or other means of dissemination.
