### ISSUE TITLE
iOS 10 Crash

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/graphing-quadratics#116]
**Device:**
iPad 4
**OS:**
iOS 10
**Browser:**
Safari
**Problem description:**
For https://github.com/phetsims/QA/issues/227.
After playing with the sim for ~10 minutes the sim crashed and reloaded.  The error message that appeared at the top the screen as the sim reloaded was "A problem occurred with this webpage so it was reloaded."  There was some minor lag in the minute or two before the crash, but it was very minor.  At the time I was on the Explore screen moving all three sliders up and down on their own.  However, I had been on every screen before that interacting with many various elements.  When using fuzz in an attempt to reproduce, I noticed that fuzz seemed to be running a bit slower on the iPad than on my Windows machine.
**Steps to Reproduce:**
1. Normal use, possibly primarily with sliders on explore screen
2. No success reproducing using ?fuzz.

**Comment by pixelzoom** [comment]
I don't see anything in the memory test results (https://github.com/phetsims/QA/issues/227#issuecomment-443350416) to suggest that we have a memory leak.   But it's not out of the question that the memory footprint (43MB startup, 54MB stabilize) could be the issue.

**Comment by pixelzoom** [comment]
@KatieWoe Is this reproducible on other versions of iOS, or on any other platforms? Or is it specific to iOS 10?

**Comment by KatieWoe** [comment]
I haven't yet, but I also haven't gotten it to reoccur on the iOS 10.  Ariel still has the iOS 12 device, so I can't test it yet as well.

**Comment by pixelzoom** [comment]
[This article](https://blog.pcrisk.com/mac/12282-how-to-fix-a-problem-occurred-with-this-webpage-so-it-was-reloaded) outlines some steps for cleaning up your iOS device.  Scroll down to the "Basic steps to solve".   Can you try these (you might want to skip Reset Network Settings) to see if the problem goes away?  I know that on my old iPad2, Safari problems are sometimes cleared up by clearing history, closing other applications, and restarting.

**Comment by KatieWoe** [comment]
Update: Occurred again on iOS 10 on vertex form screen.

**Comment by pixelzoom** [comment]
OK, so it's been reproduced on 1 screen with sliders (_Explore_) and 1 screen with pickers (_Vertex Form_), so it's not specific to sliders.

**Comment by KatieWoe** [comment]
Yes.

**Comment by pixelzoom** [comment]
@KatieWoe said in Slack:

20 or so minutes on iOS 11 and no signs of crash.  I'm going to go back to testing the iOS 10.  I did the steps in the article.  If it crashes again I'll let you know.  If it gets through the rest of the tests with no crash I'll let you know as well.

**Comment by KatieWoe** [comment]
Have not seen this reoccur after restarting the device and clearing the the web history.  Closing per @pixelzoom.  Will reopen if problem resurfaces.

**Comment by KatieWoe** [comment]
This device seems to be causing problems, which makes me think this issue might not have been solved, but might not be the fault of the sim.  Issue in question: https://github.com/phetsims/coulombs-law/issues/96
