### ISSUE TITLE
Improve drag behavior of "Point on Parabola"

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/graphing-quadratics#117]
Issue per @amanda-phet For https://github.com/phetsims/QA/issues/227
From slack:

>I'm testing the Point on Parabola on the Focus & Directrix of Graphing Quadratics.  When dragging the point it only moves with left to right motion, not up and down.  This leads to the point moving away from the finger when the curve is very sharp.  This is likely intended, and I don't see a good way around this, but I thought I should bring it to your attention just in case.

This is also recently seen in Blackbody spectrum, though the curve was generally less sharp so the effect is less noticeable.

**Comment by phet-steele** [comment]
> This is also recently seen in Blackbody spectrum

@KatieWoe I do not see an issue for this in the blackbody-spectrum repo. Should we make one?

**Comment by KatieWoe** [comment]
@phet-steele it didn't cause the same difficulties there so I didn't.  But it might be a good idea now that you mention it.  @DianaTavares since you're the designer for blackbody-spectrum, what do you think?  Do you want an issue for this?

**Comment by pixelzoom** [comment]
I think this can be improved in GQ, dragging vertically should also more the point. So I'm going to go for it.

**Comment by pixelzoom** [comment]
I've improved the drag behavior for the 'Point on Parabola'.  @KatieWoe @phet-steele @amanda-phet could you please test drive in master and provide feedback?   You can compare to [1.0.0-rc.1](https://phet-dev.colorado.edu/html/graphing-quadratics/1.0.0-rc.1/phet/graphing-quadratics_en_phet.html).

**Comment by KatieWoe** [comment]
Testing on iOS 10, I think this looks much better.  Is this an adjustment to gq only, or will effect other sims with similar behavior?  Do you think this change should be made to those?

**Comment by pixelzoom** [comment]
@KatieWoe said:
> Testing on iOS 10, I think this looks much better. 

Excellent, I think so too. More importantly, it _feels_ better. Thanks again for reporting.

> Is this an adjustment to gq only, or will effect other sims with similar behavior?

This change is necessarily specific to GQ.  

> Do you think this change should be made to those?

I'm not familiar with the other sims, so I'll defer to the designers of those sims.

**Comment by pixelzoom** [comment]
Patched in 1.0 release branch.

**Comment by pixelzoom** [comment]
I've moved the question related to Blackbody Spectrum to https://github.com/phetsims/blackbody-spectrum/issues/69.

**Comment by pixelzoom** [comment]
Labeled with "fixed-pending-testing" for regression testing in 1.0.0-rc.2.

**Comment by phet-steele** [comment]
@pixelzoom I can now drag this bad boy outside the graph (it's the only point in which I can do so). Make sure you move your mouse up or down when you are at the boundaries, not left or right.

![image](https://user-images.githubusercontent.com/5863899/49483138-4748d500-f7ef-11e8-9507-99184315868b.png)

Seen on Win 10 Chrome. For phetsims/QA/issues/233.

<details>
<summary>Troubleshooting Information</summary>

URL: https://phet-dev.colorado.edu/html/graphing-quadratics/1.0.0-rc.2/phet/graphing-quadratics_en_phet.html
Version: 1.0.0-rc.2 2018-12-04 23:26:12 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36
Language: en-US
Window: 1920x938
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4095
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"HEAD"},"axon":{"sha":"61dd41f7","branch":"HEAD"},"brand":{"sha":"1fd6682e","branch":"HEAD"},"chipper":{"sha":"0097c5ac","branch":"HEAD"},"dot":{"sha":"266d3b7a","branch":"HEAD"},"graphing-lines":{"sha":"bff7f97c","branch":"HEAD"},"graphing-quadratics":{"sha":"475051cf","branch":"HEAD"},"joist":{"sha":"88658dbb","branch":"HEAD"},"kite":{"sha":"f3e96e5b","branch":"HEAD"},"phet-core":{"sha":"2e54db08","branch":"HEAD"},"phet-io":{"sha":"1acc6dc2","branch":"HEAD"},"phet-io-wrapper-classroom-activity":{"sha":"5dea7f54","branch":"HEAD"},"phet-io-wrapper-hookes-law-energy":{"sha":"b42eaef7","branch":"HEAD"},"phet-io-wrapper-lab-book":{"sha":"b884e9c1","branch":"HEAD"},"phet-io-wrappers":{"sha":"9d0c5205","branch":"HEAD"},"phetcommon":{"sha":"869b2561","branch":"HEAD"},"query-string-machine":{"sha":"c4d4a81e","branch":"HEAD"},"scenery":{"sha":"4618d52a","branch":"HEAD"},"scenery-phet":{"sha":"e5fa975a","branch":"HEAD"},"sherpa":{"sha":"2134a0d1","branch":"HEAD"},"sun":{"sha":"6887a29a","branch":"HEAD"},"tambo":{"sha":"9b56e6cd","branch":"HEAD"},"tandem":{"sha":"1b2824a0","branch":"HEAD"}}
</details>

**Comment by KatieWoe** [comment]
Addition to what @phet-steele noticed.  It seems to occur more easily for certain shapes of parabola (close to what @phet-steele has posted) and occurs when the it is both open upwards and open downward.

**Comment by pixelzoom** [comment]
Thanks for finding this. I suspect (but have not confirmed) that it occurs when both x and y coordinates of the point are off the graph. In that case, only the x coordinate is getting clamped to the x-axis range, and the y coordinate is off the graph.   That hypothesis matches info provided by @phet-steele in https://github.com/phetsims/graphing-quadratics/issues/117#issuecomment-444319179.   This should be a relatively easy fix.

**Comment by pixelzoom** [comment]
Steps to reproduce:
1. F&D screen
2. Check "Point on Parabola"
3. Drag point towards upper-right corner of graph, then continue to hold and move mouse until it's towards the center of the equation accordion box.

**Comment by pixelzoom** [comment]
"fixed-pending-testing", will be verified in 1.0.0-rc.3.

**Comment by phet-steele** [comment]
Looks like a simple enough fix, and it is working for me 👍.
