### ISSUE TITLE
Coordinate labels get off-center with their associated point

### ISSUE THREAD

**Issue by phet-steele** [phetsims/graphing-quadratics#118]
There are countless similar ways to make this happen, but I picked a dramatic procedure that also illustrates that the coordinates node does not need to be explicitly visible to trigger this bug.

1. Fresh sim load, Standard Form screen. I picked this screen for the "illustrates that the coordinates node does not need to be explicitly visible" part since this screen starts with the vertex off. The vertex being on or off is independent to this bug, only the Coordinates checkbox is important.
2. Adjust b to 1.
3. Disable Coordinates checkbox.
4. Reset All to make this quicker, or manually change b to 0 then reenable the Coordinates checkbox (order matters if you do this manually!).
5. Enable the Vertex so you can see the coordinates. They will be off-center at this point.

This can happen to anything with coordinates (vertex, roots, focus, point on parabola [hard to see this one]).
![image](https://user-images.githubusercontent.com/5863899/49324422-3ac03600-f4ea-11e8-875a-2270c9c13df3.png)

Seen on Win 10 Chrome. For phetsims/QA/issues/227.

<details>
<summary>Troubleshooting Information</summary>

URL: https://phet-dev.colorado.edu/html/graphing-quadratics/1.0.0-rc.1/phet/graphing-quadratics_en_phet.html
Version: 1.0.0-rc.1 2018-11-30 19:42:25 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36
Language: en-US
Window: 1920x938
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4095
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"HEAD"},"axon":{"sha":"61dd41f7","branch":"HEAD"},"brand":{"sha":"1fd6682e","branch":"HEAD"},"chipper":{"sha":"0097c5ac","branch":"HEAD"},"dot":{"sha":"266d3b7a","branch":"HEAD"},"graphing-lines":{"sha":"bff7f97c","branch":"HEAD"},"graphing-quadratics":{"sha":"e121e149","branch":"HEAD"},"joist":{"sha":"88658dbb","branch":"HEAD"},"kite":{"sha":"f3e96e5b","branch":"HEAD"},"phet-core":{"sha":"2e54db08","branch":"HEAD"},"phet-io":{"sha":"1acc6dc2","branch":"HEAD"},"phet-io-wrapper-classroom-activity":{"sha":"5dea7f54","branch":"HEAD"},"phet-io-wrapper-hookes-law-energy":{"sha":"b42eaef7","branch":"HEAD"},"phet-io-wrapper-lab-book":{"sha":"b884e9c1","branch":"HEAD"},"phet-io-wrappers":{"sha":"9d0c5205","branch":"HEAD"},"phetcommon":{"sha":"869b2561","branch":"HEAD"},"query-string-machine":{"sha":"c4d4a81e","branch":"HEAD"},"scenery":{"sha":"4618d52a","branch":"HEAD"},"scenery-phet":{"sha":"e5fa975a","branch":"HEAD"},"sherpa":{"sha":"2134a0d1","branch":"HEAD"},"sun":{"sha":"6887a29a","branch":"HEAD"},"tambo":{"sha":"9b56e6cd","branch":"HEAD"},"tandem":{"sha":"3f6559f4","branch":"HEAD"}}
</details>

**Comment by pixelzoom** [comment]
To improve performance, coordinates are only updated when they are visible.  When they become visible, they are updated.  I had missed one place where the position of the updated coordinates needed to be adjusted.  Thanks for finding this @phet-steele, please verify in master.

**Comment by pixelzoom** [comment]
@KatieWoe If @phet-steele doesn't get to this before the end of the day, would you mind reviewing?

**Comment by KatieWoe** [comment]
This looks fixed in master @pixelzoom

**Comment by pixelzoom** [comment]
In Slack, @phet-steele said:

Steele Dalton [3:47 PM]
I'm not convinced this is fixed

Chris Malley [3:47 PM]
Atta boy!

Steele Dalton [3:48 PM]
right?

![image](https://user-images.githubusercontent.com/3046552/49478266-8b7eaa00-f7dc-11e8-83c3-7307a4adc1d0.png)

(about not being fixed)

Chris Malley [3:48 PM]
you mean it’s a tad off center?

Steele Dalton [3:48 PM]
correct

Chris Malley [3:49 PM]
I believe that you’re correct.  The fix was for static points, `PointNode`.  That case is a manipulator, `GQManipulator`, and probably has the same issue.

**Comment by KatieWoe** [comment]
Good catch.  Sorry for missing this.

**Comment by pixelzoom** [comment]
It's easiest to reproduce this if you move the manipulator to a different quadrant, so that the size of the background rectangle on the coordinates changes.  For example:

1. Vertex screen
2. Move vertex manipulator to (2,2)
3. uncheck Coordinates
4. Move vertex manipulator to (-2,2)
4. check Coordinates

**Comment by pixelzoom** [comment]
Fixed in the above commit.  Identical fixes for `GQManipulator` and `PointNode`.   @phet-steele please verify in master.

**Comment by phet-steele** [comment]
I like master now after https://github.com/phetsims/graphing-quadratics/commit/18b61585a89e7a0ad60b5061795f7d7361ca7b71.

**Comment by pixelzoom** [comment]
Thanks @phet-steele.

Reopened, labeled with "fixed-pending-testing".

**Comment by phet-steele** [comment]
👍
