### ISSUE TITLE
[iOS9] crashes at startup

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/graphing-quadratics#119]
For phetsims/QA/issues/227, caused by https://github.com/phetsims/joist/issues/539#issuecomment-443384951.

ES6 code snuck into one of the preloads, and preloads are not transpiled.  Mobile Safari on iOS9 does not support ES6, so the sim fails on startup.   The progress bar on the splash screen doesn't even begin to fill.

@KatieWoe FYI.  I'll have a new RC version sometime this morning.

**Comment by pixelzoom** [comment]
% cd perennial
% grunt checkout-target --repo=graphing-quadratics --target=1.0
% cd tandem
% git checkout -b graphing-quadratics-1.0
% git cherry-pick 4336872f0c7c6e3571d99c4b1c9c36da39915ecc
% grunt 
<test build, on Chrome desktop, and iOS9 Safari>
% git push origin graphing-quadratics-1.0
%

**Comment by pixelzoom** [comment]
Labeled with "fixed-pending-testing" for regression testing in 1.0.0-rc.2.

**Comment by KatieWoe** [comment]
This seems fixed 1.0.0-rc.2.
