### ISSUE TITLE
where to indicate "NO REAL ROOTS"? 

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/graphing-quadratics#12]
For a curve with no roots, the design document mockup currently shows "NO REAL ROOTS" off to the right of the x axis, like this:

![screenshot_712](https://user-images.githubusercontent.com/3046552/43922505-3614de7e-9bdc-11e8-991d-096634896e13.png)

@amanda-phet added 2 related comments in the design doc, indicating that this part of the design is still in flux:

> mock up with "no real roots" on graph close to x-axis instead of off the graph

> scratch that. mock up with AoS equation on graph, but vertex and roots labeled off to the side (and use the point tool to find the coordinates on the graph)

How about doing something similar to what was done for "undefined slope" in Graphing Lines?  If a line's slope is undefined, we indicate that next to the equation used to label the line, e.g.:

![screenshot_713](https://user-images.githubusercontent.com/3046552/43922690-ad74948c-9bdc-11e8-9937-ae6c614f7fd7.png)

Would it work to show "no real roots" next to (or below?) the equation? E.g.:

![screenshot_712](https://user-images.githubusercontent.com/3046552/43922811-153e1c82-9bdd-11e8-89bd-34e69859f02b.jpg)

Mentioning @ariel-phet, in case he knows whether this option has been previously considered.

**Comment by pixelzoom** [comment]
Or perhaps we really do want "no real roots" to be on the x axis, since that's where roots appear.

**Comment by pixelzoom** [comment]
Related question... If a=0, we don't have a quadratic, so we don't have roots -- or vertex and axis of symmetry.  In that case, perhaps we should not show "NO REAL ROOTS", because we don't show "NO VERTEX" or "NO AXIS OF SYMMETRY".  Those things are all irrelevant and are simply not shown.

**Comment by pixelzoom** [comment]
The implementation (as of 8/22/18) shows "NO REAL ROOTS" centered on the origin, e.g.:

![screenshot_719](https://user-images.githubusercontent.com/3046552/44489966-3eeed480-a61a-11e8-9674-c39d551f0611.png)

If the equation is not a quadratic (a=0), then "NO REAL ROOTS" is _not_ shown, for the same reason that we don't say anything about the vertex or axis of symmetry. E.g.:

![screenshot_720](https://user-images.githubusercontent.com/3046552/44490019-5d54d000-a61a-11e8-9186-c22722fdfef4.png)

**Comment by amanda-phet** [comment]
We discussed the first scenario and I like the way it is behaving as it is. 

In the second case (when a=0), I think we *should* be displaying no real roots. If a=0 and b≠0, there would be a single root. So, we should change the behavior so that even if a=0 we are still showing the root (or displaying no real roots). 

If a=0, you are correct we would not say anything about the vertex or aos because those are specific to a parabola.

**Comment by pixelzoom** [comment]
@amanda-phet I made the changes you requested above. Please verify behavior in [1.0.0-dev.7](https://phet-dev.colorado.edu/html/graphing-quadratics/1.0.0-dev.7/phet/graphing-quadratics_en_phet.html).

In case this scenario hasn't been considered... When a=0, b=0, c=0, _every_ point is actually a root, because y=0 y=0 includes every point on the x axis.  Do we need to indicate this somehow?

**Comment by pixelzoom** [comment]
The y=0 case (every point is a root) has been moved to https://github.com/phetsims/graphing-quadratics/issues/28.

**Comment by pixelzoom** [comment]
Fixed the y=0 case, so that "NO REAL ROOTS" is not displayed.  

@amanda-phet please verify in [1.0.0-dev.9](https://phet-dev.colorado.edu/html/graphing-quadratics/1.0.0-dev.9/phet/graphing-quadratics_en_phet.html), and feel free to close if everything looks OK.

**Comment by amanda-phet** [comment]
Looks good to me.
