### ISSUE TITLE
dev bounds issues

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/graphing-quadratics#121]
For https://github.com/phetsims/QA/issues/227.  Found by @arouinfar on macOS 10.13.6 and latest Chrome, but is much more noticeable and reproducible on an iPad in landscape mode.
The dev area from ?dev shows a different size box on the home screen than on the simulation screens.  How the size differs seems to depend on the size and shape of the window.  Either the area on the home screen will be shorter (on iPad make sure the sim is the only tab and is in landscape), or the area on sim screens will be more narrow (on iPad make sure there is at least on other tab besides the sim and it is in landscape).  @arouinfar and I are uncertain of severity of issue, so posting for consideration.
<img width="911" alt="screen shot 2018-12-03 at 11 00 49 am" src="https://user-images.githubusercontent.com/41024075/49396244-e7bace80-f6f5-11e8-8fa1-11a01b630321.png">
<img width="912" alt="screen shot 2018-12-03 at 11 00 30 am" src="https://user-images.githubusercontent.com/41024075/49396245-e7bace80-f6f5-11e8-9c64-8112fdfa3b1b.png">

**Comment by arouinfar** [comment]
@pixelzoom @amanda-phet it looks like the `?dev` boundary does not have the correct aspect ratio on the sim screens. On the Home screen, the `?dev` boundary matches published sims (such as EqEx).

EqEx:
<img width="1440" alt="screen shot 2018-12-03 at 12 25 32 pm" src="https://user-images.githubusercontent.com/8419308/49396568-b5f63780-f6f6-11e8-94e8-bb0552082215.png">

GQ Home Screen:
<img width="1440" alt="screen shot 2018-12-03 at 12 25 38 pm" src="https://user-images.githubusercontent.com/8419308/49396582-c60e1700-f6f6-11e8-8368-e27bb59f5575.png">


GQ Sim Screens:
<img width="1440" alt="screen shot 2018-12-03 at 12 25 35 pm" src="https://user-images.githubusercontent.com/8419308/49396572-bbec1880-f6f6-11e8-8f7d-8ae2f6fbb384.png">

**Comment by pixelzoom** [comment]
The home screen issue is not specific to GQ, it's present in all sims. The bottom part of the dev bounds rectangle is chopped off in master.  Compare EqEx in master (top) vs published (bottom):

![screenshot_911](https://user-images.githubusercontent.com/3046552/49397215-34070e00-f6f8-11e8-851b-e060f086b73b.png) 
![screenshot_912](https://user-images.githubusercontent.com/3046552/49397210-31a4b400-f6f8-11e8-9ebc-4f82f800336e.png)

**Comment by arouinfar** [comment]
@pixelzoom I realize that `?dev` generally looks goofy on the home screen, but the changing width concerned me.

Compare `?dev` on EqEx (more transparent) to GQ. The GQ boundary is too narrow.
![image](https://user-images.githubusercontent.com/8419308/49397447-d8895000-f6f8-11e8-9f67-afca4a1559a2.png)

**Comment by pixelzoom** [comment]
Thanks @arouinfar.  The home screen and sim screens are handled differently, and have totally different default layout bounds (home screen is ).  So I believe that we have 2 different issues here.  

phetsims/joist#541 will deal with the home screen issue.  I suspect it's caused by recent home screen changes to add a11y sound and keyboard icons.

I have reproduced the discrepancy in sim screen dev bounds in GQ, and I'm investigating that as a separate issue. Not sure yet if it's sim-specific or common code.

**Comment by pixelzoom** [comment]
Re the home screen issue...  The consensus in https://github.com/phetsims/joist/issues/541 is that it affects only our internal `dev` feature, and does not need to be addressed in the Graphing Quadratics 1.0 release branch.  So we can close this issue.  If anyone objects, or has more questions, please reopen.

**Comment by pixelzoom** [comment]
It's not aspect ratio that's important to the Java port, it's the dimensions of the layoutBounds. It's probably possible (though I haven't tried it) to take the Java layoutBounds, modify one of the dimensions, and still get the benefits of direct porting, while having the same aspect ratio as the default for HTML5. 

Gas Properties is going to be a full rewrite, not a port, so have no fear.  And if you're generally concerned about this, you might want to question whether it should even be possible to change the layoutBounds (a.k.a "dev bounds"), or whether custom layoutBounds should be required to have the same aspect ratio as the HTML5 default.

**Comment by pixelzoom** [comment]
@arouinfar It's not aspect ratio that's important to the Java port, it's the dimensions of the layoutBounds (aka 'dev bounds'). It's probably possible (though I haven't tried it) to take the Java layoutBounds, modify one of the dimensions, and still get the benefits of direct porting, while having the same aspect ratio as the default for HTML5.

Gas Properties is going to be a full rewrite, not a port, so have no fear - it is using the HTML5 default layoutBounds. And if you're generally concerned about this, you might want to question whether it should even be possible to change the layoutBounds (a.k.a "dev bounds"), or whether custom layoutBounds should be required to have the same aspect ratio as the HTML5 default.

**Comment by pixelzoom** [comment]
I said:
>  It's probably possible (though I haven't tried it) to take the Java layoutBounds,

Reopening. I'm going to give this a try.

**Comment by pixelzoom** [comment]
Adjusting the custom layoutBounds to have the same aspect ratio as the default HTML5 layoutBounds works nicely.  I've committed the change to master and 1.0 branches.  Everything remains in the same location on the screen, but the dev bounds now match the dev bounds of sims that use the default.

**Comment by pixelzoom** [comment]
@KatieWoe could you please verify? Compare master and [1.0.0-rc.1](https://phet-dev.colorado.edu/html/graphing-quadratics/1.0.0-rc.1/phet/graphing-quadratics_en_phet.html?dev), and verify that all UI elements are still in their same locations, while the dev bounds now match typical PhET sims (e.g. [Equality Explorer 1.0.3](https://phet.colorado.edu/sims/html/equality-explorer/latest/equality-explorer_en.html?dev).

**Comment by pixelzoom** [comment]
@arouinfar said:
> I'd be happy to open a general issue for discussion. Would joist be the appropriate repo @pixelzoom?

Yes.  I would recommend keeping the ability to set a custom layoutBounds, but require a layoutBounds values to have the same aspect ratio (within some tolerance).

**Comment by pixelzoom** [comment]
Labeled with "fixed-pending-testing" for regression testing in 1.0.0-rc.2.

**Comment by pixelzoom** [comment]
To clarify for 1.0.0-rc.2 regression testing, here's what you need to do for regression testing:

1. Run the sim with `dev` query parameter
2. Ignore the home screen.
3. Verify that the dev bounds for screens match the default dev bounds, e.g. for [Equality Explorer 1.0.3](https://phet.colorado.edu/sims/html/equality-explorer/latest/equality-explorer_en.html?dev)
4. Verify that UI components have not moved by comparing [1.0.0-rc.2](https://phet-dev.colorado.edu/html/graphing-quadratics/1.0.0-rc.2/phet/graphing-quadratics_en_phet.html?dev) with [1.0.0-rc.1](https://phet-dev.colorado.edu/html/graphing-quadratics/1.0.0-rc.1/phet/graphing-quadratics_en_phet.html?dev).

**Comment by KatieWoe** [comment]
Looks good 1.0.0-rc.2
