### ISSUE TITLE
[Edge] performance of sliders is laggy

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/graphing-quadratics#122]
**Test device:**
Dell
**Operating System:**
Win 10
**Browser:**
Edge
**Problem description:**
For https://github.com/phetsims/QA/issues/227.  Connected to https://github.com/phetsims/graphing-quadratics/issues/82.
When dragging and using the sliders on Edge, there in a lag, especially when the mouse or finger movement is fast.  The performance is consistent, doesn't interfere, and is generally acceptable, especially on Edge.  Documenting here so there is a record of performance.
**Steps to reproduce:**
1. Open sim in Edge
2. Go to final screen
3. Drag each slider up and down fairly quickly
4. Drag the pointer tools around the screen fairly quickly

**Troubleshooting information (do not edit):**

<details>

Name: ‪Graphing Quadratics‬
URL: https://phet-dev.colorado.edu/html/graphing-quadratics/1.0.0-rc.1/phet/graphing-quadratics_en_phet.html
Version: 1.0.0-rc.1 2018-11-30 19:42:25 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/17.17134
Language: en-US
Window: 1536x756
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Microsoft (Microsoft Edge)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"HEAD"},"axon":{"sha":"61dd41f7","branch":"HEAD"},"brand":{"sha":"1fd6682e","branch":"HEAD"},"chipper":{"sha":"0097c5ac","branch":"HEAD"},"dot":{"sha":"266d3b7a","branch":"HEAD"},"graphing-lines":{"sha":"bff7f97c","branch":"HEAD"},"graphing-quadratics":{"sha":"e121e149","branch":"HEAD"},"joist":{"sha":"88658dbb","branch":"HEAD"},"kite":{"sha":"f3e96e5b","branch":"HEAD"},"phet-core":{"sha":"2e54db08","branch":"HEAD"},"phet-io":{"sha":"1acc6dc2","branch":"HEAD"},"phet-io-wrapper-classroom-activity":{"sha":"5dea7f54","branch":"HEAD"},"phet-io-wrapper-hookes-law-energy":{"sha":"b42eaef7","branch":"HEAD"},"phet-io-wrapper-lab-book":{"sha":"b884e9c1","branch":"HEAD"},"phet-io-wrappers":{"sha":"9d0c5205","branch":"HEAD"},"phetcommon":{"sha":"869b2561","branch":"HEAD"},"query-string-machine":{"sha":"c4d4a81e","branch":"HEAD"},"scenery":{"sha":"4618d52a","branch":"HEAD"},"scenery-phet":{"sha":"e5fa975a","branch":"HEAD"},"sherpa":{"sha":"2134a0d1","branch":"HEAD"},"sun":{"sha":"6887a29a","branch":"HEAD"},"tambo":{"sha":"9b56e6cd","branch":"HEAD"},"tandem":{"sha":"3f6559f4","branch":"HEAD"}}

</details>

**Comment by phet-steele** [comment]
@KatieWoe is the performance you are seeing now any different than the performance in #82? Otherwise, if the purpose was to create a record of performance, than I think #82 does just that.

**Comment by KatieWoe** [comment]
It's not much different, maybe a bit slower.  @pixelzoom asked for the issue on slack as a record specific to the rc.

**Comment by pixelzoom** [comment]
@KatieWoe could you please review with @amanda-phet on your test device?  (Like we did in https://github.com/phetsims/graphing-quadratics/issues/82#issuecomment-437077942.) If @amanda-phet thinks the performance is acceptable, you can close this issue.

**Comment by KatieWoe** [comment]
Sure.  @amanda-phet let me know when works for you.

**Comment by amanda-phet** [comment]
@KatieWoe I will be on campus Thursday. Will that be too late for me to review with you? If it's the same as #82 then I think we should leave it as it is.

**Comment by KatieWoe** [comment]
It shouldn't be too late.  As indicated above, this is probably acceptable for Edge.  @pixelzoom does this time frame work for you?

**Comment by pixelzoom** [comment]
>  @pixelzoom does this time frame work for you?

It depends on when you'll be ready for the next RC, 1.0.0-rc2.  We don't want to do anything to put this sim on hold.

**Comment by pixelzoom** [comment]
@amanda-phet @KatieWoe reminder to review performance on Thursday 12/5.  Please use the latest RC, [1.0.0-rc.3](https://bayes.colorado.edu/dev/html/graphing-quadratics/1.0.0-rc.3/phet/graphing-quadratics_en_phet.html).

**Comment by pixelzoom** [comment]
@KatieWoe and I reviewed on her test machine.  The responsiveness is very acceptable.  No need for @amanda-phet to review, no need to change anything.  Closing.
