### ISSUE TITLE
Overlap of eye button and "point on parabola" coordinates

### ISSUE THREAD

**Issue by kellywurtz** [phetsims/graphing-quadratics#126]
Test device:
Found on both Macbook and iPad

Operating System:
OS 10.14.1 and iOS 11

Browser:
Safari and Chrome

Problem description:
For https://github.com/phetsims/QA/issues/233
Eye button obscures point coordinates for a very small range of functions/points.

Steps to reproduce:
- Open "focus and directrix" screen
- Enable "point on parabola option"
- Create the function shown in the photo below
- Drag the orange point all the way to the right 

Screenshots:
![img_0188](https://user-images.githubusercontent.com/42352972/49543197-c6441900-f894-11e8-8dd5-07f54df907b3.jpg)

Troubleshooting information (do not edit):
Name: ‪Graphing Quadratics‬
URL: https://phet-dev.colorado.edu/html/graphing-quadratics/1.0.0-rc.2/phet/graphing-quadratics_en_phet.html
Version: 1.0.0-rc.2 2018-12-04 23:26:12 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.80 Safari/537.36
Language: en-US
Window: 1680x913
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"HEAD"},"axon":{"sha":"61dd41f7","branch":"HEAD"},"brand":{"sha":"1fd6682e","branch":"HEAD"},"chipper":{"sha":"0097c5ac","branch":"HEAD"},"dot":{"sha":"266d3b7a","branch":"HEAD"},"graphing-lines":{"sha":"bff7f97c","branch":"HEAD"},"graphing-quadratics":{"sha":"475051cf","branch":"HEAD"},"joist":{"sha":"88658dbb","branch":"HEAD"},"kite":{"sha":"f3e96e5b","branch":"HEAD"},"phet-core":{"sha":"2e54db08","branch":"HEAD"},"phet-io":{"sha":"1acc6dc2","branch":"HEAD"},"phet-io-wrapper-classroom-activity":{"sha":"5dea7f54","branch":"HEAD"},"phet-io-wrapper-hookes-law-energy":{"sha":"b42eaef7","branch":"HEAD"},"phet-io-wrapper-lab-book":{"sha":"b884e9c1","branch":"HEAD"},"phet-io-wrappers":{"sha":"9d0c5205","branch":"HEAD"},"phetcommon":{"sha":"869b2561","branch":"HEAD"},"query-string-machine":{"sha":"c4d4a81e","branch":"HEAD"},"scenery":{"sha":"4618d52a","branch":"HEAD"},"scenery-phet":{"sha":"e5fa975a","branch":"HEAD"},"sherpa":{"sha":"2134a0d1","branch":"HEAD"},"sun":{"sha":"6887a29a","branch":"HEAD"},"tambo":{"sha":"9b56e6cd","branch":"HEAD"},"tandem":{"sha":"1b2824a0","branch":"HEAD"}}

**Comment by pixelzoom** [comment]
Nice! We hadn't seen that one.

**Comment by pixelzoom** [comment]
@amanda-phet Do you want this overlap to be addressed? Would it be acceptable to move the button behind the coordinates?

**Comment by pixelzoom** [comment]
I could also move the coordinates to the left of the point when the point is in the lower-right corner of the graph.  That's a bit of a hack code-wise, but relatively easy.

**Comment by pixelzoom** [comment]
With button behind point+coordinates:

![screenshot_923](https://user-images.githubusercontent.com/3046552/49546768-3dca7600-f89e-11e8-9955-3884053e9b6c.png)

**Comment by amanda-phet** [comment]
Button behind point+coordinates seems like a reasonable solution to me. Good find!

**Comment by pixelzoom** [comment]
I discussed this issue with @amanda-phet on Slack, and we decided to button behind point+coordinates, and tolerate the overlap.   The point can be moved, or coordinates turned off, if the overlap is a problem.   And we don't want to attempt to do the same thing on the left side of the graph, since we'd cause overlap problems with the vertex and/or focus.  

So this is "fixed-awaiting-testing".

**Comment by phet-steele** [comment]
Good 'nuff in 1.0.0-rc.3.
