### ISSUE TITLE
pointerAreas for eye button and "Point on Parabola" overlap

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/graphing-quadratics#127]
For phetsims/QA#233. Noted while working on #126.

![screenshot_924](https://user-images.githubusercontent.com/3046552/49548718-dadbdd80-f8a3-11e8-8792-e20613a2e4db.png)

Discussed with @amanda-phet. Moving the eye button 11 pixels to the right will resolve the overlap:

![screenshot_926](https://user-images.githubusercontent.com/3046552/49548856-43c35580-f8a4-11e8-9f7f-6886a6ad1a76.png)

This same change will be applied to Graphing Lines.

**Comment by pixelzoom** [comment]
@KatieWoe FYI.

**Comment by KatieWoe** [comment]
Thanks for the heads up.

**Comment by pixelzoom** [comment]
This issue is now "fixed-pending-testing".

**Comment by phet-steele** [comment]
No overlap in 1.0.0-rc.3!
