### ISSUE TITLE
width of the "Quadratic Terms" accordion box

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/graphing-quadratics#128]
For phetsims/QA#233, reported by @amanda-phet on Zoom, which she had previously discussed with @KatieWoe.

The "Quadratic Terms" accordion box looks like this:

![screenshot_927](https://user-images.githubusercontent.com/3046552/49548999-b5030880-f8a4-11e8-8ef5-78840cf52575.png)

With `?stringTest=X`, it looks like this:

![screenshot_928](https://user-images.githubusercontent.com/3046552/49549033-cea45000-f8a4-11e8-9466-cd12520efb0d.png)

@amanda-phet and @KatieWoe were wondering why the accordion box doesn't get narrower with shorter strings.  For this dialog, the English content is narrower than the title.  In order to have a horizontal separator that spans the full width of the accordion box, it's necessary to set a minimum width for that separator.  Without that minimum width, the accordion box would look like this:

![screenshot_929](https://user-images.githubusercontent.com/3046552/49549191-39ee2200-f8a5-11e8-9ef1-81599b701021.png)

The minimum separator width is currently 200.  @amanda-phet suggested reducing it to 175.  I'm also going to investigate computing it as a function of title.width + expandCollapseButton.width + xSpacing.

**Comment by KatieWoe** [comment]
Discussed this with @phet-steele on Zoom and he said that this was generally acceptable and pointed out that the equations likely wouldn't be translated and shortened.

**Comment by pixelzoom** [comment]
Width of the separator is now computed as a function of the title and content.  Here's what the accordion box looks like:

![screenshot_930](https://user-images.githubusercontent.com/3046552/49550073-d31e3800-f8a7-11e8-8bd2-9b712b511a85.png)

With `?stringTest=long`:

![screenshot_931](https://user-images.githubusercontent.com/3046552/49550083-d9acaf80-f8a7-11e8-9250-69b580386186.png)

With `?stringTest=X`:

![screenshot_932](https://user-images.githubusercontent.com/3046552/49550095-e0d3bd80-f8a7-11e8-9463-7a9803e572b4.png)

**Comment by pixelzoom** [comment]
This issue is now "fixed-pending-testing".

**Comment by phet-steele** [comment]
Lookin' good in 1.0.0-rc.3.
