### ISSUE TITLE
Why are the save/erase buttons phetioReadOnly?

### ISSUE THREAD

**Issue by zepumph** [phetsims/graphing-quadratics#132]
While working on https://github.com/phetsims/phet-io/issues/1466, I noticed that I can't toggle the visibility of the save/erase buttons, with phetioIDs like:
`graphingQuadratics.exploreScreen.view.equationAccordionBox.buttonGroup.saveButton`

Likely this is purposeful and the issue can just be closed. I know others have spent much longer on this sim's design than I have. At the very least my question is something like, "Why are these buttons' visible/enabled Properties featured when they can't even be used?" 
Assigning to @pixelzoom for clarification.

**Comment by pixelzoom** [comment]
Good question! 

From the requirements in https://github.com/phetsims/graphing-quadratics/issues/112:

> - hide save and erase button as a group, but not individually

So the request was to be able to change the visibility of `buttonGroup`, but not the individual buttons. The rationale was that it doesn't make sense to have only the "Save" or "Erase" button, but it is useful to hide the entire feature. 

Further confirmation appears in [Graphing Quadratics: PhET-iO Featured List](https://docs.google.com/document/d/1OfHhIDuaBt-hhXVtpnJgM3Wm0iByJ7dmXd-2UkphUR4/edit#) where "Hide save/erase group" is featured.

@zepumph if this answers your question, feel free to close.

**Comment by zepumph** [comment]
Oops sorry to close prematurely. This all makes sense. The reason why I was asking was because the individual buttons' enabled/visible Properties are still phetioFeatured. I would recommend making those not featured in studio when we go back through, since they are readonly and can't be used. I'm not sure if that is a you thing, or a designer thing, but I'll assign to you for now to see what you think.

**Comment by pixelzoom** [comment]
@zepumph Roger that.  Are they feature now because all buttons are featured by default?  I don't recall if they were featured incorrectly before via sim-specific code.

**Comment by zepumph** [comment]
>Are they featured now because all buttons are featured by default?

Yes now buttonModel.enabledProperty, and Round/RectangularButtonView.visibleProperty (a NodeIO subProperty) are both featured by default. 

I would recommend removing any sim specific code and setting them manualing to phetioFeatured: false via studio admin mode to add to the overrides.

**Comment by pixelzoom** [comment]
I addressed this in the above commit. Verification is part of #112. Closing.
