### ISSUE TITLE
Update QA credits before next publication

### ISSUE THREAD

**Issue by zepumph** [phetsims/graphing-quadratics#134]
@KatieWoe how do the current QA credits look?

**Comment by zepumph** [comment]
`Steele Dalton, Laura Rea, Jacob Romero, Kathryn Woessner, Kelly Wurtz`

**Comment by KatieWoe** [comment]
Add Ethan Ward and Jaspe Arias

**Comment by zepumph** [comment]
Thanks, https://github.com/phetsims/graphing-quadratics/issues/134

**Comment by KatieWoe** [comment]
Looks good.
