### ISSUE TITLE
Move BackgroundNode to common code

### ISSUE THREAD

**Issue by zepumph** [phetsims/graphing-quadratics#135]
Over in https://github.com/phetsims/inverse-square-law-common/issues/79 there is good use for this same type. @pixelzoom and I think we should move GQ/BackgroundNode to common code and use it in both sims as well as anywhere else that needs it.

**Comment by zepumph** [comment]
Over in https://github.com/phetsims/scenery-phet/commit/d5e624d7401bfa503810bdc4276b470f3efec959, we added BackgroundNode to scenery-phet. Now we can update the usage in this repo. The one feature that will be removed from it is the debug query parameter: `showOrigin`.

**Comment by zepumph** [comment]
@pixelzoom please review. I subtyped the common code element to keep all the functionality that was previously there.

**Comment by pixelzoom** [comment]
👍 closing.
