### ISSUE TITLE
Graphing Quadratics 1.2 release

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/graphing-quadratics#137]
1.2 release is for phet and phet-io brands.

From 1/14/2021 PhET-iO meeting, milestones are:

3/1/21 begin work
3/31/21 publish 1.2

1.2 will be a new release branch.  It requires a full dev test, followed by full RC test.

FYI @amanda-phet  @kathy-phet

**Comment by pixelzoom** [comment]
@arouinfar can you remind me what needs to be done for this sim?  Is it just #138 (client guides) and QA process?  Or is there something else that needs to be captured in a GitHub issu?

**Comment by pixelzoom** [comment]
@amanda-phet  can you remind me what needs to be done for this sim?  Is it just #138 (client guides) and QA process?  Or is there something else that needs to be captured in a GitHub issue?

**Comment by amanda-phet** [comment]
@kathy-phet and I are thinking we should do another look at studio for this sim since there have likely been some changes to common code and studio practices since we last worked on this sim. 

If we have changes to make to the featured list, we can do that with overrides. If anything else comes up, we will let you know @pixelzoom .

**Comment by pixelzoom** [comment]
Review of sim in Studio will be tracked in https://github.com/phetsims/graphing-quadratics/issues/139.

**Comment by pixelzoom** [comment]
@amanda-phet Any other prerequisties for this release, or it is just #139 (review Studio)?

**Comment by amanda-phet** [comment]
Just #138 and #139, I believe.

**Comment by pixelzoom** [comment]
Milestone were changed in the Project Overview:

3/1/21 begin work
4/15/21 publish 1.3

**Comment by pixelzoom** [comment]
At 4/8/21 Q2 planning meeting, dates were adjusted:

3/1/21 start
5/15/21 end

**Comment by pixelzoom** [comment]
Status:  It looks like all GitHub issues have been addressed, but QA process has not started.  So 5/15/21 is no longer a realistic publication dates.  Assigning to @kathy-phet and @amanda-phet to establish new milestones.

**Comment by pixelzoom** [comment]
@kathy-phet changed milestones to:

3/1/21 start
6/30/21 end

**Comment by pixelzoom** [comment]
We're now 1 week past the milestone. Assigning to @kathy-phet to revise.  Feel free to assign back to me when you're ready to proceed with publishing this release.

**Comment by pixelzoom** [comment]
8/9/2021:
* published 1.2.0-rc.1 for full RC testing in https://github.com/phetsims/qa/issues/687

**Comment by pixelzoom** [comment]
8/31/2021:

* published 1.2.0-rc.3 for RC spot-check testing in https://github.com/phetsims/qa/issues/704

**Comment by pixelzoom** [comment]
9/7/21:

* published RC spot check phetsims/qa#701

**Comment by pixelzoom** [comment]
9/8/2021: Graphing Quadratics 1.2.0 was deployed.

Extra steps identifed by `grunt production`:

> PhET-iO deploys involve a couple of extra steps after production. Please ensure the following are accomplished:
> 1. Make sure the sim is listed in perennial/data/phet-io-api-stable, if it has had a designed production release, and update the checked in API file to match the published version.

Confirmed, it's listed.

> 2. Create an issue in the phet-io repo and assign to @kathy-phet to update the main "PhET-iO Simulations" spreadsheet from this new publication. (https://docs.google.com/spreadsheets/d/18_QNGuVtYtxOEKG9xRBs_PSQpyvzySF1Gk5puR-5Fv4/edit#gid=1881767354)

See https://github.com/phetsims/phet-io/issues/1819

> 3. If you are delivering this version to a research partner, update partners.md (phet-io/doc/partners.md) to show this delivery. (Read the intro of the document to make sure that you format the entry correctly.)
> 4. If this is a version that will be used with students, then make sure to remove the password protection, see https://github.com/phetsims/phet-io/blob/master/doc/phet-io-security.md for details. 

See https://github.com/phetsims/phet-io/issues/1820

**Comment by pixelzoom** [comment]
Build server reports that Graphing Quadratics 1.2.0 deploy failed, details below.   The sim's page at phet.colorado.edu appears to be missing a screenshot.  Clicking where the screenshot should be launches 1.2.0, even though deploy supposedly failed.   Further investigation is occurring in https://github.com/phetsims/perennial/issues/243.

```js
Build failure: Error: Build aborted, Error: grunt --brands=phet,phet-io --repo=graphing-quadratics build-images in ../chipper failed with exit code 3
stdout:
Loading "Gruntfile.js" tasks...ERROR
Error: Cannot find module '../../../perennial-alias/js/common/isRepoTypeScript'
Require stack:
- /data/share/phet/phet-repos/chipper/js/grunt/webpackBuild.js
- /data/share/phet/phet-repos/chipper/js/grunt/buildStandalone.js
- /data/share/phet/phet-repos/chipper/js/grunt/copySupplementalPhetioFiles.js
- /data/share/phet/phet-repos/chipper/js/grunt/buildRunnable.js
- /data/share/phet/phet-repos/chipper/js/grunt/Gruntfile.js
- /data/share/phet/phet-repos/chipper/Gruntfile.js
- /data/share/phet/phet-repos/chipper/node_modules/grunt/lib/grunt/task.js
- /data/share/phet/phet-repos/chipper/node_modules/grunt/lib/grunt.js
- /usr/lib/node_modules/grunt-cli/bin/grunt
Warning: Task "build-images" not found. Use --force to continue.

Aborted due to warnings.
Sim = graphing-quadratics Version = 1.2.0 Brands = phet,phet-io Locales = * Shas = {"comment":"# graphing-quadratics 1.2.0 Wed Sep 08 2021 18:30:22 GMT-0400 (Eastern Daylight Time)","assert":{"sha":"f360fa1bd09a47b3c9e49cd90c8dddd136a13e0c","branch":"HEAD"},"axon":{"sha":"d09f8f50b1a8b97145612bece9e7d91a20e05b28","branch":"HEAD"},"brand":{"sha":"0c723e76a7bad4344cb588c486ae41d0f7fc4995","branch":"HEAD"},"chipper":{"sha":"7aee98a05c3a13c5000e04ed2ea1ddfe84dad715","branch":"HEAD"},"dot":{"sha":"aacdd9db44ef332395aa95b0b134b6032d5b8a59","branch":"HEAD"},"graphing-lines":{"sha":"7bc6a8269b9571a7788bee67edb62642f9f28770","branch":"HEAD"},"graphing-quadratics":{"sha":"826f094b7d9fe5557b2fb3a8677968ae89dfe394","branch":"1.2"},"joist":{"sha":"843feeb1a1c9e32194961faec92e1d15523bbcf6","branch":"HEAD"},"kite":{"sha":"a5a45cba30bc83d0400d83f03c7e4ffe06d75501","branch":"HEAD"},"perennial-alias":{"sha":"695911d0604c2bd18e9031ea4f5b26d6586bd025","branch":"HEAD"},"phet-core":{"sha":"354cc8ce376a142df9f579e2e44e438a07b56605","branch":"HEAD"},"phet-io":{"sha":"5ff1615454c98ae6bf43ccb9149ec17282d66c70","branch":"HEAD"},"phet-io-client-guides":{"sha":"1a588f974609e9665b4bdeb6c839762b7a60a4fd","branch":"HEAD"},"phet-io-wrappers":{"sha":"dd9755228f1eff6bd01448d2c6825f2e1471fcbc","branch":"HEAD"},"phetcommon":{"sha":"702911858bafc8e772a2b9d8747ef599cc2bce5c","branch":"HEAD"},"phetmarks":{"sha":"589cdbe7c499adfc1cc478b11340fc0ac61ff93d","branch":"HEAD"},"query-string-machine":{"sha":"12cfdab188ee5be9a8c1932411ad41da8b175c88","branch":"HEAD"},"scenery":{"sha":"dfc38683f72c688970cd03c26843685db92a3894","branch":"HEAD"},"scenery-phet":{"sha":"7a6b0480e7b81dc39ec48dc369bd951f59df9523","branch":"HEAD"},"sherpa":{"sha":"ec49f43aee29c836c13884be095e2772bc9faaa0","branch":"HEAD"},"studio":{"sha":"6000377b355bd90674414eae4fa4f695dc7fb40b","branch":"HEAD"},"sun":{"sha":"ca4c2fb861e678adc960a84f67b90875eaab3e1c","branch":"HEAD"},"tambo":{"sha":"e4fda961e4983c1f10aceffff14d0c91e0f50c31","branch":"HEAD"},"tandem":{"sha":"dcea61ce3483056a7!
d4750d3c51aa3f6d20365cd","branch":"HEAD"},"twixt":{"sha":"35e83120131ca1265e72d84c822a21bb557e08cb","branch":"HEAD"},"utterance-queue":{"sha":"c5024988addef3818199c1bad305d4b9c6e1e385","branch":"HEAD"}}
```

**Comment by pixelzoom** [comment]
Developers investigating phetsims/perennial#243 are confident that the deploy failed in a cleanup step, so the deploys are OK.  So closing this issue.
