### ISSUE TITLE
Review this sim in Studio

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/graphing-quadratics#139]
Pre-requisite for https://github.com/phetsims/graphing-quadratics/issues/137...

In https://github.com/phetsims/graphing-quadratics/issues/137#issuecomment-780009425, @amanda-phet said:

> @kathy-phet and I are thinking we should do another look at studio for this sim since there have likely been some changes to common code and studio practices since we last worked on this sim.
> 
> If we have changes to make to the featured list, we can do that with overrides. If anything else comes up, we will let you know @pixelzoom .

**Comment by amanda-phet** [comment]
This is complete. 

@pixelzoom let's schedule a meeting to review some of the questions and changes, and then I'll make GitHub issues for everything!

**Comment by pixelzoom** [comment]
@amanda-phet and I are going to Zoom on Tuesday, March 2 @ 11:00AM MST.

**Comment by amanda-phet** [comment]
Once #140 #141 #142 #143 #144 #145 #146 are complete, I still ned to go back to studio and feature some more elements. 

- `graphingQuadratics.exploreScreen.view.equationAccordionBox.interactiveEquationNode.visibleProperty`
- the point tool nodes and their inputEnabledProperty IDs
- point tool nodes quadraticProperty
- manipulators and inputEnabledProperty

**Comment by pixelzoom** [comment]
All change requests except #144 have been addressed and are ready for review.

Assigning this issue to @amanda-phet to follow up on https://github.com/phetsims/graphing-quadratics/issues/139#issuecomment-789834507.

**Comment by amanda-phet** [comment]
I believe this is complete after reviewing and updating overrides.
