### ISSUE TITLE
Change phetioDocumentation for PointTool positionProperty

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/graphing-quadratics#141]
For #137 and #139...

For PointTool positionProperty change phetioDocumentation to:

'position of this point tool’s crosshairs'

**Comment by pixelzoom** [comment]
@amanda-phet ready for review in master or [1.2.0-dev.1](https://phet-dev.colorado.edu/html/graphing-quadratics/1.2.0-dev.1/phet-io/).

**Comment by amanda-phet** [comment]
All looks good.
