### ISSUE TITLE
Changes to PointTool onQuadraticProperty

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/graphing-quadratics#142]
For #137 and #139...

For PointTool onQuadraticProperty:

- [x] rename to `quadraticProperty` for consistency with naming in other places
- [x] change phetioDocumentation to "the curve that this point tool is on, null if it is not on a curve”

**Comment by pixelzoom** [comment]
@amanda-phet ready for review in master or [1.2.0-dev.1](https://phet-dev.colorado.edu/html/graphing-quadratics/1.2.0-dev.1/phet-io/).

**Comment by amanda-phet** [comment]
These all look good
