### ISSUE TITLE
Make visibleProperty read-only for AccordionBox titles

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/graphing-quadratics#143]
For #137 and #139...

 For all AccordionBox titles, set visibleProperty phetioReadOnly: true

**Comment by pixelzoom** [comment]
There are 5 instances of `visibleProperty` that were changed to `phetioReadOnly: true`. Search for "AccordionBox.titleNode.visibleProperty", or see these elements:

graphingQuadratics.exploreScreen.view.equationAccordionBox.titleNode.visibleProperty
graphingQuadratics.exploreScreen.view.quadraticTermsAccordionBox.titleNode.visibleProperty
graphingQuadratics.standardFormScreen.view.equationAccordionBox.titleNode.visibleProperty
graphingQuadratics.vertexFormScreen.view.equationAccordionBox.titleNode.visibleProperty
graphingQuadratics.focusAndDirectrixScreen.view.equationAccordionBox.titleNode.visibleProperty

**Comment by pixelzoom** [comment]
@amanda-phet ready for review in master or [1.2.0-dev.1](https://phet-dev.colorado.edu/html/graphing-quadratics/1.2.0-dev.1/phet-io/).

**Comment by amanda-phet** [comment]
These all look good to me
