### ISSUE TITLE
Use inputEnabledProperty

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/graphing-quadratics#144]
For #137 and #139...

Any Node with an input listener will need to have its `inputEnabledProperty` instrumented.  These Nodes can be identified by searching for `addInputListener` in the graphing-quadratics code.  That includes:

- [x] PointToolNode (point tools)
- [x] All subclasses of GQManipulator (manipulators)

**Comment by pixelzoom** [comment]
Slack:

Chris Malley 12:57 PM
Is inputEnabledProperty read for general use? I have a request to use it in Graphing Quadratics to support disabling of draggable things.

Kathy Perkins  12:56 PM
@pixelzoom - My impression was it wasn't ready yet.

Michael Kauzmann  12:28 PM
My optimistic hope is by the end of next week.

Kathy Perkins  2:24 PM
Graphing Quadratics can wait for the pickable to be resolved, after the work for ■■■ study is completed. Yes, we will push back the date after we have a sense of when we figure out when pickable alternative is identified.

**Comment by pixelzoom** [comment]
Deferred and unassigned until the PhET-iO team tells me that `inputEnabledProperty` is ready for use.  @zepumph @samreid FYI.

**Comment by zepumph** [comment]
Sounds good. This issue will be ready to go likely as part of https://github.com/phetsims/scenery/issues/1158 though I can hold off on this repo is you would like. That issue is on hold until https://github.com/phetsims/scenery/issues/1116 is sorted out.

**Comment by pixelzoom** [comment]
> This issue will be ready to go likely as part of phetsims/scenery#1158 though I can hold off on this repo is you would like. 

FYI, there's no use of pickableProperty in this sim, which is the subject of  phetsims/scenery#1158.

**Comment by pixelzoom** [comment]
@kathy-phet said:
> Graphing Quadratics can wait for the pickable to be resolved

I interpret that to mean that we're going to wait to public until `inputEnabledProperty` is ready, so labeling this issue as blocks-publication.

**Comment by zepumph** [comment]
This is now ready for use. you can use `inputEnabledPropertyPhetioInstrumented:true` to instrument `inputEnabledProperty` instances in your sim.

**Comment by pixelzoom** [comment]
Here's a description of the sim-specific `inputEnabledProperty` elements that were added in the above commits.  

For point tools, there are 2 for each screen:
```
graphingQuadratics.*.view.leftPointToolNode.inputEnabledProperty
graphingQuadratics.*.view.rightPointToolNode.inputEnabledProperty
```

For manipulators:
```
graphingQuadratics.vertexFormScreen.view.vertexManipulator.inputEnabledProperty
graphingQuadratics.focusAndDirectrixScreen.view.focusManipulator.inputEnabledProperty
graphingQuadratics.focusAndDirectrixScreen.view.pointOnParabolaManipulator.inputEnabledProperty
graphingQuadratics.focusAndDirectrixScreen.view.vertexManipulator.inputEnabledProperty
```

@amanda-phet please review in master.

**Comment by amanda-phet** [comment]
Looks like they are all there
