### ISSUE TITLE
Change phetioDocumentation for PointTool

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/graphing-quadratics#145]
For #137 and #139, previously discussed in #77 ...

Change phetioDocumentation for leftPointTool to:
'The point tool that is initially on the left. It is typically grabbed from the left, and its probe is on the right.'

Change phetioDocumentation for rightPointTool to:
'The point tool that is initially on the right. It is typically grabbed from the right, and its probe is on the left.'

**Comment by pixelzoom** [comment]
This needed to be done for both the model and view.

In the model (`PointTool`), there was no phetioDocumentation, because PointTool is not a subclass of PhetioObject. I change that by making `PointTool extends PhetioObject` and setting `phetioState: false`.

In the view (`PointToolNode'`), I used the phetioDocumentation from the model:

```js
  phetioDocumentation: pointTool.phetioDocumentation
```

**Comment by pixelzoom** [comment]
@amanda-phet ready for review in master or [1.2.0-dev.1](https://phet-dev.colorado.edu/html/graphing-quadratics/1.2.0-dev.1/phet-io/).

**Comment by amanda-phet** [comment]
Looks good to me.
