### ISSUE TITLE
Change requests for graphingQuadratics.standardFormScreen.view.rootsNode

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/graphing-quadratics#146]
For #137 and #139...

graphingQuadratics.standardFormScreen.view.rootsNode (RootsNode.js):

- [x] When there is 1 root, rightCoordinatesProperty should have the same value as leftCoordinatesProperty (it's currently null).
- [x] rightRootNode should still be invisible if there is 1 root.
- [x] rightCoordinatesProperty should have same initial values as leftCoordinatesProperty.
- [x] Verify what happens with leftRootNode and rightRootNode if you set visibleProperty=true when there are no roots.

**Comment by pixelzoom** [comment]
Summary of changes in the above commits:

* When there is 1 root, `leftCoordinatesProperty` and `rightCoordinatesProperty` are the same.
* `leftCoordinatesProperty` and `rightCoordinatesProperty` are both intiialzed to (0,0)
* Updated phetioDocumentation for `leftCoordinatesProperty` and `rightCoordinatesProperty`
* Updates phetioDocumentation for `leftRootNode` and `rightRootNode`

Testing in Studio:

* Inspected `leftCoordinatesProperty` and `rightCoordinatesProperty`
* Inspected phetioDocumentation
* Verified that with no roots, setting visibleProperty=true for leftRootNode and rightRootNode does not result in anything being displayed. Note that visibleProperty will automatically change when the roots change, so changing visibleProperty does not result in a persistent change. So we might consider making it `phetioReadOnly: true`.

**Comment by pixelzoom** [comment]
@amanda-phet ready for review in master or [1.2.0-dev.1](https://phet-dev.colorado.edu/html/graphing-quadratics/1.2.0-dev.1/phet-io/).

Note this possible change in https://github.com/phetsims/graphing-quadratics/issues/146#issuecomment-789948803:
> ... Note that visibleProperty will automatically change when the roots change, so changing visibleProperty does not result in a persistent change. So we might consider making visibleProperty `phetioReadOnly: true`.

**Comment by amanda-phet** [comment]
>Note that visibleProperty will automatically change when the roots change, so changing visibleProperty does not result in a persistent change. So we might consider making visibleProperty phetioReadOnly: true. 

`graphingQuadratics.standardFormScreen.view.rootsNode.leftRootNode.visibleProperty` already appears to be read only, so I'm not sure I follow. We do what this to be read only, so it seems to be working correctly. 

I confirmed that the roots are behaving as requested, which is great!
