### ISSUE TITLE
Pass DerivedProperty visibleProperty to Nodes where possible

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/graphing-quadratics#149]
Over in https://github.com/phetsims/scenery/issues/1180, I learned that visibleProperty can be derived and passed to Node. As a double bonus, this eliminates the need to use `visiblePropertyOptions: { phetioReadOnly: true }` and the client does not need to observe `visibleProperty`.   So I'm going to use this wherever `visibleProperty` is derived.

**Comment by pixelzoom** [comment]
Done in the above commit.  Here's the list of elements that were touched. They should still all be read-only, because they are derived from 2 or more other Properties.

```
graphingQuadratics.vertexFormScreen.view.vertexManipulator.visibleProperty
graphingQuadratics.focusAndDirectrixScreen.view.vertexManipulator.visibleProperty
graphingQuadratics.focusAndDirectrixScreen.view.focusManipulator.visibleProperty
graphingQuadratics.standardFormScreen.view.noRealRootsNode.visibleProperty
graphingQuadratics.standardFormScreen.view.rootsNode.visibleProperty
graphingQuadratics.standardFormScreen.view.vertexNode.visibleProperty
```

@amanda-phet please review in master.

**Comment by amanda-phet** [comment]
Looks good.
