### ISSUE TITLE
design a screen for focus and directrix

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/graphing-quadratics#15]
In a conversation on 8/8/18, @amanda-phet and I discussed the directrix feature (actually focus and directrix) that appears on the _Vertex Form_ screen in the design document.  There are some problems with including this feature on this screen, namely:

- Focus and directrix is not necessarily related to vertex form.
- The optimal range for vertex form coefficients results in the focus point being covered by the vertex.  And using coefficients that work for focus point compromises the vertex form.
- Focus and directrix is an additional way to define a parabola, so (if kept) it should probably be promoted to its own screen.

Our discussion concluded with the possibility of either dropping this feature altogether or moving it to a 3rd screen.  We talked a little bit about how this screen might work, but didn't get too far. In discussions that I had with @ariel-phet, he felt strongly that it should be included, and we should design a 3rd screen.

So I've moved this feature to a 3rd _Focus & Directrix_ screen, tentatively titled based on a quick Google search of how this topic is usually referred to.   Assuming that a 3rd screen is indeed desired, I'll wait until it's specified in the design document before doing additional work on that screen.  Since this sim is moving relatively quickly, the priority is high.

**Comment by pixelzoom** [comment]
We also might consider what form of the equation is used in this screen.  Poking around, it seems like
the standard form is (x - h)<sup>2</sup> = 4p (y - k), where the focus is (h, k + p) and the directrix is y = k - p.

**Comment by amanda-phet** [comment]
I will plan to prioritize this this week and be prepared for design meeting next week on this screen.

**Comment by amanda-phet** [comment]
This was discussed in design and a design was agreed upon. There was one change to the design since then, and here is the latest mockup: 
![image](https://user-images.githubusercontent.com/7852916/45703667-3e226300-bb32-11e8-833b-f375f55ba72d.png)

**Comment by amanda-phet** [comment]
At startup, p=1, h=0, and k=8. Vertex, Focus, and Directrix are checked, Point on Quadratic and Coordinates are unchecked.

**Comment by amanda-phet** [comment]
The design is done and implementation has started so I will close this issue.
