### ISSUE TITLE
Update credits for 1.2 release

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/graphing-quadratics#155]
For https://github.com/phetsims/qa/issues/692.

I'll add Nancy Salpepi proactively, since she created issues for the dev test.

**Comment by pixelzoom** [comment]
@KatieWoe Here are the current credits. Towards the end of RC testing, me know who you'd like to add.

<img width="689" alt="screenshot_1159" src="https://user-images.githubusercontent.com/3046552/128785547-734586b8-de51-4d0b-8769-a5aed3374054.png">

**Comment by KatieWoe** [comment]
Brooklyn Lash and Emily Miller should both be added.

**Comment by pixelzoom** [comment]
QA credits were updated in master and 1.2 branches in the above commits, shown in the screenshot below.  I'll leave this issue open in case any revisions are needed for the next RC.

<img width="637" alt="screenshot_1218" src="https://user-images.githubusercontent.com/3046552/130688102-5c338d31-d7ef-4eac-a289-d70de95ccff7.png">

**Comment by KatieWoe** [comment]
No updates for rc.3

**Comment by KatieWoe** [comment]
No updates for rc.4

**Comment by pixelzoom** [comment]
Thanks @KatieWoe. Since we're now ready to publish, I'll close this issue.
