### ISSUE TITLE
Slight overlap between Point on Parabola Coordinates and Accordion Box

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/graphing-quadratics#159]
https://github.com/phetsims/qa/issues/692

In the Focus and Directrix screen, I noticed a slight overlap between the Point on Parabola values and the accordion box. After speaking with @amanda-phet, we were wondering if there was an area to make space so that this overlap doesn't happen?

<img width="444" alt="Screen Shot 2021-08-18 at 3 18 02 PM" src="https://user-images.githubusercontent.com/87318828/129958859-56254458-8c73-40b1-977b-d4263200969f.png">

<img width="444" alt="Screen Shot 2021-08-18 at 2 52 40 PM" src="https://user-images.githubusercontent.com/87318828/129957737-13b83e29-7596-4f44-91c1-d8ac6cd1cd85.png">

**Comment by pixelzoom** [comment]
The screenshot below shows the full context.

The coordinates are not overlapping anything in the accordion box, so there is no usability impact here.  But if you don't want this overlap to occur, then you have 1 option - add more horizontal space between the graph and the accordion box.  I don't think the UI will benefit in any way by increasing that space, so my recommendation is "do nothing".

<img width="1017" alt="screenshot_1199" src="https://user-images.githubusercontent.com/3046552/130364372-0de243cb-0b71-4184-9fcd-1283abe7fa26.png">
<img width="231" alt="screenshot_1198" src="https://user-images.githubusercontent.com/3046552/130364373-9366113a-94de-490a-971b-56942565edc4.png">

**Comment by pixelzoom** [comment]
Here's the closest that I could come to making the coordinates overlap something in the accordion box:

<img width="1006" alt="screenshot_1200" src="https://user-images.githubusercontent.com/3046552/130364514-67ffca9c-2142-4594-a225-9a8beaea0da9.png">

**Comment by pixelzoom** [comment]
Another option would be to limit coordinates to 1 decimal place.  But there's probably a good reason why they are 2 decimal places.

**Comment by pixelzoom** [comment]
Note that there is precedent for allowing Point On Parabola to overlap, even with other interactive UI components.  See https://github.com/phetsims/graphing-quadratics/issues/126.

**Comment by amanda-phet** [comment]
@pixelzoom thanks for finding those more dramatic cases. I thought if it was just a few pixels of overlap we might consider finding the room, since it's aesthetically annoying, but the max amount of possible overlap is too great to be able to find the space to avoid it. So I think we should leave this as-is.
