### ISSUE TITLE
add Milestones section to design document

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/graphing-quadratics#16]
Please add a *Milestones* section to the design document.  I'll be happy to help with this, but will need to know the desired 1.0 publication date.

**Comment by pixelzoom** [comment]
Raising priority to high.  Since @amanda-phet has been unavailable for awhile, I've been doing quite a bit of common-code work and have not been spending the majority of my time on this sim.  But since I don't know what the schedule is, I'm concerned that this might not be a good strategy for managing my time.

**Comment by amanda-phet** [comment]
This would be good to discuss with @kathy-phet and @ariel-phet too. As far as I know, there aren't specific milestones for publication, except that we would like to wrap up this sim quickly. With the need for a new screen design (#15 ) and my recent absences I see why things have slowed down, but that should be resolved soon. I will start an email thread.

**Comment by amanda-phet** [comment]
Added to design doc:

Features implemented by October 2018 (CM should start Gas Properties)
Dev testing and code review by October 2018
Feature-complete, dev tested version by November 13, 2018 (Amanda’s NYC workshop)
Published by Jan 31, 2019 (Google.org grant)
