### ISSUE TITLE
Point on Parabola coordinates are outside layoutBounds.

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/graphing-quadratics#160]
**Test device**
Mac11 (m1 chip)

**Operating System**
11.4

**Browser**
safari

**Problem description**
https://github.com/phetsims/qa/issues/692

In the Focus and Directrix screen, when the point on parabola is all the way on the left in quadrant III, the coordinate values box is cut off. 

**Visuals**

Normal screen size:
<img width="444" alt="Screen Shot 2021-08-18 at 4 57 25 PM" src="https://user-images.githubusercontent.com/87318828/129972561-b4941de9-dd3f-4056-a6fc-4b6a7f8c3440.png">

Full screen:
<img width="444" alt="Screen Shot 2021-08-18 at 4 57 06 PM" src="https://user-images.githubusercontent.com/87318828/129972641-f04b6362-6616-4f11-aeb8-61c293ccc0f7.png">

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Graphing Quadratics‬
URL: https://phet-dev.colorado.edu/html/graphing-quadratics/1.2.0-rc.1/phet/graphing-quadratics_all_phet.html
Version: 1.2.0-rc.1 2021-08-09 23:17:20 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Safari/605.1.15
Language: en-us
Window: 1440x683
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {}

**Comment by amanda-phet** [comment]
This is definitely going outside of the dev bounds
![image](https://user-images.githubusercontent.com/7852916/130125811-88c60acf-4a55-4d5f-9096-dab6e23946a9.png)

But I'm not sure if it's a pedagogical issue. The actual coordinates aren't that important to see at every single pixel (just that you can see a number of points on the parabola so you could verify that they make the quadratic true). 

If it's possible to flip the coordinate to the other side, we could try that. This was so long ago that I don't remember if we discussed this, but I am wondering if we did.

**Comment by pixelzoom** [comment]
> If it's possible to flip the coordinate to the other side, we could try that. This was so long ago that I don't remember if we discussed this, but I am wondering if we did.

That's not possible, it does not work for many situations, like the one shown below. We decided that the "point on parabola" coordinates are always positioned based on the sign of it's x coordinate.

There are 3 options for resolving this:
(1) Reduce the size of all coordinate displays. Not recommended.
(2) Shift the graph to the right. This will exacerbate https://github.com/phetsims/graphing-quadratics/issues/159.
(3) Reduce the width of the graph. 

<img width="1018" alt="screenshot_1201" src="https://user-images.githubusercontent.com/3046552/130364622-c4c71e12-9626-4283-bed0-2e47cf82700e.png">

**Comment by pixelzoom** [comment]
@amanda-phet this same issue was discussed in https://github.com/phetsims/graphing-quadratics/issues/91.   You concluded that this was OK.   It's fine if you'd like to change your mind, just reminding you of the history.

**Comment by amanda-phet** [comment]
>@amanda-phet this same issue was discussed in #91. You concluded that this was OK. It's fine if you'd like to change your mind, just reminding you of the history.

Thank you! I was starting to think this sounded familiar, and since I pointed out that it's not a pedagogical issue, I think we should still leave it as it is.
