### ISSUE TITLE
Point Tool coordinates are outside of layoutBounds.

### ISSUE THREAD

**Issue by brooklynlash** [phetsims/graphing-quadratics#161]
**Test device**
Lenovo

**Operating System**
Windows 10

**Browser**
Chrome

**Problem description**
For https://github.com/phetsims/qa/issues/692, may be similar to [#106](https://github.com/phetsims/graphing-quadratics/issues/160) but I think a new issue is warranted. 
Able to be seen on all screens. The gray draggable coordinate box with the circle on the right can have coordinate points partially out of view if the point is close to the edge of the graph. 

**Steps to reproduce**
1. Go to [iframe of Graphing Quadratics](https://phet-dev.colorado.edu/html/graphing-quadratics/1.2.0-rc.1/phet/graphing-quadratics_all_iframe_phet.html)
2. Make a graph that extends its points very close to the left edge of the graph. 
3. Use the left draggable box to collect and snap on a point near the edge. 
4. The first number is usually unable to be seen because it is past the iframe. 

**Visuals**
![quadratics2](https://user-images.githubusercontent.com/72031637/130141852-337ff980-3783-4dd2-b164-cf26c876312a.PNG)
![quadratics3](https://user-images.githubusercontent.com/72031637/130141854-68caccb3-cb79-409a-a627-7da136f81616.PNG)
![quadratics4](https://user-images.githubusercontent.com/72031637/130141857-94c7852b-3bcd-4c9b-818b-dcbb2e32e787.PNG)

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Graphing Quadratics‬
URL: https://phet-dev.colorado.edu/html/graphing-quadratics/1.2.0-rc.1/phet/graphing-quadratics_all_phet.html
Version: 1.2.0-rc.1 2021-08-09 23:17:20 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36
Language: en-US
Window: 1707x817
Pixel Ratio: 2.25/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4095
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

**Comment by pixelzoom** [comment]
This is a problem we encountered before, but it doesn't appear to have been documented in a GitHub issue. 

What we had decided previously is that we wanted the graph to be as large as possible. So if someone had a problem viewing coordinates using one point tool, they should use the other point tool. That is one of the reasons why we have point tools with probes on different sides.

If you want the display area of both tools to always be fully visible, then you'll need a large amont of space around the graph. So you'll need to shrink the graph quite a bit.  (And keep in mind that the amount of space needed is going to increase if we decide to show 2 decimal places for each coordinate in https://github.com/phetsims/graphing-quadratics/issues/158.)   As you shrink the size of the graph, you may also need to shrink the size of some of the things on the graph - for example manipulator may need to be smaller.  

Making the graph smaller will negatively impact usability, and is a poor use of space.  So my recommendation here is "do nothing".

**Comment by amanda-phet** [comment]
I agree that we should do nothing for this issue. There are two potential point tools that the user can use, so I'm not concerned about the usability.
