### ISSUE TITLE
Generalize "point tool body".

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/graphing-quadratics#167]
As discussed in https://github.com/phetsims/graphing-quadratics/issues/158...

graphing-lines and graphing-quadratics both have "point tools". But they have different implementations of PointTool (model) and PointToolNode (view).  The reason for that is documented in #18. (graphing-slope-intercept consists of a screen from graphing-lines, so uses the point tool from graphing-lines.)

Both implementations of PointToolNode use .png files that were exported from graphing-lines/asserts/point_tool.ai.  Then we needed a wider display area (to show more decimal places) in https://github.com/phetsims/graphing-quadratics/issues/158, so we copied point_tool.ai to graphing-quadratics/asserts/point_tool.ai, and made adjusts specific to https://github.com/phetsims/graphing-quadratics/issues/158, to be released in Graphing Quadratics 1.2.

We realized that a better long-term solution is to ditch the .ai and .png files for PointToolNode, and create a "point tool body" (`PointToolBodyNode`?) programmatically.  It should be parameterized to handle different sizes of display area, different sizes of "grippy" area, different colors, etc.   The basic body shape will use `ShadedRectangleNode`.  The grippy parts will likely be a set of Paths that are filled with a LinearGradient to give the illusion of being lit from above.

`PointToolBodyNode` will not include the probe part of the tool. Adding a sim-specific probe will be the responsibility of the client application.

This mockup by @amanda-phet shows the revised PointToolNode on the right:

![image](https://user-images.githubusercontent.com/7852916/130483864-1f956b86-a521-4e93-b2ed-28756dc51de7.png)

**Comment by pixelzoom** [comment]
This issue is deferred until Graphing Quadratics 1.2 is published https://github.com/phetsims/graphing-quadratics/issues/137.

**Comment by pixelzoom** [comment]
Self assigning. I'll probably have some time to do this after Graphing Quadratics 1.2 is published.

**Comment by pixelzoom** [comment]
@amanda-phet ready for review in master. I used your mockup (above) as a guide for colors, spacing, etc.

Here are before and after screenshots.

Graphing Quadratics:

<img width="787" alt="screenshot_1230" src="https://user-images.githubusercontent.com/3046552/133318933-997923f6-f4d3-4d5a-b43e-df1e5e75ca88.png">
<img width="791" alt="screenshot_1229" src="https://user-images.githubusercontent.com/3046552/133318950-04a4d93e-c23f-4c8a-bef5-a428710f1dc1.png">

Graphing Lines:

<img width="788" alt="screenshot_1232" src="https://user-images.githubusercontent.com/3046552/133319058-f10d3553-fe09-477e-9bc0-f6499de5c9da.png">
<img width="791" alt="screenshot_1231" src="https://user-images.githubusercontent.com/3046552/133319027-149f2920-85fe-4e47-b1b7-565c8ba44408.png">

Also note that Level 3 of the _Line Game_ screen in Graphing Lines has point tools as the reward. Run the sin with `?showReward`, play Level 3 (no need to get any correct answers), and you'll see a reward that uses the new point tool:

<img width="791" alt="screenshot_1234" src="https://user-images.githubusercontent.com/3046552/133319407-632fcbd7-dbd6-4449-9b35-f8be422cf281.png">

**Comment by pixelzoom** [comment]
I should also note that I did NOT migrate `PointToolBodyNode` to common code.  There's not a clear place for that, and it's currently used only within the "graphing lines" family of sims.  So as with the other components that are shared by that family, it currently lives in the graphing-lines repo.  If/when a more general use is needed, `PointToolBodyNode` is very general, and can be easily migrated to some other repo.

**Comment by amanda-phet** [comment]
Looks like a nice change overall. Thanks for making this happen @pixelzoom !

**Comment by pixelzoom** [comment]
Screenshots will need to be revised for the sims that use the point tool. I've created issues for each sim, linked above.

This issue is done, and is ready to be verified in a future QA process.
