### ISSUE TITLE
Make Point On Parabola snap to displayed x value, like Point Tool.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/graphing-quadratics#172]
In https://github.com/phetsims/graphing-quadratics/issues/169#issuecomment-909518229, @stemilymill reported:

> https://github.com/phetsims/qa/issues/704
> 
> The snapping behavior of the point tool is correct, but I noticed that in the Focus & Diretrix screen, the Point on Parabola graph option shows the old behavior with multiple y-values for one x-value. @amanda-phet is this ok, or should the behavior match the point tool? 

![same x different y graph options point on parabola](https://user-images.githubusercontent.com/85511101/131560644-ecee9c0e-6355-410d-909d-d313e53084bf.gif)

**Comment by pixelzoom** [comment]
This can certainly be done, but it a new issues.

@amanda-phet is this something that you want done? And do you want it for the 1.2 release?

**Comment by pixelzoom** [comment]
Note to self...  

This involves taking this bit of code from `PointToolNode.PointToolDragListener`:

```js
            // We will be snapping the x value as it will be displayed by the point tool.
            // See See https://github.com/phetsims/graphing-quadratics/issues/169.
            let x = Utils.toFixedNumber( position.x, GQConstants.POINT_TOOL_DECIMALS );
...
            const y = snapQuadratic.solveY( x );
            position = new Vector2( x, y );
```

... and injecting it into `PointOnParabolaManipulator.PointOnParabolaDragListener`.

**Comment by amanda-phet** [comment]
I think we should make this change since the goals of the point on parabola are very similar to the point tool.

**Comment by pixelzoom** [comment]
Done in master and 1.2 branches. @amanda-phet please review in master.

**Comment by amanda-phet** [comment]
Looks great!

**Comment by pixelzoom** [comment]
Ready for testing in the next RC.  To verify:

1. Go to the Focus & Directrix screen
2. Check the "Point on Parabola" checkbox
3. Keep the "Coordinates" checkbox checked
4. Move the "Point on Parabola" manipulator (red sphere) along the curve.  Verify that for each x coordinate shown, you only see one y coordinate value.
5. Verify with various configurations of the curve, especially ones with a steep slope.

**Comment by Nancy-Salpepi** [comment]
I was unable to find any instances where the same x value had multiple y values. When the y coordinate value changed, so did the x value.
