### ISSUE TITLE
Revise screenshots.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/graphing-quadratics#174]
The look of the point tool was changed in https://github.com/phetsims/graphing-quadratics/issues/167, so screenshots will need to be revised.  This does not need to be addressed proactively, as other visual changes might be made before this sim is republished.

**Comment by pixelzoom** [comment]
@amanda-phet You can attached screenshots to this issue. I'll check them into GitHub and integrate into the sim.  See https://github.com/phetsims/graphing-quadratics/tree/master/assets for the list of screenshots.

**Comment by amanda-phet** [comment]
All screenshots are in the assets folder. Tagging as ready for review by QA.

**Comment by pixelzoom** [comment]
I reviewed this again for https://github.com/phetsims/graphing-quadratics/issues/176, to make sure there have been no significant changes in the past year that require new screenshots.  The size of icons in the navigation bar have change a little bit, but not enough to be noticable in screenshots.  And there are no new features or changes that would require new screenshots.  So we're still good to go here.

**Comment by KatieWoe** [comment]
Does the addition of the preferences menu icon require new screenshots?

**Comment by pixelzoom** [comment]
Since @arouinfar will be the one who has to make the screenshots, I'm going to defer to her.  But my opinion is that changes to the navigaiton batr (like the Preferences button) are not significant enough (or visibile enough) to be a require new screenshots.

**Comment by pixelzoom** [comment]
I should also note that the Preferences button only appears in the "all" version of the sim.  It's not present in locale-specific versions because there are no sim-specific Preferences.  So this is a good reason NOT to show the Preferences button in screenshots.

**Comment by arouinfar** [comment]
> But my opinion is that changes to the navigaiton batr (like the Preferences button) are not significant enough (or visibile enough) to be a require new screenshots.

I agree. I don't think we need to take new screenshots in this situation.

> I should also note that the Preferences button only appears in the "all" version of the sim. It's not present in locale-specific versions because there are no sim-specific Preferences. So this is a good reason NOT to show the Preferences button in screenshots.

We now serve the "all" version of the simulation on the sim page, so I think it's fine for the Preferences button to show up in screenshots. I just don't think we need to retake screenshots for that sole reason, closing.
