### ISSUE TITLE
Graphing Quadratics - Publish 1.3 with PhET-iO Upgrades

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/graphing-quadratics#176]
As part of the "batch release" milestone https://github.com/orgs/phetsims/projects/44, publish Graphing Quadratics, for brands=phet,phet-io.

**Comment by pixelzoom** [comment]
Unassigning until this becomes a priority.

**Comment by pixelzoom** [comment]
For the 6/9-6/28 iteration, a task is to get this sim ready for dev testing. Self-assigning.

**Comment by pixelzoom** [comment]
6/22/23 GitHub issue was created for dev test. Dev version will be deployed when QA is ready to begin.

* https://github.com/phetsims/qa/issues/959

**Comment by arouinfar** [comment]
6/27/23 dev.5 was deployed and QA started testing for https://github.com/phetsims/qa/issues/959

**Comment by pixelzoom** [comment]
7/7/23 1.3.0-rc.1 was deployed for RC testing:

* https://github.com/phetsims/qa/issues/962

**Comment by pixelzoom** [comment]
7/24/23 1.3.0-rc.2 was deployed for RC testing:

* https://github.com/phetsims/qa/issues/965

**Comment by pixelzoom** [comment]
7/25/23 1.3.0-rc.3 was deployed for RC testing:

* https://github.com/phetsims/qa/issues/966

EDIT: Test completed 7/25/2023.

**Comment by pixelzoom** [comment]
7/25/2023 Graphing Quadratics 1.3.0 was published.
