### ISSUE TITLE
Update QA credits for 1.3 release.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/graphing-quadratics#177]
Update QA credits for 1.3 release.

**Comment by KatieWoe** [comment]
Clifford Hardin should be added to QA credits.

**Comment by KatieWoe** [comment]
Jaron Droder should be added for QA

**Comment by pixelzoom** [comment]
Ready for testing with the Migration wrapper in 1.3.0-rc.2.   Please assign back to me when testings is completed.

**Comment by Nancy-Salpepi** [comment]
QA credits look good. No further changes needed.

**Comment by pixelzoom** [comment]
For 1.3.0-rc.3, please identify any changes to the QA credits, and assign back to me.

**Comment by KatieWoe** [comment]
No updates needed for rc.3

**Comment by pixelzoom** [comment]
Proceeding with publication of 1.3.0, so it's now safe to close this issue.
