### ISSUE TITLE
Add support for dynamic locale

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/graphing-quadratics#178]
... similar to what was done in https://github.com/phetsims/natural-selection/issues/319.

@kathy-phet said:
> And this isn't a current priority, so let's visit that one after you have these others converted

Note that since graphing-lines is a dependency of this sim, this will also involve touching graphing-lines.

**Comment by pixelzoom** [comment]
Unassigning until this becomes a priority.

**Comment by pixelzoom** [comment]
This is done. Supporting dynamic strings is a lot of work when those strings appear in equations, and it required major layout changes in this sims.

Ready for review when this sim gets scheduled for re-publishing.

**Comment by pixelzoom** [comment]
Getting this sim ready for dev testing is a task for June 9-29 iteration, so relabeling this issue accordingly.

**Comment by arouinfar** [comment]
@pixelzoom I reviewed Graphing Quadratics on master with `stringTest=dynamic` and the layout reflows really nicely. I didn't notice any issues with `maxWidth` or layout changes.
