### ISSUE TITLE
PhET-iO design review for 1.3 release

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/graphing-quadratics#180]
#178 (add support for dynamic locale) will certainly result in many API changes, and there have been many common-code API changes and additions.  So this sim will require a full design review of the PhET-iO API.

**Comment by pixelzoom** [comment]
Getting this sim ready for dev testing is a task for June 9-29 iteration, so relabeling this issue accordingly.

**Comment by pixelzoom** [comment]
> Getting this sim ready for dev testing is a task for June 9-29 iteration

Noting that I’ll be unavailable June 23-29. So we’ll need complete this review in time + change requests by next Thursday, June 22.  Sorry I didn’t note this sooner.

**Comment by pixelzoom** [comment]
@arouinfar anything else to do here, or can this issue be closed?

**Comment by arouinfar** [comment]
I generally like to keep these review issues open until I complete examples.md just in case I run into any other issues along the way. Examples.md has been completed, no further issues to report, closing.
