### ISSUE TITLE
Instrument PatternStringProperty and DerivedProperty for strings that need to be autoselectable in Studio.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/graphing-quadratics#186]
https://github.com/phetsims/graphing-quadratics/issues/178 resulted in a bunch of new DerivedProperty instances that dynamically create strings that appear in the UI.   Per https://github.com/phetsims/phet-io/issues/1942, they will need to be instrumented for PhET-iO.  And per https://github.com/phetsims/fourier-making-waves/issues/235, we need to decided where they live in the Studio tree.

**Comment by pixelzoom** [comment]
There are no PatternStringProperty in this sim, so just DerivedProperty.

**Comment by pixelzoom** [comment]
This is on-hold until we wrap up https://github.com/phetsims/fourier-making-waves/issues/235, in which we're deciding where derived strings live in the Studio tree.

**Comment by pixelzoom** [comment]
For this sim, I'm going to take a different approach than https://github.com/phetsims/fourier-making-waves/issues/235.   I'm not going to instrument the RichText markup that is added to math symbols (the Properties in GQSymbols.ts).  Those cases add the most "nesting" to dependencies, and seemed to be the least useful in Fourier. I've noted this a code comment via the commit above.

The result of this decision: strings that appear in the UI and contain symbols are not autoselectable in Studio.  The set of symbols is: _a_, _b_, _c_, _h_, _k_, _p_, _x_, _x<sup>2</sup>_, _y_

@arouinfar please review in Studio and let me know how this feels.

@zepumph @samreid FYI.

**Comment by arouinfar** [comment]
Thanks @pixelzoom. As expected, there is quite a bit of text that is not autoselectable, but it all pertains to equations and related coefficients. The experience does not seem buggy, and I think it's easier to direct users to things like `aStringProperty` rather than have them traverse nested dependencies. I'm tracking examples in #189, so we can close this issue.
