### ISSUE TITLE
Create examples.md

### ISSUE THREAD

**Issue by arouinfar** [phetsims/graphing-quadratics#189]
For #180 

- [ ] Derived strings are not autoselectable, see #186. This means the characters used for coefficients and variables are not discoverable with autoselect. There may be different conventions for labeling these quantities, so clients could want to customize these strings. Include an example explaining how to customize a, b, c, h, k, etc.

**Comment by pixelzoom** [comment]
@arouinfar If this is not completed before dev testing begins in https://github.com/phetsims/qa/issues/959, please provide QA with instructions on what they should do about examples.md.

**Comment by arouinfar** [comment]
Examples updated in the above commits, closing.
