### ISSUE TITLE
review pointer areas

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/graphing-quadratics#19]
Test with `showPointerAreas` query parameter. Deferred until the sim is feature complete.

**Comment by pixelzoom** [comment]
@amanda-phet pointer areas are ready for your review in [1.0.0-dev.16](https://phet-dev.colorado.edu/html/graphing-quadratics/1.0.0-dev.16/phet/graphing-quadratics_en_phet.html). Pointer areas for manipulators, pickers and buttons are identical to Graphing Lines.

**Comment by amanda-phet** [comment]
All of these look fine to me.
