### ISSUE TITLE
Uninstrument `equationAccordionBox.titleNode`

### ISSUE THREAD

**Issue by arouinfar** [phetsims/graphing-quadratics#190]
For #180 

In #187 Text and RichText were uninstrumented, including things like `titleText`. However, it looks like @pixelzoom may have missed one:

`exploreScreen.view.equationAccordionBox.titleNode` 
<img width="258" alt="image" src="https://github.com/phetsims/graphing-quadratics/assets/8419308/8f28e4e6-7d85-42da-9e2b-eb9781591560">

There isn't any reason to instrument this `titleNode`. Its only child is a read-only `visibleProperty` whose value never changes.

**Comment by pixelzoom** [comment]
`equationAccordionBox.titleNode` was uninstrumented throughout in the above commit. @arouinfar please review, close if OK.

**Comment by pixelzoom** [comment]
This change also required migration rules (see above commit), which git-hooks did not check for me. Luckily I remembered to check manually using the Migration wrapper.  Had I deferred until publishing, this would have been a lot more work to figure out what/where went wrong.

**Comment by arouinfar** [comment]
Thanks @pixelzoom, looks good. Glad you tested things out in the Migration wrapper!
