### ISSUE TITLE
Add link to `model.*PointTool` to corresponding view element

### ISSUE THREAD

**Issue by arouinfar** [phetsims/graphing-quadratics#191]
For #180 

The Point Tools contain useful information in both the model and the view. It would be helpful to connect `view.leftPointTool` and `view.rightPointTool` to their corresponding model elements. I find myself trying to autoselect my way to the model with `ctrl` and come up with nothing.

This also means we should make the parent view elements `phetioFeatured: true` so the links show up in the Featured tree.

**Comment by pixelzoom** [comment]
Done in the above commits, with API change. See Studio tree screenshot below. @arouinfar please review, close if OK.

<img width="240" alt="screenshot_2625" src="https://github.com/phetsims/graphing-quadratics/assets/3046552/9d0b68bd-6b86-45fa-9969-b9f6ab042ae3">

**Comment by arouinfar** [comment]
Thanks @pixelzoom. Can you also feature `view.*PointToolNode` so these links show up in the Featured tree?

**Comment by pixelzoom** [comment]
>  Can you also feature `view.*PointToolNode` so these links show up in the Featured tree?

Oh right, duh... you asked for that.  Done in the above commit.

**Comment by arouinfar** [comment]
Looks great, thanks!

**Comment by arouinfar** [comment]
Rookie mistake, I reviewed with "All" selected.

I see that `view.rightPointTool` and `view.LeftPointTool` are featured, but the links aren't showing up because the target elements `model.rightPointTool` and `model.leftPointTool` aren't featured, just their children.

Sorry to send this back again @pixelzoom.

**Comment by pixelzoom** [comment]
Good catch, fixed in the above commits. Back to @arouinfar to verify.

**Comment by arouinfar** [comment]
Looks good in master, thanks @pixelzoom
