### ISSUE TITLE
Equation AccordionBox doesn't properly resize when `interactiveEquationNode` is partially hidden

### ISSUE THREAD

**Issue by arouinfar** [phetsims/graphing-quadratics#192]
For #180 

When all three sliders in the Equation AccordionBox are hidden, the layout does not dynamically change to eliminate the blank space.
`equationAccordionBox.interactiveEquationNode.*Slider.visibleProperty`

<img width="376" alt="image" src="https://github.com/phetsims/graphing-quadratics/assets/8419308/e6f0d548-c232-455c-9723-8e7a6d26e7bf">

Hiding the  `interactiveEquationNode` resizes things as expected, however.
<img width="157" alt="image" src="https://github.com/phetsims/graphing-quadratics/assets/8419308/4d74fe6e-4df2-4dc4-8bbd-9252fc8ae00d">

**Comment by arouinfar** [comment]
Actually, this appears to be a more general issue with the `interactiveEquationNode` which contains the sliders and an `equationNode`.
<img width="228" alt="image" src="https://github.com/phetsims/graphing-quadratics/assets/8419308/9d9ed0bd-484f-4d07-a7c3-dff62a778f8b">


Hiding `interatctivieEquationNode.equationNode` also results in a gap in the layout.
<img width="204" alt="image" src="https://github.com/phetsims/graphing-quadratics/assets/8419308/def08fd1-0ba6-4de0-ae03-44f39caef3d4">

**Comment by pixelzoom** [comment]
Reproduced in master.

**Comment by pixelzoom** [comment]
Fixed in the above commit. @arouinfar please review, close if OK.

**Comment by pixelzoom** [comment]
Fixed in the above commit. @arouinfar please review, close if OK.

**Comment by arouinfar** [comment]
Thanks @pixelzoom. Looks good in master, closing.
<img width="202" alt="image" src="https://github.com/phetsims/graphing-quadratics/assets/8419308/90161edc-79cc-4ae8-b10f-bc31702d9381">
<img width="190" alt="image" src="https://github.com/phetsims/graphing-quadratics/assets/8419308/c8a760d8-d494-4a6c-8e51-ade459e12454">
