### ISSUE TITLE
Missing separator at top of equationAccordionBox content.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/graphing-quadratics#193]
While working on https://github.com/phetsims/graphing-quadratics/issues/192, I noticed that we lost the separator at the top of every `equationAccordionBox`.   The separator is still in the code, but because there's nothing about it in "content" of the accordion box, scenery's layout manager automatically hides it.   This is because scenery takes a very literal view of "separator" -- there must be a visible Node on both sides of the separator, or it will be hidden.

Here is `equationAccordionBox` in the 4 screens of the published version (1.2.13):

<img width="368" alt="screenshot_2626" src="https://github.com/phetsims/graphing-quadratics/assets/3046552/d0637c05-6d81-450f-b53c-b30bcf7ce9e3">
<img width="319" alt="screenshot_2627" src="https://github.com/phetsims/graphing-quadratics/assets/3046552/16f58031-cdcd-470a-9d89-95912794ccd1">
<img width="311" alt="screenshot_2628" src="https://github.com/phetsims/graphing-quadratics/assets/3046552/1d3568c7-ebbb-4e2c-b0d4-21862c2a5d99">
<img width="385" alt="screenshot_2635" src="https://github.com/phetsims/graphing-quadratics/assets/3046552/63d984fe-757c-42b0-99c8-ce8701b65fbe">

Compare to master. Note the absence of the separator between the accordion box's title and content.

<img width="358" alt="screenshot_2630" src="https://github.com/phetsims/graphing-quadratics/assets/3046552/1d08a50f-9dff-49f2-ae9d-efa575f0a2d7">
<img width="312" alt="screenshot_2632" src="https://github.com/phetsims/graphing-quadratics/assets/3046552/be85147a-db08-4aa1-854e-9ac3fe96ed17">
<img width="327" alt="screenshot_2633" src="https://github.com/phetsims/graphing-quadratics/assets/3046552/43e33e45-abbc-4a94-9f38-9999840d2fe3">
<img width="389" alt="screenshot_2634" src="https://github.com/phetsims/graphing-quadratics/assets/3046552/4faa5702-110e-4ec3-8f39-2cb7591e2f12">

**Comment by pixelzoom** [comment]
Fixed in the above commits, and the restored separator automatically disappears if not needed.  @arouinfar please reivew, compare to published version 1.2.13 at https://phet.colorado.edu/sims/html/graphing-quadratics/latest/graphing-quadratics_all.html.  And beware of https://github.com/phetsims/sun/issues/848 - if the entire content of an AccordionBox is hidden, the entire AccordionBox becomes invisible.

**Comment by arouinfar** [comment]
Good catch! Looks good in master, closing.
