### ISSUE TITLE
Unable to autoselect strings of variables

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/graphing-quadratics#198]
**Test device**
MacBook Air M1 chip

**Operating System**
13.4

**Browser**
Safari 16.5

**Problem description**
For https://github.com/phetsims/qa/issues/959, in Studio `shift` + `alt/opt` doesn't work for any of the variables (x, y, a, b, c) even though they all have string properties. 
<img width="240" alt="Screenshot 2023-06-28 at 3 01 35 PM" src="https://github.com/phetsims/graphing-quadratics/assets/87318828/271e3b45-7454-46a8-861c-9d602b82791d">
<img width="142" alt="Screenshot 2023-06-28 at 3 01 47 PM" src="https://github.com/phetsims/graphing-quadratics/assets/87318828/10c1e7c8-0b90-4962-9d5c-a9fbc608fca0">

**Steps to reproduce**
1. In Studio: on any screen hover over a variable and press `shift` + `alt/opt`

**Comment by zepumph** [comment]
This was a designed choice. Closing as a won't fix.

**Comment by arouinfar** [comment]
@zepumph is correct, this was a design choice, but I did document how to change the strings in the examples doc. https://phet-dev.colorado.edu/html/graphing-quadratics/1.3.0-dev.5/phet-io/doc/guides/examples.html#rename-the-coefficients
