### ISSUE TITLE
Typo in examples

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/graphing-quadratics#199]
For https://github.com/phetsims/qa/issues/959

In the  **Hold a Term **Constant**** section, under **Focus & Directrix Screen** you have the 'k' slider listed twice instead of the 'h' slider. 

<img width="934" alt="Screenshot 2023-06-28 at 7 49 04 PM" src="https://github.com/phetsims/graphing-quadratics/assets/87318828/e2ec18cf-28c2-43bb-ade0-8eb65374dc67">

**Comment by arouinfar** [comment]
Good catch @Nancy-Salpepi! Fixed in the above commit, closing.
