### ISSUE TITLE
review stringTest

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/graphing-quadratics#20]
After implementing i18n, test with various `stringTest` query parameter values. Deferred until the sim is feature complete.

The stringTest checklist is:

- [ ] stringTest=long (exceptionally long strings)
- [ ] stringTest=double (all strings doubled)
- [ ] stringTest=X (short strings)
- [ ] stringTest=rtl (right-to-left)
- [ ] stringTest=xss (security test, passes if sim does not redirect to another URL)

**Comment by pixelzoom** [comment]
@amanda-phet This is ready for verification, see [1.0.0-dev.22](https://phet-dev.colorado.edu/html/graphing-quadratics/1.0.0-dev.22/phet/graphing-quadratics_en_phet.html) and the checklist above.  In particular, note that text is the only thing that scales; UI components (buttons, checkboxes, pickers, sliders, icons) do not scale, so that their sizes remain consistent, and the sim remains usable.

**Comment by pixelzoom** [comment]
@amanda-phet note the updated dev version in the previous commit.

**Comment by amanda-phet** [comment]
I looked at each stringtest and nothing looked wrong to me. Should we keep this open for QA to verify, or will they verify separately?

**Comment by pixelzoom** [comment]
QA will verify as part of their standard process. So closing this issue.
