### ISSUE TITLE
Should `vertexNode` be featured?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/graphing-quadratics#203]
Discovered while working on https://github.com/phetsims/graphing-quadratics/issues/202 ...

Should `graphingQuadratics.standardFormScreen.view.graphNode.vertexNode` be featured?  All of the other points and manipulators on the graphs are featured, including:

graphingQuadratics.standardFormScreen.view.graphNode.rootsNode
graphingQuadratics.vertexFormScreen.view.graphNode.vertexManipulator
graphingQuadratics.focusAndDirectrixScreen.view.graphNode.focusManipulator
graphingQuadratics.focusAndDirectrixScreen.view.graphNode.pointOnParabolaManipulator
graphingQuadratics.focusAndDirectrixScreen.view.graphNode.vertexManipulator

**Comment by arouinfar** [comment]
Good catch @pixelzoom. Yes, let's feature the `vertexNode` too.

**Comment by pixelzoom** [comment]
vertexNode is now featured, see commits above to master and 1.3.  @arouinfar please review. If everything looks OK, please change the label to "fixed-awaiting-deploy" for verification in the next RC.

**Comment by arouinfar** [comment]
Looks good, thanks @pixelzoom.

**Comment by pixelzoom** [comment]
To verify in 1.3.0-rc.2:

1. Run the sim in Studio
2. Search for `vertextNode` in the tree. There should be 1 element.
3. Verify that `vertexNode` is "Featured: true".

**Comment by pixelzoom** [comment]
In Slack#DM, @KatieWoe pointed out that none of the elements listed in https://github.com/phetsims/graphing-quadratics/issues/203#issue-1803889453 are featured.  They appear in the featured tree because a child element (typically `visibleProperty` and/or `inputEnabledProperty`) is featured.  So by featuring `vertexNode`, we are now inconsistent.

@arouinfar How would you like to address this?

**Comment by pixelzoom** [comment]
If we want to be consistent with the elements listed in https://github.com/phetsims/graphing-quadratics/issues/203#issue-1803889453, it looks like we should unfeature `vertexNode`, and feature `vertexNode.visibleProperty`.  Does that seem correct?

**Comment by pixelzoom** [comment]
> ...  Does that seem correct?

Nope. `rootsNode.visibleProperty` is not featured.  If we want to be consistent, we should back out these changes entirely, by unfeaturing `vertexNode`.

**Comment by arouinfar** [comment]
Good find @KatieWoe. 

> Nope. `rootsNode.visibleProperty` is not featured.  If we want to be consistent, we should back out these changes entirely, by unfeaturing `vertexNode`.  

Agreed, let's back out these changes @pixelzoom.

**Comment by pixelzoom** [comment]
Will do. My bad on this one.  Will require another RC spot check.

**Comment by pixelzoom** [comment]
The featuring of `vertexNode` was reverted in the above commits.  

To verify in 1.3.0-rc.3:

1. Run the sim in Studio
2. Select the "All" radio button to see all elements in the Studio tree.
3. Search for `vertextNode` in the tree.
4. Verify that vertexNode is "Featured false".

**Comment by KatieWoe** [comment]
This looks to be fixed in 1.3.0-rc.3
