### ISSUE TITLE
point tool problems

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/graphing-quadratics#22]
The point tool should work for all lines (curved and straight) that are displayed on the graph.  It currently has the following problems:

- [x] does not always work for the primary and saved quadratic, e.g. when -1 < a < 1.  See `nearestPointOnLineToPoint` in `Quadratic`.
- [x] does not work for the lines that represent the terms of the quadratic (y=ax^2, y=bx, y=c)

**Comment by pixelzoom** [comment]
The reuse of `GRAPHING_LINES/PointTool` has an additional problem. `PointTool` was designed to be used with `GRAPHING_LINES/Line[]`.  But it's being passed `GRAPHING_QUADRATIC/Quadratic[]`, which does not extend Line.  

`PointToolNode` (both the GRAPHING_LINES and GRAPHING_QUADRATIC implementations) have the same problem.

**Comment by pixelzoom** [comment]
While working on #18, I broke the color highlighting of the point tool. So that needs to be fixed.

**Comment by pixelzoom** [comment]
To resolve the issue noted in https://github.com/phetsims/graphing-quadratics/issues/22#issuecomment-415181856, graphing-quadratics will have it's own `PointTool` and `PointToolNode` that are specific to type `Quadratic`.

**Comment by pixelzoom** [comment]
@amanda-phet Should the point tool interact with the axis of symmetry or directrix?

**Comment by amanda-phet** [comment]
I think of those as special lines, and we are making a point of distinguishing them from other functions by making them dashed. These are lines that are used to help describe the parabola. So, no, the point tool should not interact with those two lines.

**Comment by pixelzoom** [comment]
Reported by @kathy-phet via Slack:
>  The point tools pick up if they are on the line even when they are outside of the visible graph. I randomly hit them in this situation: see how they are black.

![image 1](https://user-images.githubusercontent.com/3046552/45648837-e37ffd00-ba86-11e8-93b4-72df98fa26a3.png)

**Comment by pixelzoom** [comment]
- [ ] Point tools also have a problem with their drag bounds. They probably need different drag bounds, since their probes are now on the left and right.

**Comment by pixelzoom** [comment]
All issues have been addressed for point tool.  It now works reliably, and works for term of the quadratic.
