### ISSUE TITLE
behavior of coefficient sliders

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/graphing-quadratics#23]
From the design document:

> The sliders control the values of a, b, and c for the graphed parabola. They range from [-6,6] each, and the value is rounded to the nearest hundredth. 
>
> The values do not change in a linear way, to keep the motion smooth. This is probably a logarithmic scale, but we will need to tinker with it. 
> 
> When the slider gets within a few pixels of 0, it snaps to 0? 
> 
> _Default: a=1, b=0, c=0_

After experimenting with various behavior (including log scale), here's what I arrived at:

- _a_ slider behavior is quadratic
- _b_ and _c_ sliders behavior is linear
- _a_ slider snaps to zero when |value| < 0.05
- _b_ and _c_ sliders snaps to zero when |value| < 0.1

Demonstrated in [1.0.0-dev.5](https://phet-dev.colorado.edu/html/graphing-quadratics/1.0.0-dev.5/phet/graphing-quadratics_en_phet.html).  @amanda-phet please review, specify what you'd like to change.

**Comment by amanda-phet** [comment]
I think we might want a to snap to zero when |a| < 0.03. 0.05 seems too far from 0 and it looked a little jumpy when I moved the slider up and down past 0. 

b and c seem fine to me, although they don't feel "snappy" around 0, but the important thing is that I can get 0 if I want it.

**Comment by pixelzoom** [comment]
@amanda-phet said:
> I think we might want a to snap to zero when |a| < 0.03. 0.05 seems too far from 0 and it looked a little jumpy when I moved the slider up and down past 0.

Done in the above commit. You can try this is master, or let me know if you'd like a dev version  

> b and c seem fine to me, although they don't feel "snappy" around 0, but the important thing is that I can get 0 if I want it.

Making these sliders feel more "snappy" around zero would require increasing the snap interval to > 0.1.   And then you wouldn't be able to get to 0.1, which seems odd since these sliders display 1 decimal place.

**Comment by amanda-phet** [comment]
Just checked in master. I like this change a lot. Thank you!

**Comment by amanda-phet** [comment]
@pixelzoom want to close after a dev version is published?

**Comment by pixelzoom** [comment]
@amanda-phet feel free to close if [1.0.0-dev.6](https://phet-dev.colorado.edu/html/graphing-quadratics/1.0.0-dev.6/phet/graphing-quadratics_en_phet.html) looks good to you.  To summarize, that version has:

- _a_ slider behavior is quadratic
- _b_ and _c_ sliders behavior is linear
- _a_ slider snaps to zero when |a| < 0.03
- _b_ and _c_ sliders snaps to zero when |value| < 0.1

**Comment by amanda-phet** [comment]
All looks good. Thanks.
