### ISSUE TITLE
title case

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/graphing-quadratics#24]
These cases are particularly notable as other selections in the same toolbox do use title case.
![title case4](https://user-images.githubusercontent.com/41024075/45239673-49100480-b2a3-11e8-955f-fde4f1090c2e.PNG)
![tatle case5](https://user-images.githubusercontent.com/41024075/45239679-4ca38b80-b2a3-11e8-9054-225f7894e237.PNG)

**Comment by pixelzoom** [comment]
"Axis of Symmetry" is the title of something.  "Hide curves" is an action.  There is no need to be pedantic about using title case everywhere, and there content needs to be examined when deciding what case to use. 

@amanda-phet please advise.

**Comment by pixelzoom** [comment]
https://github.com/phetsims/tasks/issues/953

**Comment by pixelzoom** [comment]
Per 9/13/18 design meeting, "Hide curves" check box is schedule to be replaced by an "eyeball" toggle button.  So this issue is no longer relevant.  Closing.
