### ISSUE TITLE
change requests: 9/13/18 design meeting

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/graphing-quadratics#27]
Change requests from 9/13/18 design meeting. @amanda-phet FYI.

- [x] split first screen into 'Explore" (decimals) and "Standard Form" (integers) screens

_Focus & Directrix_ screen:
- [x] add save/erase buttons
- [x] add point tools
- [x] add Vertex, Focus and Directrix checkboxes with icons
- [ ] ~~When p=0, graph x=h, hide vertex manipulator, keep focus and point manipulators~~
- [x] 0.1 increments for all sliders
- [x] make Vertex manipulator snap to grid
- [x] make Focus manipulator interval 0.1 (same as p slider)
- [x] make Point manipulator continuous
- [x] make focus manipulator disappear when it goes off graph
- [x] force Point manipulator to stay on graph
- [x] choose defaults for p,h,k, revise later
- [x] choose default for point on quadratic, revise later

_Explore_ screen:
- [x] remove 'Hide coordinates' checkbox
- [x] put graph controls in an AccordionBox with title "Quadratic Terms"

_Vertex Form_ screen:
- [x] add Vertex checkbox with icon

All screens:
- [x] change 'Hide coordinates' to 'Coordinates', off by default
- [x] replace 'Hide curves' with eyeball toggle button (SCENERY_PHET/EyeToggleButton)
- [x] make 'NO REAL ROOTS' disappear for y=0

**Comment by pixelzoom** [comment]
9/17/18 @amanda-phet also asked to change the equation form in _Focus and Directrix_ screen to:

![image](https://user-images.githubusercontent.com/3046552/45647993-86834780-ba84-11e8-9f87-dc66fa5345ec.png)

**Comment by amanda-phet** [comment]
@pixelzoom has raised two issues with allowing p=0 since the last design meeting. 

(1) The model currently does not allow for graphs of the form x = __. 
(2) The new form of the quadratic that we are using for the Focus & Directrix screen has p in the denominator of a fraction. 

For these reasons, I think we should hold off on allowing p=0 on this screen, and the slider should simply skip over 0.

**Comment by pixelzoom** [comment]
In #31, we decided not to allow p=0.  So that item in the above checklist will not be completed.

**Comment by pixelzoom** [comment]
All change requests have been addressed. Closing.
