### ISSUE TITLE
color design

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/graphing-quadratics#29]
- [x] Colors for the quadratic terms.
In discussion with Amanda, we concluded that black is a bad color for y=c, because it can't be distinguished from the x axis (see screenshot below). And using magenta for y=ax^2 makes it difficult to distinguish from the interactive quadratic (not a problem if we use magenta for y=c). We need to come up with 3 colors that can be easily distinguished from other curves/lines on the graph.

- [x] Color for roots.
Using the same color (red) for the interactive curve and the roots creates a undesirable association.  Choose a different color for one of these.  (

- [x] Color for interactive equation.
Throughout Graphing Lines, we use black for the interactive curve. Graphing Quadratics alternates between red and black.  Will this be confusing?

![screenshot_754](https://user-images.githubusercontent.com/3046552/45634558-e7e4ef80-ba5f-11e8-83bf-b1ec3215696b.png)

**Comment by amanda-phet** [comment]
I think all of these colors are working as they are with once exception (below). We already discussed the color of the interactive equation being red on the first two screens and black on the 3rd and 4th. The colors for the quadratic terms are working well and have good contrast in different color-blind modes. As for the 'a' coefficient picker being green, it seems consistent with the 4th screen, even if the user doesn't know that right away, so I am fine with leaving that one as green. 

The one change to make at this time is the **color for roots:** @pixelzoom can you change the roots to be `#0071bc` . This color works for color-blindness and has a nice coherence with the purple we are using for the vertex.

**Comment by pixelzoom** [comment]
Color for roots has been changed, closing.
