### ISSUE TITLE
new artwork for point tool that has probe on right

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/graphing-quadratics#33]
Rather than reflecting one image about the y axis, @amanda-phet would like to use separate artwork for each point tool, so that the lighting is correct.    

The current .png file was acquired from graphing-lines, and lives at https://github.com/phetsims/graphing-quadratics/blob/master/images/point_tool_body.png.

The .ai file is in graphing-lines at https://github.com/phetsims/graphing-lines/blob/master/assets/point_tool.ai.

@amanda-phet Please provide me with:
(1) new .ai file
(2) new .png file, with same dimensions as current .png file
(3) credits for the new .png file

**Comment by amanda-phet** [comment]
(1) and (2) sent over slack to @pixelzoom .

**Comment by pixelzoom** [comment]
Changes made in master, @amanda-phet please review.

Here are the licenses, let me know if this needs to change:

```js
“point_tool_left.png”: {
   “text”: [
     “Copyright 2018 University of Colorado Boulder”
   ],
   “projectURL”: “http://phet.colorado.edu“,
   “license”: “contact phethelp@colorado.edu”,
   “notes”: “created by Amanda McGarry, asset file is graphing-lines/assets/point_tool.ai”
 },
 “point_tool_right.png”: {
   “text”: [
     “Copyright 2018 University of Colorado Boulder”
   ],
   “projectURL”: “http://phet.colorado.edu”,
   “license”: “contact phethelp@colorado.edu”,
   “notes”: “created by Amanda McGarry, asset file is graphing-lines/assets/point_tool.ai”
 }
```

If all looks OK, you can close this issue.

**Comment by pixelzoom** [comment]
Revised licensing per @amanda-phet, see above commit.

**Comment by amanda-phet** [comment]
One change: Bryce should be credited with point_tool_left. Once that change is made we can close this.

**Comment by amanda-phet** [comment]
Looks great. Thanks.
