### ISSUE TITLE
control for hiding equations on graph?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/graphing-quadratics#35]
Do we need a control for hiding the equation on the graph? Can we rename "Coordinates" to "Labels" and use one control for hiding both coordinates and equations?

A decision on this may need to wait until equations on the graph are implemented.  But in the meantime, I'm planning for this by having 2 separate view Properties that control the visibility of coordinates and equations.

**Comment by pixelzoom** [comment]
Raising priority to top.  If this is going to involve any changes for the 10/12 interviews deadline, I need to know asap.

**Comment by amanda-phet** [comment]
I am still very torn. We are getting to the point of having so many checkboxes that the list is starting to feel overwhelming (especially on the F&D screen). But I do not think we should have one single checkbox for both coordinates and equations. I'm inclined to leave it as-is and see what happens in interviews.

After discussing with @pixelzoom on slack, we decided to add an "Equations" checkbox to each screen, and add a thin separator line to distinguish the more important checkboxes at the top from the less important checkboxes (Coordinate and Equations). On startup, let's have Equations checked.

**Comment by pixelzoom** [comment]
@amanda-phet and I also discussed what was done in Graphing Lines. It hides the equation for the interactive line when the equation accordion box is collapsed, and does not support hiding the equations for saved lines, y=x and y=-x. Applying that approach to Graphing Quadratics would not be straightforward. When/how should the equations on the terms be hidden? What about the saved line?  And the current implementation has a single `equationsVisibleProperty` that toggles visibility of all equations.  So we decided to try the "Equations" checkbox approach described above.

**Comment by pixelzoom** [comment]
In [1.0.0-dev.19](https://phet-dev.colorado.edu/html/graphing-quadratics/1.0.0-dev.19/phet/graphing-quadratics_en_phet.html), I've added an "Equations" checkbox to all screens, defaulting to checked. The "Equations" and "Coordinates" checkboxes are preceded by a horizontal separator. @amanda-phet please review.

**Comment by kathy-phet** [comment]
Equations and Coordinates together look good to me. My soft preference would be to default Equations check box as not checked, to reduce the visual complexity on start up of all the screens. And let students discover they can display time themselves.

**Comment by ariel-phet** [comment]
I generally think having this equations checkbox works well. I think we might do a bit of pixel polishing on the final screen to make things a bit more compact, but overall thinks look good.

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/graphing-quadratics/issues/36#issuecomment-426486193, @ariel-phet said:
> it looks like in latest dev you have made the accordion box initially collapsed. We could start with a different default, but starting with the vertex at (0,0) seems extremely natural. I think having the quadratic terms accordion box close to begin with is appropriate (especially since this is more of a "physicist" view and not used a ton by math educators). One issue is that the equations checkbox is then hidden, perhaps this checkbox should be moved into the main control panel on this first screen?

@amanda-phet and I recognized the issue with putting the Equation checkbox in the Quadratic Terms accordion box.  We discussed other places to put it.  Another panel below the accordion box seemed to "heavy" for a single checkbox.  Floating below the accordion box would make it look odd/lonely when the accordion box is minimized.  In the equation (top) accordion box would create a significant implementation issue - all of these accordion boxes share the same structure and code, so making one of them different at this point will be costly.  In the end, we rationalized that the Equation checkbox in this screen is needed to reduce the clutter caused by showing the quadratic terms, so it was OK to put the checkbox with the checkboxes for those terms. 

@ariel-phet does that satisfy your comment?

**Comment by pixelzoom** [comment]
I asked:
> @ariel-phet does that address your comment?

In Slack discussion, @ariel-phet said, "It is a pretty minor concern" and "I would say yes, it is addressed"

**Comment by amanda-phet** [comment]
@pixelzoom thanks for clarifying our thought process. I agree it seems strange to have the checkbox nested on the Explore screen, but seems like the best option for that screen given the alternatives. 

@kathy-phet I like the equations at startup because they are a simplified version of what is in the accordion box, so when someone is changing one parameter of the equation they can see the overall equation changing with it. However I would be open to having it off, or changing other startup conditions to reduce the initial load. Interviews will be helpful here as well.

**Comment by amanda-phet** [comment]
decision in 10/4/18 design meeting: leave off by default.

**Comment by pixelzoom** [comment]
Equations is now unchecked by default in all screens. Closing.
