### ISSUE TITLE
how to implement Quadratic toStateObject?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/graphing-quadratics#38]
Related to #14, PhET-iO instrumentation.

Quadratic is the primary model class in Graphing Quadratics.  Its properties include standard form coefficients (a, b, c), vertex form coefficients (p, h, k), and abstractions that are of specific importance to the sim (vertex, focus, directrix, axis of symmetry, color).   Parabolas (a !== 0) have all of the above fields; non-parabolas (a === 0) have a subset of these fields, with the others being `undefined`.  

Quadratic implements `toStateObject` and `fromStateObject`.   The current implementation of `toStateObject` is:

```js
    /**
     * Encodes a Quadratic instance as a PhET-iO state object
     * @returns {*}
     * @public
     */
    toStateObject() {

      // all Quadratics have these fields, which are sufficient to restore a Quadratic
      const object = {
        a: this.a,
        b: this.b,
        c: this.c,
        color: Color.toColor( this.color ).toStateObject()
      };

      //TODO #14 Is it OK that the fields vary depending on whether Quadratic is a parabola? How/where to document?
      // parabolas have these additional fields, which are otherwise undefined
      if ( this.a !== 0 ) {
        _.extend( object, {
          p: this.p,
          h: this.h,
          k: this.k,
          vertex: this.vertex.toStateObject(),
          focus: this.focus.toStateObject(),
          directrix: this.directrix,
          axisOfSymmetry: this.axisOfSymmetry
        } );
      }

      return object;
    }
```

Questions:

(1) Is it OK for the composition of a state object to vary like this? Or would it be preferable to have a consistent composition with some properties whose value is `undefined`? 

(2) Where should this difference in parabola vs non-parabola be documented?  I looked at examples of the `documentation` option for IO types, but I didn't see any examples that looked similar.

**Comment by zepumph** [comment]
>Is it OK for the composition of a state object to vary like this? Or would it be preferable to have a consistent composition with some properties whose value is undefined?

I think it would be preferable to have consistent values with undefined, for consistency. I also think that would be easier to document.

>(2) Where should this difference in parabola vs non-parabola be documented? I looked at examples of the documentation option for IO types, but I didn't see any examples that looked similar.

I would look NodeIO.documentation as an example about how the Type's documentation string can be lengthy and/or html. I would recommend trying to accomplish the documentation in that string.

**Comment by samreid** [comment]
PhET-iO values are based on JSON.stringify, which suppressed keys with undefined values:

```js
JSON.stringify({x:true,y:'false',z:undefined});

// "{"x":true,"y":"false"}"
```

For simplicity on the implementation side, it seems best to include the values even when undefined, but be aware they will not show up on the client frame.  I agree https://github.com/phetsims/scenery/blob/68d2f5af9bf0b62b3fefbc0f87df71cef3574eee/js/nodes/NodeIO.js#L122-L132 documentation is an appropriate example.

**Comment by pixelzoom** [comment]
Below is the new definition of Quadratic `toStateObject`, which includes all properties, regardless of whether they are null.  I verified that `undefined` properties do not appear in the event stream.

```js
    /**
     * Encodes a Quadratic instance as a PhET-iO state object
     * @returns {*}
     * @public
     */
    toStateObject() {
      return {

        // These properties are sufficient to restore a Quadratic, see fromStateObject.
        a: this.a,
        b: this.b,
        c: this.c,
        color: Color.toColor( this.color ).toStateObject(),

        // These properties are desired in the event stream, but will be undefined for non-parabolas (a===0).
        // Because PhET-iO values are based on JSON.stringify, undefined properties will not be present in the
        // event stream.
        p: this.p,
        h: this.h,
        k: this.k,
        vertex: ( this.vertex ? this.vertex.toStateObject() : undefined ),
        focus: ( this.focus ? this.focus.toStateObject() : undefined ),
        directrix: this.directrix,
        axisOfSymmetry: this.axisOfSymmetry
      };
    }
```

The screenshot below shows the QuadraticIO `documentation` in Studio. The HTML for this is defined in `Quadratic.documentationQuadraticIO` so that implementation details are not leaking into QuadraticIO. 

![screenshot_772](https://user-images.githubusercontent.com/3046552/46375604-1ca49980-c651-11e8-8b33-70e2334b3125.png)

@samreid @zepumph feedback?

**Comment by zepumph** [comment]
I believe that we will want the types to be in PhET-iO form, so instead marked as `NumberIO` and `ColorIO`. We don't currently have a way to mark types to make sure they are included in the docs when included in this string (i.e. so that you can see what the serialization of a `ColorIO` looks like).

@samreid maybe it would be nice to include `ColorIO` as a list of "dependencies" to `QuadraticIO` in the type api so that studio could then have a reference to ColorIO's type api from `QuadraticIO`. This way we can guarantee that that TypeIO shows up in the studio type docs.

**Comment by pixelzoom** [comment]
@zepumph I don't understand how the previous comment applied to my `documentation` for QuadraticIO.

**Comment by pixelzoom** [comment]
Ah... Perhaps you mean `{NumberIO}` instead of `{number}`, and `{ColorIO}` instead of `{color}`?

I'm also interested in whether this is the appropriate level of documentation. Too much info, too little info?

**Comment by zepumph** [comment]
That looks good. I think that the level of verbosity is appropriate. We often to refer to these types of objects as "value types", but I think data structure is good too. 

@samreid why are toStateObject and fromStateObject directly on the types for Vector2 and Quadratic. That feels like an antipattern to me, could we use https://github.com/phetsims/phet-io/issues/1373 to make things more consistent?

**Comment by zepumph** [comment]
>@samreid why are toStateObject and fromStateObject directly on the types for Vector2 and Quadratic. That feels like an antipattern to me, could we use phetsims/phet-io#1373 to make things more consistent?

Like `vector2.phetioType.toStateObject()`

**Comment by samreid** [comment]
Should we move the few preceding comments to https://github.com/phetsims/dot/issues/76 ?  Anything else for this issue?

**Comment by zepumph** [comment]
see https://github.com/phetsims/dot/issues/76#issuecomment-426449721

Anything else for this issue?

**Comment by pixelzoom** [comment]
Danke. Closing.
