### ISSUE TITLE
identify and evaluate equation overlap

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/graphing-quadratics#39]
There are situations where an equation may overlap other UI elements (other equations, points, manipulators, etc.)  We should identify these situations, and decide whether to address them (based on UX and cost).

**Comment by pixelzoom** [comment]
- [ ] Standard Form screen with a=6, b=-1, c=6. This could be addressed by changing the vertex.y threshold that is used to change from tangent to horizontal orientation.  In `QuadraticNode`, change `workaroundYMargin` from 3.5 to 4.5.

![46360103-fd454680-c627-11e8-8db7-29595896baa3](https://user-images.githubusercontent.com/3046552/46422376-78befa80-c6f1-11e8-9f33-f4b3435ae786.png)

**Comment by pixelzoom** [comment]
- [ ] _Explore_ screen, with a=-1, b=3.3, c=1.4, including a saved line.  I believe that we've decide to live with this type of overlap.  Foreground-to-background ordering of the lines (and equations) is interactive line, quadratic term, linear term, constant term, saved line.

![screenshot_775](https://user-images.githubusercontent.com/3046552/46424255-dbb29080-c6f5-11e8-98b2-8b0f360c7c15.png)

**Comment by pixelzoom** [comment]
- [ ] On the _Focus & Directrix_ screen, the manipulators can overlap.  But there's really no way to avoid that, and the user can move the manipulators.  Here's a worst case:

![screenshot_777](https://user-images.githubusercontent.com/3046552/46514320-86bc6a80-c81a-11e8-9b0c-ecda3613f9c2.png)

**Comment by pixelzoom** [comment]
The 4 examples above are the overlaps that I was able to identify.  @amanda-phet please indicate which of these need to be addressed.  My feeling is that we should address (1), but can live with (2), (3) and (4).  Also feel free to identify other that I might have missed.

**Comment by amanda-phet** [comment]
I found these as well and was happy with how the sim handled the overlap. I agree that (1) could be improved as it's not just that one instance but happens when b=-1, -2, -3, and -4.

**Comment by pixelzoom** [comment]
I'll spend a little time investigating how to address (1).

**Comment by pixelzoom** [comment]
@amanda-phet please review dev version [1.0.0-dev.35](https://phet-dev.colorado.edu/html/graphing-quadratics/1.0.0-dev.25/phet/graphing-quadratics_en_phet.html).  In this dev version, equations use horizontal orientation if all of the following are true:
(1) the screen displays a vertex point (all screens except _Explore_)
(2) |a| > 0.75 (the parabola is narrow)
(3) the equation is longer than the distance between the tangent point and the vertex (use `?dev` to see the tangent point, a black dot on the parabola)

**Comment by amanda-phet** [comment]
It looks great! That seems to address (1) to me very well. And I'm fine not addressing (2)-(4), if you want to close this issue.
