### ISSUE TITLE
credits

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/graphing-quadratics#4]
Finalize the credits in graphing-quadratics-main.js.

**Comment by pixelzoom** [comment]
This sim is now in RC testing.  @KatieWoe please provide names (as you want them to appear) for the QA credits.

**Comment by KatieWoe** [comment]
Kathryn Woessner, Steele Dalton, Laura Rea, Kelly Wurtz, Jacob Romero.
@phet-steele @rea-laura @kellywurtz @JRomero0613 please double check spelling, etc.

**Comment by pixelzoom** [comment]
@amanda-phet @KatieWoe Below is a screenshot showing the final credits for Graphing Quadratics. Please verify. 

![screenshot_935](https://user-images.githubusercontent.com/3046552/49608508-0ae3b900-f956-11e8-8066-cf4d1ada714a.png)

**Comment by KatieWoe** [comment]
looks good

**Comment by pixelzoom** [comment]
Btw... I verified spelling of QA team names by looking at prior sim credits and Slack.

**Comment by amanda-phet** [comment]
All looks good to me!
