### ISSUE TITLE
Vertex Form screen starting state 

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/graphing-quadratics#40]
I am thinking that it would be best to leave vertex *unchecked* on this screen on startup. I think the flow from the previous screens makes me want the student to interact with the equation first, then interact with the graph, so that they are attending to the equation and how it is different from the first two screens. Then on the Focus & Directrix screen, the interaction with the graph will be natural as that is more the focus than the equation.

**Comment by pixelzoom** [comment]
Done, closing.
