### ISSUE TITLE
pixel polishing

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/graphing-quadratics#44]
This sim is feature complete and is now ready for pixel polishing.  [1.0.0-dev.24](https://phet-dev.colorado.edu/html/graphing-quadratics/1.0.0-dev.24/phet/graphing-quadratics_en_phet.html) is the reference dev version.  (EDIT: Updated to a newer dev version.)

If you have suggestions, please add comments here. Include screenshots, if applicable. 

Note that work on screen icons is still in progress (see #11), so please ignore them for now.  

Since code review needs to start the middle of next week, the priority of this issue is high.

**Comment by amanda-phet** [comment]
I don't have any final requests as we've already gone over my pixel polishes.

**Comment by amanda-phet** [comment]
I just noticed something, and it seems new to me... The font size of the coordinates seems to be changing dramatically- I assume to fit a max width- and it's really startling. Did this change because some coordinates are too wide? Or has this always been the behavior? 
![screen shot 2018-10-05 at 10 33 58 am](https://user-images.githubusercontent.com/7852916/46547779-4399e000-c88a-11e8-9c05-48eff91907ea.png)

![screen shot 2018-10-05 at 10 34 05 am](https://user-images.githubusercontent.com/7852916/46547789-485e9400-c88a-11e8-8a1c-90f42af24d98.png)

**Comment by pixelzoom** [comment]
Which version? This should be fixed in 1.0.0-dev.24.

**Comment by amanda-phet** [comment]
Ah, thanks, I was looking at dev.22. I have too may versions open in tabs :)

**Comment by pixelzoom** [comment]
Do you mind if we delete the previous comments, so that this issue focuses on pixel polishes?

**Comment by ariel-phet** [comment]
The only two things I see (and I am not tied to these polishes at all, just two things I notice, but would be fine to leave as is)...

1. I don't really like the default slider color in this sim. For whatever reason it just looks a bit "dull" to me with the color scheme of the rest of the sim. Perhaps maybe just using a lighter blue would help. As I said, everything works as is, I am just not in love with that color. The highlight hover color is more in line with what I think would look better personally as a default.

2. The final screen feels a bit crowded in terms of the panels. I think the reference equation is a bit larger than it needs to be in my opinion. Again not a big deal, but perhaps something more like the following:

![graphingq](https://user-images.githubusercontent.com/4051174/46552465-ff154100-c897-11e8-9b08-65ff0dcf41f4.PNG)

**Comment by pixelzoom** [comment]
Re @ariel-phet's feedback above:

1. If we change the slider thumb color, please specify both the highlighted and unhighlighted colors. 

2. We could make the accordion box title equation less tall by decreasing the font size for the fraction. If we reduce the overall size of the title equation, we should consider doing so in all screens for consistency.

**Comment by amanda-phet** [comment]
(1) I'm fine with the default color, but if it doesn't seem to draw in students during interviews I will recommend a new color.

(2) A slightly smaller equation would be fine, but right now all screens seem to match the interactive equation sizes and I think that is more important here.

**Comment by pixelzoom** [comment]
@kathy-phet do you have any feedback for this issue?

**Comment by pixelzoom** [comment]
@kathy-phet created 2 issues labeled with "design:polish" (#46, #47), so hopefully that concludes her feedback on this issue.  Closing this issue to stay on schedule.  @kathy-phet if you have other feedback, feel free to create additional issues.
