### ISSUE TITLE
test multi-touch

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/graphing-quadratics#45]
This sim still needs a thorough test of multi-touch, prior to being turned over to QA.

**Comment by amanda-phet** [comment]
I'll leave comments here with anything unusual that I find.. 

The first thing (and I'm not super familiar with multi-touch issues), is that if I am dragging something and click reset-all, I can continue to drag (e.g. the point tool, the vertex). 

Also if I'm dragging the vertex, focus, or orange point, and hide it while dragging, I can continue to drag.

**Comment by pixelzoom** [comment]
> The first thing (and I'm not super familiar with multi-touch issues), is that if I am dragging something and click reset-all, I can continue to drag (e.g. the point tool, the vertex).

Consensus on the developer channel is that "the policy is to ignore this problem unless it causes a crash".   That's probably because the cost to address it is high and the negative impact on the UX is low.  @amanda-phet if you feel strongly that I should address this, please discuss with @ariel-phet.

> Also if I'm dragging the vertex, focus, or orange point, and hide it while dragging, I can continue to drag.

@amanda-phet What does "hide it while dragging" mean?  Does that mean that you change a slider that moves the manipulator off the graph?

**Comment by amanda-phet** [comment]
I'm fine with ignoring the reset-all issue since it did not cause anything to crash. 

What I meant in the second example by "hide it while dragging" is "uncheck the visibility checkbox" while dragging. 

Since it also doesn't cause the sim to crash or cause anything else buggy to happen, I'm fine ignoring it too.

**Comment by pixelzoom** [comment]
The 2 issues reported by @amanda-phet in https://github.com/phetsims/graphing-quadratics/issues/45#issuecomment-427453692 have both been addressed in master.

**Comment by pixelzoom** [comment]
- [ ] When the contents of the graph are hidden, cancel interactions with the manipulators on the graph.

**Comment by pixelzoom** [comment]
I did quite a bit of multi-touch testing today on iPad2.  Dragging the vertex manipulator while attempting to use the h or k sliders (or pickers) causes a bit of flailing (as expected), but nothing breaks. 

@amanda-phet please verify that the checklist items above are addressed in [1.0.0-dev.27](https://phet-dev.colorado.edu/html/graphing-quadratics/1.0.0-dev.27/phet/graphing-quadratics_en_phet.html).   If there's nothing else, you can feel free to close this issue (QA will be doing their own multi-touch testing later).

**Comment by amanda-phet** [comment]
Fixed! Awesome.
