### ISSUE TITLE
Explore Screen: Bug in linear term positioning

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/graphing-quadratics#46]
The coefficient of the linear term is appearing to the right, instead of the left of the "x" term. 
![image](https://user-images.githubusercontent.com/5096804/46621130-e26d4900-cae3-11e8-9271-1acf55d2b6d2.png)

**Comment by pixelzoom** [comment]
I'm guessing that this is in 1.0.0-dev.25.  It was broken there when I added that ability to independently vary the space around operators (=,+) versus the space between coefficients and variables.  It's fixed in master.
