### ISSUE TITLE
make point tool stay on the line you are currently on

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/graphing-quadratics#47]
As I was playing with the point tool, I noticed that when lines overlap it will jump to a different line when it crosses that line (in the Explore screen with all lines displayed). 

A preferred behavior I think would be if it prioritized staying on the line you are currently on (if you are snapped to that line) regardless of which line is "on top" when it crosses other lines. If you pull it off explicitly and put it on the other line, then it would stay on that line when you move through the intersection. 

Thoughts?

**Comment by amanda-phet** [comment]
@pixelzoom what is the priority right now? Is it the closest line to the tool? 

I've noticed it is a little jumpy but wasn't sure another approach would work. @pixelzoom is it possible to try what Kathy has mentioned- the current line has higher priority than neighboring lines?

**Comment by pixelzoom** [comment]
Yes, that's possible. Proceed?

**Comment by amanda-phet** [comment]
Yes, please proceed.

**Comment by pixelzoom** [comment]
@amanda-phet said:
> I've noticed it is a little jumpy but wasn't sure another approach would work. 

What's making this feel jumpy is the tension between snapping to quadratics and snapping to the graph's grid.  If I turn of snapping to the graph's grid, it feels nice and smooth.   Is it really necessary for the point tools to snap to the graph grid in this sim?

**Comment by pixelzoom** [comment]
@amanda-phet said:
> I've noticed it is a little jumpy but wasn't sure another approach would work. 

While I think @kathy-phet's suggestion is good, it's not going to affect the jumpiness much. What's making the point tools feel jumpy is the tension between snapping to quadratics and snapping to the graph's grid.   If I turn off snapping to the graph's grid, it feels nice and smooth.  To demonstrate, I added a `?snapToGrip` query parameter, which defaults to `true`.  

With snap: [1.0.0-dev.28](https://phet-dev.colorado.edu/html/graphing-quadratics/1.0.0-dev.28/phet/graphing-quadratics_en_phet.html)

Without snap: [1.0.0-dev.28?snapToGrid=false](https://phet-dev.colorado.edu/html/graphing-quadratics/1.0.0-dev.28/phet/graphing-quadratics_en_phet.html?snapToGrid=false)

So is it really necessary for the point tools to snap to the graph grid in this sim?

**Comment by amanda-phet** [comment]
This seems like a huge improvement to me and I'm fine with this being the only change. I'll leave it up to @kathy-phet if you still want to try the solution of prioritizing the curve you are on.

**Comment by pixelzoom** [comment]
This is implemented in [1.0.0-dev.32](https://phet-dev.colorado.edu/html/graphing-quadratics/1.0.0-dev.32/phet/graphing-quadratics_en_phet.html). There's also a new query parameter that lets you experiment with the distance for snapping to a curve. The query parameter is `snapDistance`, default 1, values are in graph units. 

@amanda-phet @kathy-phet please review.  High priority, since we're trying to get into dev testing by the end of this week.

**Comment by pixelzoom** [comment]
I discovered that 1.0.0-dev.32 has a problem with how it's handling snapping. Snapping was based on y displacement from the curve, not the actual distance from the curve.

[1.0.0-dev.33](https://phet-dev.colorado.edu/html/graphing-quadratics/1.0.0-dev.33/phet/graphing-quadratics_en_phet.html) handles snapping correctly -- query parameter `snapDistance` is the distance of the point tool from the closest point on the curve.  Please use this version to evaluate the desired value for `snapDistance`.  The default of 1 may be a little too "snappy".

**Comment by amanda-phet** [comment]
I prefer snapDistance=0.5 or 0.6 myself.

**Comment by pixelzoom** [comment]
Chris Malley [12:23 PM]
You didn’t indicate in the issue, but I assume you are OK with how the point tools now prefer to stay snapped to the line that they’re on? (edited)

Amanda McGarry [12:25 PM]
oh yes, I like it quite a lot

**Comment by pixelzoom** [comment]
@amanda-phet Do you want me to proceed with implementing separate `snapOnDistance` and `snapOffDistance` ?

**Comment by kathy-phet** [comment]
I liked how this worked. Easier to study on the curve. So thumbs up from me.

Sent from my iPhone

On Oct 17, 2018, at 9:24 PM, Chris Malley <notifications@github.com<mailto:notifications@github.com>> wrote:


Since we're trying to get into dev testing tomorrow, I went ahead and did this.

1.0.0-dev.35<https://phet-dev.colorado.edu/html/graphing-quadratics/1.0.0-dev.35/phet/graphing-quadratics_en_phet.html> has two query parameters:

snapOnDistance - default 0.5, less than or equal to this distance snaps ON to a curve
snapOffDistance - default 2, greater than this distance snaps OFF of a curve

Values are in graph units, and must be > 0.

@kathy-phet<https://github.com/kathy-phet> @amanda-phet<https://github.com/amanda-phet> Let me know how this feels, and whether you'd like the default values changed.

**Comment by amanda-phet** [comment]
I'm fine with this if @kathy-phet likes it!
