### ISSUE TITLE
test performance

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/graphing-quadratics#48]
Do performance acceptance testing.

**Comment by pixelzoom** [comment]
Performance of sliders is a little pokey on iPad2, especially on the _Explore_ screen.  Start by deferring updates for things that are not visible.

**Comment by pixelzoom** [comment]
Updating of lines, equations and coordinates now occurs only when those things are visible.

**Comment by pixelzoom** [comment]
I made several optimizations, the most significant of which is that lines, equations and coordinates are only updated when they are visible.  Performance feels acceptable to me on iPad2 - not super snappy, but OK.

@amanda-phet please verify that performance is acceptable in [1.0.0-dev.27](https://phet-dev.colorado.edu/html/graphing-quadratics/1.0.0-dev.27/phet/graphing-quadratics_en_phet.html).

**Comment by pixelzoom** [comment]
Performance sign-off need to happen before dev testing and code review, so raising priority to high.

**Comment by amanda-phet** [comment]
I forgot to test on an iPad2 when I was in the office yesterday. I will see if my iPad2 at home is working and will try testing now.

**Comment by amanda-phet** [comment]
performance on iPad2 is definitely laggy, but everything about the iPad is- just changing the URL in the browser was laggy. So, while the sim isn't great, I don't think it is worse than the overall iPad performance.
