### ISSUE TITLE
test for memory leaks (brand=phet-io)

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/graphing-quadratics#50]
For instrumented sims, memory leak testing must be done separately for the phet-io brand, because according to the [How to Instrument document](https://github.com/phetsims/phet-io/blob/master/doc/how-to-instrument-a-phet-simulation-for-phet-io.md):

> Perform a full test for memory leaks. The benchmark dev release can be helpful here. This will help catch faulty tandem disposal. PhET-iO instantiates different objects and wires up listeners that are not present in the PhET-branded simulation. It needs to be tested separately for memory leaks.

**Comment by pixelzoom** [comment]
Slack dev-public:

> Sam Reid [9:56 AM]
Memory leak testing Graphing Quadratics PhET-iO over the last 5 minutes doesn’t suggest any serious memory leaks (it’s just the normal slow rising pattern).  I also don’t see any tandems being added after the sim starts up, so that’s a good indicator that there are no phet-io related memory leaks.
>
> Chris Malley [9:59 AM]
Thanks, that matches what I see.  I wasn’t aware of this “normal slow rising pattern”.  When I tested Equality Explorer (5 screens), it started at 71MB and then oscillated around 82MB.

**Comment by pixelzoom** [comment]
https://github.com/phetsims/graphing-quadratics/issues/14 (review of PhET-iO instrumentation) is a prerequisite to doing memory leak testing.

**Comment by samreid** [comment]
The main part of the work in #14 is complete, removing "block" status.  @chrisklus are running a 10-minute memory test for this.  Initial heap size (after about a minute) is 73.6MB.  We'll report back in 10 minutes with the second snapshot.  Keep in mind that https://github.com/phetsims/unit-rates/issues/207 may be related to this memory issue.

**Comment by pixelzoom** [comment]
Why are you doing a memory leak test before all PhET-iO related issues have been addressed?

**Comment by pixelzoom** [comment]
Why are you doing a memory leak test before all PhET-iO related issues have been addressed?  And did someone ask you to self-assign?

**Comment by samreid** [comment]
Everything seems OK for now, we can run another test after checking off all other PhET-iO issues.  Putting on hold until all other phet-io issues have been addressed.

**Comment by pixelzoom** [comment]
Test results for:

* [1.0.0-dev.46](https://phet-dev.colorado.edu/html/graphing-quadratics/1.0.0-dev.46/phet-io/) with `?fuzz`
* Chrome 70.0.3538.102
* macOS 10.11.6 on MacBook Pro

| Minutes | Heap Size (MB) |
| ---: | ---: |
| 0 |   |
| 5 |   |
| 10 |   |
| 15 |   |
| 20 |  |
| 25 |  |
| 30 |  |
| 45 |  |

**Comment by pixelzoom** [comment]
For comparison, the latest `brand=phet` memory tests are in https://github.com/phetsims/graphing-quadratics/issues/106.

Test results for `brand=phet-io`:

* [1.0.0-dev.46](https://phet-dev.colorado.edu/html/graphing-quadratics/1.0.0-dev.46/phet-io/graphing-quadratics_all_phet-io.html?phetioStandalone) with `?standalone&fuzz`
* Chrome 70.0.3538.102
* macOS 10.11.6 on MacBook Pro

| Minutes | Heap Size (MB) |
| ---: | ---: |
| 0 |  43.9 |
| 5 |  52.2 |
| 10 | 53.6 |
| 15 | 54.6  |
| 20 | 54.7 |
| 25 |  55.4 |
| 30 |  55.5 |
| 45 |  55.6 |

This looks fine.  PhET-iO appears to add < 4MB of overhead to `brand=phet`, and that seems reasonable. Closing.
