### ISSUE TITLE
[iOS] clipArea bug for navigation bar icons

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/graphing-quadratics#51]
I noticed this first on iPad2 and just confirmed it on a newer iPad, so it's likely an iOS bug. The parabolas seem to extend beyond the navbar into the sim region. 

![image](https://user-images.githubusercontent.com/7852916/46816762-e34be800-cd3a-11e8-842c-9a391dd4f3ad.png)

**Comment by pixelzoom** [comment]
I'll bet it's a problem on the home screen too. The screen icons use scenery's `clipArea` feature to clip the parabolas to the icon bounds, see for example [GQScreenIconFactory](https://github.com/phetsims/graphing-quadratics/blob/master/js/common/view/GQScreenIconFactory.js) line 71.  

@jonathanolson are you aware of any problems with `clipArea` on iOS9?

**Comment by pixelzoom** [comment]
@amanda-phet What is the iOS version of the "newer iPad"?

**Comment by pixelzoom** [comment]
It's also a problem on desktop Safari, I see it in Safari 11.1.2.

**Comment by amanda-phet** [comment]
seen on iOS 9 and iOS 12.

**Comment by pixelzoom** [comment]
If I change the color of the parabolas to 'red', you can see the problem more clearly for all 4 navbar icons:

![screenshot_786](https://user-images.githubusercontent.com/3046552/46822773-97546f80-cd49-11e8-8d0b-0dcd0a2dab15.png)

Surprisingly, the home screen icons (which are the same ScreenIcons) look fine:

![screenshot_787](https://user-images.githubusercontent.com/3046552/46822792-a4715e80-cd49-11e8-8383-e7228c58c01e.png)

**Comment by pixelzoom** [comment]
@jonathanolson Any progress on this, or should I apply the above workaround?

**Comment by jonathanolson** [comment]
It's looking like a browser issue that's quite particular to ID names and order of operations. It's not pretty, but I'd keep the workaround for now.

**Comment by pixelzoom** [comment]
Moving this to a general scenery issue: https://github.com/phetsims/scenery/issues/881.

I'll apply the workaround (separate icon instances for navigation bar) in Graphing Quadratics.

**Comment by pixelzoom** [comment]
Workaround is applied, so this is not blocking 1.0 publication.

Marking this as deferred until phetsims/scenery#881 is fixed.  Then the workaround should be removed.

**Comment by pixelzoom** [comment]
Moved this issue to https://github.com/phetsims/joist/issues/532, updated TODO items in this sim to point to that issue. 

Closing.
