### ISSUE TITLE
Slider tandem names

### ISSUE THREAD

**Issue by chrisklus** [phetsims/graphing-quadratics#53]
@samreid and I are wondering if the tandem for `aSlider` of type QuadraticCoefficientSlider -> CoefficientSlider should have a different name since CoefficientSlider contains a slider, but is not of type slider. The current naming creates a confusing phetioID because of `aSlider.slider`:

`graphingQuadratics.exploreScreen.view.equationAccordionBox.content.aSlider.slider`

@pixelzoom have you considered renaming QuadraticCoefficientSlider to QuadraticCoefficientControl, CoefficientSlider to CoefficientControl, and then aSlider to aControl?

Found while working on #14.

**Comment by pixelzoom** [comment]
Ah, I misspoke.  We do need to instrument the label, with the intention of controlling its visibility.  

Rethinking.

**Comment by pixelzoom** [comment]
Renamed to CoefficientControl and QuadraticCoefficientControl in the above commit. The tandems are now (for example):

```
graphingQuadratics.exploreScreen.view.equationAccordionBox.content.aSlider
graphingQuadratics.exploreScreen.view.equationAccordionBox.content.aSlider.slider
graphingQuadratics.exploreScreen.view.equationAccordionBox.content.aSlider.label
```

I'm much less happy with these names, but I can live with it.  Please review.

**Comment by pixelzoom** [comment]
I should also note that I'm much less happy with the `phetioDocumentation`, e.g.

Before: `phetioDocumentation: 'slider for coefficient a'`
After: `phetioDocumentation: 'control for coefficient a'`

.. and similarly in 5 other similar places (for coefficients b, c, p, h, k).

It seems like it will now be more difficult for the PhET-iO client to identify sliders.

**Comment by samreid** [comment]
> The tandems are now (for example):
> `graphingQuadratics.exploreScreen.view.equationAccordionBox.content.aSlider.slider`

I pulled and tested, and the tandems are now like so:

`graphingQuadratics.exploreScreen.view.equationAccordionBox.content.aControl.slider`. That seems great.

> I'm much less happy with these names, but I can live with it.

Regardless of phet-io, it seems odd that a `CoefficientSlider` would contain a `VSlider`--that is, that a `*Slider` would contain a `*Slider`.

> I should also note that I'm much less happy with the phetioDocumentation: After: `phetioDocumentation: 'control for coefficient a'`

Would inheritance address this problem?  Then `CoefficientSlider` could extend `VSlider` and it would technically be a `*Slider` instead of a Node that contains a Slider?

**Comment by pixelzoom** [comment]
@samreid said:
> Would inheritance address this problem?

You seem to want to force the tandem names to match the implementation specifics (inheritance vs composition).  I thought we had moved on from that approach. I don't see any advantage in doing that, only disadvantages.   From the client's point of view, it's a slider that's decorated with a label.  That doesn't mean that `CoefficientSlider` must be a subclass of `VSlider`.

**Comment by pixelzoom** [comment]
I investigated changing to `class CoefficientSlider extends VSlider` and then adding the label as a child. That opened a new can of worms.  See screenshot below.  Because `VSlider` is a rotated `Slider`, the label ends up rotated and in the wrong position.  Using this knowledge to rotate the label would be wrong and could break in the future.  `VSlider` should be fixed so that it can be decorated, see https://github.com/phetsims/graphing-quadratics/issues/53.

![screenshot_789](https://user-images.githubusercontent.com/3046552/46923376-0513cc00-cfd4-11e8-9414-ba178898172c.png)

**Comment by samreid** [comment]
> I thought we had moved on from that approach. I don't see any advantage in doing that, only disadvantages. 

This general topic is under discussion in https://github.com/phetsims/phet-io/issues/1392

> I investigated changing to class CoefficientSlider extends VSlider and then adding the label as a child. That opened a new can of worms.

Thanks, I agree inheritance is inappropriate for this case.

> You seem to want to force the tandem names to match the implementation specifics (inheritance vs composition). 

I'd like to discuss this independently of PhET-iO for the moment.  If I have a `*Slider` that contains a `*Slider` by composition, it sounds like there are two sliders.  As a synthetic example, imagine I had a `MysteriousCat` type that contains a `Cat` by composition.  It sounds like there are two cats.  More likely what is intended is something like `MysteriousCatContainer` that contains a `Cat` by composition.

**Comment by pixelzoom** [comment]
@samreid said:
> Thanks, I agree inheritance is inappropriate for this case.

Inheritance is the approach I'm pursuing.  I intended to fix phetsims/sun#406, then change to `class CoefficientSlider extends VSlider`, decorated with a label.   The resulting tandems will be (for example):

```
graphingQuadratics.exploreScreen.view.equationAccordionBox.aSlider
graphingQuadratics.exploreScreen.view.equationAccordionBox.aSlider.label
```

 I see no advantage to introducing a "container" for PhET-iO.

**Comment by samreid** [comment]
> I see no advantage to introducing a "container" for PhET-iO.

The argument has nothing to do with PhET-iO, as described in both https://github.com/phetsims/graphing-quadratics/issues/53#issuecomment-429677171 and https://github.com/phetsims/graphing-quadratics/issues/53#issuecomment-429553193

That being said, inheritance sounds like a reasonable long term solution, I hope it goes smoothly!

**Comment by pixelzoom** [comment]
`CoefficientSlider` now extends `VSlider`, then adds a label.   I adjusted local variable names, tandem names, and `phetioDocumentation`.  @chrisklus @samreid please review.

**Comment by samreid** [comment]
Looks great, nice work, thanks, closing.
