### ISSUE TITLE
Should saveEraseButtons be saveErasePanel, etc?

### ISSUE THREAD

**Issue by chrisklus** [phetsims/graphing-quadratics#54]
@samreid and I are wondering if the saveEraseButtons tandem should be renamed to saveErasePanel because most buttons are instrumented individually. Since these are instrumented together, we think that it might be more accurate to call them a panel, or a node, or something like that. Also, we are wondering if SaveEraseButtons.js should be renamed as well.

@pixelzoom what do you think?

Found while working on #14.

**Comment by pixelzoom** [comment]
How about class `SaveEraseButtonGroup` and tandem `saveEraseButtonGroup`?

**Comment by pixelzoom** [comment]
I'm considering this...  `SaveEraseButtonGroup` sounds nice because we're programmers and familiar with the concept of ButtonGroup in Java.   Is `SaveEraseButtonGroup` vs `SaveEraseButtons` really going to make a difference to the PhET-iO client?

**Comment by pixelzoom** [comment]
And the `phetioDocumentation` seems pretty clear:

```js
      const saveEraseButtons = new SaveEraseButtons(
        model.saveQuadratic.bind( model ), 
        model.eraseQuadratic.bind( model ),
        model.savedQuadraticProperty, {
          tandem: options.tandem.createTandem( 'saveEraseButtons' ),
          phetioDocumentation: 'buttons to save and erase a quadratic on the graph'
        } );
```

**Comment by samreid** [comment]
Regardless of phet-io, the `*Buttons` nomenclature is odd.  That means `saveEraseButtons` is an instance of type `*Buttons` which sounds really odd.  What's the argument against `ButtonGroup`? Our clients are programmers.  Calling it an instance of a `*Group` seems clearer than calling it an instance of a `*Buttons`.  Yes, having proper documentation helps, but we should choose the better name as well.

As a hypothetical example for a different context and just focusing on the var name:
```js
var sliders = new HBox({children: [slider1,slider2]});
var sliderGroup = new HBox({children: [slider1,slider2]});
var sliderPanel = new HBox({children: [slider1,slider2]});
var sliderContainer = new HBox({children: [slider1,slider2]});
var controlNode = new HBox({children: [slider1,slider2]});
```
I can't think of any good arguments for the former name, any of the latter 4 seem much clearer.  On the other hand:
```js
var sliders = [slider1,slider2];  // Seems appropriate because it is an array of sliders.
```

Do we use the "plural component" strategy (like `saveEraseButtons` instanceof `SaveEraseButtons`) in much of our codebase?

**Comment by pixelzoom** [comment]
I don't understand what the cognitive leap is in understanding "Button" versus "Buttons".   And I don't see any advantage to including info about the type of container (e.g. "Panel").

Precedent for this naming, which seems crystal clear to me:

GRAVITY_AND_ORBITS/SpeedRadioButtons
UNIT_RATES/ShoppingCategoryRadioButtons
REACTIONS_PRODUCTS_AND_LEFTOVERS/VisibilityRadioButtons

But if you think `SaveEraseButtonGroup` is an improvement, I'll roll with it.

**Comment by pixelzoom** [comment]
"What type is this instance?"  It's an instance of SaveEraseButtons.  Again, I think this is a non-problem.  But if you want to spearhead this issue, go for it.

**Comment by pixelzoom** [comment]
@samreid Are you satisfied with `SaveEraseButtonGroup` here?  If so, please close this issue.   If you wish to purse the consistency issue mentioned in https://github.com/phetsims/graphing-quadratics/issues/54#issuecomment-429676318, please create a new issue.

**Comment by pixelzoom** [comment]
Whoops, I haven't changed the name of `SaveEraseButtons` yet.  Before I do.... Is `SaveEraseButtonGroup` acceptable?

**Comment by samreid** [comment]
That looks great, thanks!  Closing.
