### ISSUE TITLE
Type for locationProperty

### ISSUE THREAD

**Issue by samreid** [phetsims/graphing-quadratics#57]
From #14, `PointTool.locationProperty` is declared like so
```js
// @public {Vector2}
this.locationProperty = new Property( options.location, {
  valueType: Vector2,
  tandem: options.tandem.createTandem( 'locationProperty' ),
  phetioType: PropertyIO( NullableIO( Vector2IO ) ),
  phetioDocumentation: 'location of this point tool'
} );
```

The review noted inconsistencies:
(1) the public type is `Vector2`, not `Vector2|null`
(2) the valueType is `Vector2`, no support for null indicated
(3) the phetioType is `PropertyIO( NullableIO( Vector2IO ) ),` which specifies null as a possibility.

Should this value support null or not?

**Comment by pixelzoom** [comment]
A point tool always has a location, so PointTool `locationProperty` should have `phetioType: PropertyIO( VectorIO )`.   This was probably a copy-paste error from VertexNode or RootsNode, where those things are null for non-parabolas. 

Fixed in above commit. Closing.
