### ISSUE TITLE
Issue with NumberDisplay tandem

### ISSUE THREAD

**Issue by samreid** [phetsims/graphing-quadratics#59]
Discovered in #14 and #58, `NumberDisplay` is marked as `tandem: Tandem.required`, however `ExploreInteractiveEquationNode.EquationNode` creates a `NumberDisplay` without passing in a tandem.

I am uncertain whether this should be solved by marking `NumberDisplay` as `Tandem.optional` or by passing a tandem to it.

**Comment by pixelzoom** [comment]
For this sim, there is no desire or need to instrument the NumberDisplay instances that subcomponents of the equations.  So I don't think it's appropriate to pass them a tandem. I could pass them `Tandem.optional` as a workaround.   But I think this is a case where `tandem: Tandem.required` is not appropriate in a common-code component.

**Comment by samreid** [comment]
> For this sim, there is no desire or need to instrument the NumberDisplay instances that are subcomponents of the equations. So I don't think it's appropriate to pass them a tandem. I could pass them Tandem.optional as a workaround. 

Since not all `NumberDisplay` instances should be instrumented, `NumberDisplay` should be instrumented as `Tandem.optional`.  I will make this change so I can proceed checking for downstream issues in #58.  Commit coming shortly.

**Comment by samreid** [comment]
In the preceding commit, I changed NumberDisplay to be Tandem.optional.  @pixelzoom please review and close if all is well.

**Comment by pixelzoom** [comment]
I don't think the comment belongs in NumberDisplay, it's without context here.

```js
      // NumberDisplay instances that are subcomponents of the equations are not instrumented
      tandem: Tandem.optional,
```

**Comment by samreid** [comment]
Thanks, reassigning to you to address as you see fit.  I'm not sure if you want that comment elsewhere or not.

**Comment by pixelzoom** [comment]
Done. Back to you for approval.

**Comment by samreid** [comment]
To me, `// optional because not all {{*}} instances require instrumentation` is redundant because that is the definition of `Tandem.optional`, and I would not like to see that comment duplicated at every `Tandem.optional` site.  Where added documentation *may* be beneficial is in sites like ExploreInteractiveEquationNode.EquationNode where the NumberDisplay is created without a Tandem.  

```js
// Create the display for the a coefficient.  Note that NumberDisplay is not PhET-iO 
// instrumented when it appears as a subcomponent of an equation.
const aNode = new NumberDisplay( aProperty, aProperty.range, _.extend( {}, numberDisplayOptions, {
  numberFill: GQColors.EXPLORE_A,
  decimalPlaces: GQConstants.EXPLORE_DECIMALS_A
} ) );
```

But like I said, I'm not even sure that comment is necessary.  Up to you @pixelzoom

**Comment by pixelzoom** [comment]
I don't think a comment is needed at the NumberDisplay instantiation sites  in Graphing Quadratics. It's obvious that it's not instrumented because no tandem is passed.  

I've remove the comment from NumberDisplay.   My first inclination was to put something like:

```js
// Common-code tandems are typically Tandem.required but this one is different because 
// Graphing Quadratics (and likely other sims in the future) needs to use it without instrumentation.  
// See https://github.com/phetsims/graphing-quadratics/issues/59.
tandem: Tandem.optional
```

But that is too verbose.  And it has the same problem as the shorter comment that I added.  That is, because of this policy of defaulting common-code components to `Tandem.required` (which I still don't agree with), every time that we encounter a situation like this, we'll need to change it to `Tandem.optional` and either (a) explain why, or (b) say nothing and nope that someone doesn't change it back to `Tandem.required`.   Imo, `Tandem.optional` should be the defacto default.   Or `Tandem.required` should behave like `Tandem.optional` and error out only if a query parameter enables is required-ness.

**Comment by samreid** [comment]
Note: a commit was made above under: https://github.com/phetsims/scenery-phet/commit/e0d662a8790e29bb5c8df3b78f3c832648570b37

I think leaving certain types such as Buttons as `Tandem.required` may be most helpful to us, since we will (always?) want data streams for them, and this can help us catch accidentally uninstrumented components.

> Imo, Tandem.optional should be the defacto default. Or Tandem.required should behave like Tandem.optional and error out only if a query parameter enables its required-ness.

That is the current behavior.  Tandem.required only fails when using ?phetioValidateTandems.

The change in https://github.com/phetsims/scenery-phet/commit/e0d662a8790e29bb5c8df3b78f3c832648570b37 looks great, can we close this issue?  Do you want to open another issue to further discuss optional/required?

**Comment by pixelzoom** [comment]
I'm OK with just closing this.
