### ISSUE TITLE
Should VerticalSlider be made into a common component?

### ISSUE THREAD

**Issue by andrealin** [phetsims/graphing-quadratics#6]
There is an HSlider.js in SUN, but there is no VSlider.js. Graphing quadratics uses vertical sliders, so I copied a VerticalSlider from LEAST_SQUARES_REGRESSION/view/MyLineControlPanel into GRAPHING_QUADRATICS/common/view/VerticalSlider.

Should there be a common code VSlider created in SUN?

Assigning to @ariel-phet and @pixelzoom for input.

**Comment by ariel-phet** [comment]
@andrealin I believe HSlider.js supports vertical orientations. For instance, I know that Resistance in a Wire was converted to use the HSlider common component. Please take a look at how things are done in that repo. You most definitely want to use the common component (and I believe it already exists)

**Comment by andrealin** [comment]
Ah ok, I see that in Resistance in a Wire. Will do something similar in Graphing Quadratics. Closing.
