### ISSUE TITLE
There should be a data stream message when the camera button is pressed.

### ISSUE THREAD

**Issue by samreid** [phetsims/graphing-quadratics#60]
Discovered in #14 and #58, there is no data stream message when the camera button is pressed, but there should be.  This behavior arose because we wanted to instrument the save + clear buttons as a group rather than individually, since it doesn't make sense to show one without the other.  However, we forgot that if the buttons are not instrumented at all, then they do not emit to the data stream.

A potentially workable "middle ground" which I do not recall discussing with @pixelzoom or design teams before is to include the option `phetioReadOnly: true` for the `saveButton` and `eraseButton`.  This will allow the buttons to emit to the data stream, but the buttons will not be independently customizable.

For instance, I added two lines to SaveEraseButtons.js
```js
      const saveButton = new RectangularPushButton( {
        content: new FontAwesomeNode( 'camera', { maxWidth: BUTTON_ICON_WIDTH } ),
        baseColor: PhetColorScheme.BUTTON_YELLOW,
        listener: saveFunction,
        tandem: options.tandem.createTandem('saveButton'), // ADDED LINE
        phetioReadOnly: true                               // ADDED LINE
      } );
```

With those new added lines, the button now emits to the data stream like so:
![image](https://user-images.githubusercontent.com/679486/46927320-fa682f80-cff1-11e8-9ed1-87662de1df20.png)

And the `saveButton` appears in studio, but note the controls (like the selected checkbox and emit button) are grayed out:

![image](https://user-images.githubusercontent.com/679486/46927345-14097700-cff2-11e8-922b-ae89a525b1a2.png)

@pixelzoom what do you think?

**Comment by pixelzoom** [comment]
Middle-ground solution seems fine.  Committed above. Please review.

**Comment by samreid** [comment]
Looks great, thanks, closing.
