### ISSUE TITLE
Update tandem names for input listeners

### ISSUE THREAD

**Issue by zepumph** [phetsims/graphing-quadratics#65]
@pixelzoom there is a recent (undocumented until https://github.com/phetsims/phet-io/commit/5d71fdfc43629eb8e12ede29a2df8c22c0090d12) convention that all input listeners' tandems should be named `inputListener`. This is to promote flexible, robust tandem names that are more future proof.

Thus 
```js
      this.addInputListener( new PointToolDragHandler( pointTool, modelViewTransform, graph,
        options.tandem.createTandem( 'dragHandler' ) ) );
```
should be renamed to 
```js
      this.addInputListener( new PointToolDragHandler( pointTool, modelViewTransform, graph,
        options.tandem.createTandem( 'inputListener' ) ) );
```

In the sim I see 4 usages of `createTandem.*handler`. 

From #14

Sorry about the newness of this all.

**Comment by pixelzoom** [comment]
Why would you want to name them all `inputListener`?  There are many types of input listener, all with very different APIs.  That would be like using tandem `'node'` for anything that's a subtype of Node.

**Comment by pixelzoom** [comment]
In faradays-law, the reference implementation:

```js
117 const dragListener = new DragListener( {
118
119   tandem: tandem.createTandem( 'dragListener' ),
...
141 draggableNode.addInputListener( dragListener );
```

**Comment by pixelzoom** [comment]
Some of the inconsistencies that you've identified in https://github.com/phetsims/phet-io/issues/1392#issue-369350164 are in common code.   Do those need to be addressed prior to Graphing Quadratics 1.0 ?

**Comment by zepumph** [comment]
I think ideally, seeing as it has to do with long term tandem name support. I added the block-publication label to that issue.

**Comment by pixelzoom** [comment]
And what do you name the tandem for the 2nd listener when you need to add more than one input listener to a Node?

**Comment by pixelzoom** [comment]
And what do you name the tandem for the 2nd listener when you need to add more than one input listener to a Node?  Example is BEERS_LAW/CuvetteNode.  There are 2 listener, one to handle highlighting and one to handle dragging.  If I needed to instrument both of these listeners, how can they both have tandem name 'inputListener'?

**Comment by pixelzoom** [comment]
This is blocked until https://github.com/phetsims/phet-io/issues/1392 is resolved.

**Comment by zepumph** [comment]
phetsims/phet-io#1392 has progressed enough such that this issue can be closed as a `wont-fix`. @pixelzoom anything else?
