### ISSUE TITLE
Equation on the directrix line shows when it should not.

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/graphing-quadratics#68]
Basically, the green equation for the directrix shows up even when the Equation check box is not checked.

I thought this was just on the smart phone, but it is general. It is hidden when the screen starts up, but then appears as soon as you change the line in any way. If you stop changing the line, and check and uncheck the equation check box it will go away. But as soon as you change the line it reappears. 

This seems easily reproducible, but let me know if you don't see it.

**Comment by pixelzoom** [comment]
Steps to reproduce:
1. go to Focus & Directrix screen
2. note that the directrix is shown without equation
3. move p slider
4. notes that equation appears on directrix

**Comment by pixelzoom** [comment]
Similar problem occurs with axis of symmetry (so at least I was consistent :)

Steps to reproduce:
1. go to Standard Form screen
2. check the "Axis of Symmetry" checkbox
3. note that axis of symmetry is shown without equation
4. press the a spinner
5. note that equation appears on axis of symmetry

**Comment by pixelzoom** [comment]
Fixed in [1.0.0-dev.34](https://phet-dev.colorado.edu/html/graphing-quadratics/1.0.0-dev.34/phet/graphing-quadratics_en_phet.html).  @kathy-phet or @amanda-phet please verify, close this issue if it looks OK.

**Comment by kathy-phet** [comment]
Tested. Looks fixed to me.
