### ISSUE TITLE
point tool snaps when it shouldn't

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/graphing-quadratics#70]
Reported by @phet-steele via Slack.

In [1.0.0-dev.34](https://bayes.colorado.edu/dev/html/graphing-quadratics/1.0.0-dev.34/phet/graphing-quadratics_en_phet.html):

(1) point tool will snap to hidden curves
(2) point tool will snap to curves beyond the edges of the graph

**Comment by pixelzoom** [comment]
@phet-steele I have reproduced (2) above, but I cannot reproduce (1).  Can you please provide steps to reproduce?

**Comment by pixelzoom** [comment]
(2) is fixed in the above commit.  The point tool will now snap only when it's on the graph.

**Comment by pixelzoom** [comment]
Slack:

Steele Dalton [9:26 PM]
Hey I don't have a procedure l, it just happens. Hide your curve, remember where it is, then move the tool to it

Chris Malley [9:27 PM]
Oh I see… using the eyeball toggle button? I was using the checkboxes to hide the terms on the Explore screen.

**Comment by pixelzoom** [comment]
Issue (1) fixed in the above commit.

**Comment by pixelzoom** [comment]
@phet-steele please verify in [1.0.0-dev.36](https://phet-dev.colorado.edu/html/graphing-quadratics/1.0.0-dev.36/phet/graphing-quadratics_en_phet.html).

**Comment by phet-steele** [comment]
Looks good on mobile.
