### ISSUE TITLE
add phetioDocumentation for all tandems

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/graphing-quadratics#71]
Based on meeting decision in https://github.com/phetsims/phet-io/issues/1346.

**Comment by pixelzoom** [comment]
@zepumph Should I add `phetioDocumentation` to the top-level Screen, ScreenView and Model types?  We have been passing `tandem` to these things via a constructor param.  Passing `phetioDocumentation` will require:

(1) converting from `tandem` constructor param to `options`, and passing both `tandem` and `phetioDocumentation` via `options`.

(2) Making the model types extend PhetioObject, probably with `phetioState: false` to prevent "circular JSON" error.

All of this so that so I can write (e.g.) "the model for the Explore screen" for tandem "graphingQuadratics.exploreScreen.model".   This seems entirely redundant and not worth the effort.  But the decision in phetsims/phet-io#1346 was "phetioDocumentation for all tandems, until further notice".  So if that's what you want, let me know.

**Comment by zepumph** [comment]
I think you should hold off on those higher level tandems for now. I'll mark that in the other issue.

**Comment by pixelzoom** [comment]
Two other situations:

(1) To provide `phetioDocumentation` for GQViewProperties and its subtypes, I would need to change it to `extends PhetioObject` and set `phetioState: false`.    

(2) We do not want to instrument the various `*GraphNode` classes, but we do want to instrument their subcomponents.  So `tandem` is passed as a constructor parameter.    So providing `phetioDocumentation` for these is also problematic.

**Comment by pixelzoom** [comment]
@zepumph and I discussed the above exceptions to documentation.  We will skip top-level types.  And for the other cases (GQViewProperties and *GraphNode classes), the is no "phetio instance" created (no entry in Studio), so these things do not require phetioDocumentation.

**Comment by pixelzoom** [comment]
Grr.. I went to the trouble of adding `phetioDocumentation` to all of my DragListener subclasses, only to find out that there is apparent no "phetio instance" for DragListener.

**Comment by pixelzoom** [comment]
Putting this on hold until general decision are made about `phetioDocumentation`, Studio, etc.

**Comment by pixelzoom** [comment]
Pretty sure that phetioDocumentation is now complete.  I'm going to close this issue, and it will be tested by QA when we get to PhET-iO dev/rc testing.

**Comment by pixelzoom** [comment]
In 11/29/18 phet-io meeting, there was a consensus that `GQViewProperties` and it's subclasses should have phetioDocumentation, so that doc like `'Properties that are specific to the view'` appears in Studio. This means that `GQViewProperties` should extend `PhetioObject`, and also set `phetioState: false`.

**Comment by pixelzoom** [comment]
GQViewProperties was instrumented in the above commit, tested in Studio.
