### ISSUE TITLE
increase use of phetioReadOnly

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/graphing-quadratics#72]
There seem to be more things (especially in the view) that we don't want the PhET-iO client to modify. Take another look to identify these.

**Comment by pixelzoom** [comment]
Question for @samreid or @zepumph:  For the view of the point tools (`PointToolNode`), the only thing  that we'd like clients to be able to do is change the visibility.  Location should be changed with the model (PointTool `locationProperty`).  So I'm considering adding a `visibleProperty` to the PointTool model (to be observed by PointToolNode), and then marking PointToolNode as `phetioReadOnly: true`.   Does that sound like a good or bad idea?  And is it acceptable to add a Property that is specific to PhET-iO?

**Comment by samreid** [comment]
We discussed the "all or none" approach and discussed "cherry-picking" individual attributes in https://github.com/phetsims/phet-io/issues/1375#issuecomment-427144500.  The conclusion was that we would not try to "cherry pick" individual attributes like visibility, but that if a Node is instrumented, you would get all of its features such as visibility/opacity/pickability.

We decided that we want to change how we perform the PhET-iO design for a simulation.  We will no longer say things like "this node should be able to be made invisible, but not unpickable".  We will instead say "this node should be instrumented or uninstrumented".   Instrumented Node instances will all have the same feature set for uniformity.

> Location should be changed via the model (PointTool locationProperty).

That sounds good, there is currently no Node feature that sets translation (or transform in general).

> And is it acceptable to add a Property that is specific to PhET-iO?

In general, it is fine to create Properties or Emitters or other code that is necessary to provide the desired PhET-iO feature set, but it doesn't sound warranted for the case described in the preceding comment.

Should we reopen the design issue to make sure everyone is aware of this change in the PhET-iO simulation design process?

**Comment by pixelzoom** [comment]
Adding `visibleProperty` to PointTool would also make controlling their visibility (via PhET-iO) identical controlling the visibility of all of the things on the graph - vertex, roots, focus, directrix, axis of symmetry.  That is, via a BooleanProperty.

**Comment by pixelzoom** [comment]
Adding `visibleProperty` to PointTool would also make controlling their visibility (via PhET-iO) identical to controlling the visibility of all of the things on the graph - vertex, roots, focus, directrix, axis of symmetry.  That is, via a BooleanProperty.  The view for all of those things is slated to be marked `phetioReadOnly: true`.

**Comment by samreid** [comment]
One question that should be addressed before we can continue on this issue:

* Should the PointToolNode/VertexManipulators/etc be able to be set visible: true and pickable: false?  If so, this may suggest that the Nodes should be phetioReadonly:false.  In other PhET-iO simulations, it has been a typical use case to be able to make things visible but unpickable.

**Comment by pixelzoom** [comment]
Blocked by #80.

**Comment by samreid** [comment]
The proposal from #80 is that in this case the 5 or so node types that have a DerivedProperty for visibilityProperty would be phetioReadOnly.  If we proceed with that proposal, what remains to do for this issue before publication?

**Comment by pixelzoom** [comment]
>  If we proceed with that proposal, what remains to do for this issue before publication?

Inspect everything that has a tandem to see whether there's anything else (buttons? checkboxes?containers?) that should be phetioReadOnly.

**Comment by zepumph** [comment]
`Tandem` is a Type that is basically a fancy `String` class used for creating unique identifiers throughout the project. `PhetioObject` uses `Tandem` to register an instance with phet-io for interoperability. When an instance has been "added" to phet-io, we call that instance instrumented. 

You can simply pass tandems (with `createTandem` ) wherever you want across the project and nothing will be necessarily instrumented. This is a similar discussion as the one regarding `phetioDocumentation` and why it wasn't showing up in Studio for some instances that were "passed tandems"

**Comment by pixelzoom** [comment]
Still waiting for replies to proposal over in #80... But assuming that we decide to make `{DerivedProperty} visibleProperty` read-only,  I'm going to make these things `phetioReadOnly:true`:

subclasses of Manipulator (FocusManiplulatorNode, VertexManipulatorNode)
subclasses of PointNode (VertexNode, RootsNode)

And after review of instrumented instances, instances of these things should also be `phetioReadOnly: true`:

all uses of CoordinatesNode
NoRealRootsNode

**Comment by pixelzoom** [comment]
Testing of the above commit is pending resolution of https://github.com/phetsims/graphing-quadratics/issues/89.

**Comment by pixelzoom** [comment]
#89 was resolved, and the changes herein were tested.  They will be more thoroughly reviewed by QA during dev/rc testing.   So closing this issue.
