### ISSUE TITLE
Flickering Curve

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/graphing-quadratics#76]
**Test device:**
Dell Laptop
**Operating System:**
Windows 10
**Browser:**
Chrome
**Problem description:**
For https://github.com/phetsims/QA/issues/211
On the fourth screen, when trying to make the vertex and the focus overlap, the curve flickers very quickly between a curve opening up, and a curve opening down.  Since this configuration (p=0) would result in dividing by zero it is good that is not possible for the value to be zero.  However, the flickering between p=.1 and p=-.1 can be distracting and jarring.
**Steps to reproduce:**
1. Easiest done on a device with touch, but can be done with a mouse as well.
2. Go to the Focus & Directrix screen
3. Ensure that the vertex and the focus boxes are selected.
4. Drag the focus manipulator to try and directly cover the vertex manipulator

**Screenshots:** Note: Can be done faster than shown here.
![zero](https://user-images.githubusercontent.com/41024075/47231230-9777ef00-d389-11e8-9ceb-4084d085d0fe.gif)

Troubleshooting information (do not edit):

<details>

Name: ‪Graphing Quadratics‬
URL: https://phet-dev.colorado.edu/html/graphing-quadratics/1.0.0-dev.38/phet/graphing-quadratics_en_phet.html
Version: 1.0.0-dev.38 2018-10-18 21:15:53 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.67 Safari/537.36
Language: en-US
Window: 1536x732
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"master"},"axon":{"sha":"644353d6","branch":"master"},"brand":{"sha":"1fd6682e","branch":"master"},"chipper":{"sha":"fc5919bb","branch":"master"},"dot":{"sha":"dcccfddd","branch":"master"},"graphing-lines":{"sha":"08b2b43e","branch":"master"},"graphing-quadratics":{"sha":"9b807638","branch":"master"},"joist":{"sha":"b12072c7","branch":"master"},"kite":{"sha":"380cef53","branch":"master"},"phet-core":{"sha":"269c4c8a","branch":"master"},"phet-io":{"sha":"ce77e241","branch":"master"},"phet-io-wrapper-classroom-activity":{"sha":"534dc595","branch":"master"},"phet-io-wrapper-hookes-law-energy":{"sha":"3372700d","branch":"master"},"phet-io-wrapper-lab-book":{"sha":"09507f4d","branch":"master"},"phet-io-wrappers":{"sha":"0a4a3153","branch":"master"},"phetcommon":{"sha":"a2a1aaba","branch":"master"},"query-string-machine":{"sha":"9ae63aab","branch":"master"},"scenery":{"sha":"d7e6c53e","branch":"master"},"scenery-phet":{"sha":"344597e6","branch":"master"},"sherpa":{"sha":"0989d371","branch":"master"},"sun":{"sha":"289fce23","branch":"master"},"tambo":{"sha":"fe63321c","branch":"master"},"tandem":{"sha":"2c4b970a","branch":"master"}}

</details>

**Comment by pixelzoom** [comment]
There's no way to avoid this flickering -- that's what happens when you transition from p=0.1 to p=-0.1.   Assigning to @amanda-phet in case there's any change that she wants to make here.

**Comment by pixelzoom** [comment]
There's no way to avoid this flickering -- that's what happens when you transition from p=0.1 to p=-0.1, it's an abrupt reflection across the x axis.   Assigning to @amanda-phet in case there's any change that she wants to make here.

**Comment by amanda-phet** [comment]
No change- this is the behavior because p cannot equal 0 since it is in the denominator of a fraction. In interviews, I asked students what would happen if p=0 and they all said something similar to "it would be a straight vertical line" so the current design is effective for addressing learning goals.
