### ISSUE TITLE
Difficulty attaching to lines

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/graphing-quadratics#78]
**Test device:**
Dell Laptop
**Operating System:**
Windows 10
**Browser:**
Firefox
**Problem description:**
For https://github.com/phetsims/QA/issues/211
It can be difficult to get the device that examines the lines to jump to the desired line if the lines are too close together, and there is a another line on the other side.  If they are close enough together, the device jumps from one to the other, skipping the line in the middle.  It may be possible to put the device on the desired line if approaching from outside the graph.
**Steps to reproduce:**
1. Go to the Explore screen
2. Open the Quadratic Terms toolbox and select "y=ax2"
3. Set a at -6 and c at +6
4. Use one of the line examining tools and approach the orange curve from the top, left, or right of the graph.
5. Once it has attached to the orange curve, attempt to attach to the blue curve.  It will jump between either side of the orange curve instead.
6. To get around this problem, approach from the bottom of the graph as shown.

**Screenshots:**
![jump](https://user-images.githubusercontent.com/41024075/47235927-bd0bf500-d397-11e8-9c81-157794877ad7.gif)

Troubleshooting information (do not edit):

<details>

Name: ‪Graphing Quadratics‬
URL: https://phet-dev.colorado.edu/html/graphing-quadratics/1.0.0-dev.38/phet/graphing-quadratics_en_phet.html
Version: 1.0.0-dev.38 2018-10-18 21:15:53 UTC
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:62.0) Gecko/20100101 Firefox/62.0
Language: en-US
Window: 1536x760
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"master"},"axon":{"sha":"644353d6","branch":"master"},"brand":{"sha":"1fd6682e","branch":"master"},"chipper":{"sha":"fc5919bb","branch":"master"},"dot":{"sha":"dcccfddd","branch":"master"},"graphing-lines":{"sha":"08b2b43e","branch":"master"},"graphing-quadratics":{"sha":"9b807638","branch":"master"},"joist":{"sha":"b12072c7","branch":"master"},"kite":{"sha":"380cef53","branch":"master"},"phet-core":{"sha":"269c4c8a","branch":"master"},"phet-io":{"sha":"ce77e241","branch":"master"},"phet-io-wrapper-classroom-activity":{"sha":"534dc595","branch":"master"},"phet-io-wrapper-hookes-law-energy":{"sha":"3372700d","branch":"master"},"phet-io-wrapper-lab-book":{"sha":"09507f4d","branch":"master"},"phet-io-wrappers":{"sha":"0a4a3153","branch":"master"},"phetcommon":{"sha":"a2a1aaba","branch":"master"},"query-string-machine":{"sha":"9ae63aab","branch":"master"},"scenery":{"sha":"d7e6c53e","branch":"master"},"scenery-phet":{"sha":"344597e6","branch":"master"},"sherpa":{"sha":"0989d371","branch":"master"},"sun":{"sha":"289fce23","branch":"master"},"tambo":{"sha":"fe63321c","branch":"master"},"tandem":{"sha":"2c4b970a","branch":"master"}}

</details>

**Comment by pixelzoom** [comment]
Point tools were implemented as specified and signed off in https://github.com/phetsims/graphing-quadratics/issues/47.  There are 2 query parameters that control snapping: `snapOnDistance` and `snapOffDistance`.   @amanda-phet and @kathy-phet seemed to be satisfied with the default values, but perhaps they need to be calibrated.   Note that you can't have both large snap distances and the ability to easily move between curves that are close together.  And the current values favor making it easy to snap to (and stay on) a curve.  

@amanda-phet please review and let me know if you'd like to make any changes.

**Comment by amanda-phet** [comment]
This is behaving as intended, and we want to prioritize staying on a curve when using the point tool.
