### ISSUE TITLE
[Edge] performance is slow but acceptable

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/graphing-quadratics#82]
In https://github.com/phetsims/QA/issues/211#issuecomment-431400947, @KatieWoe reported, and @phet-steele added 👍:
> General performance note: Edge seems to be a bit slow and prone to lag.

Overall? Specific features?

**Comment by phet-steele** [comment]
@pixelzoom I had an answer until I discovered #83. If #83 is causing my performance issues, I'm going to wait to comment on Edge performance.

**Comment by KatieWoe** [comment]
@pixelzoom Mostly noticeable when dragging objects for me, though things like the number pickers may be a bit slow as well, its a bit harder to tell.

**Comment by pixelzoom** [comment]
@KatieWoe Please expand the "Quadratic Terms" accordion box on the _Explore_ screen, and check all of the checkboxes.  Is there any significant difference in performance with Equations checked vs unchecked? (Sorry I can't test this myself, I don't have access to an Edge test machine.)

**Comment by KatieWoe** [comment]
@pixelzoom The process you describe does cause a very noticeable drop in performance.

**Comment by KatieWoe** [comment]
@pixelzoom performance is better.  There is still lag under those conditions, but it is better.
I also went to look at other browsers and saw the master sim won't load on internet explorer.  After a few minutes the progress bar hasn't started to fill at all.  No errors appear in the console and nothing appears in the network tab.  The master sim is loading on chrome, firefox, and edge on the same device.

**Comment by pixelzoom** [comment]
Sorry @KatieWoe, I forgot that we can no longer run in requirejs mode on IE11 (see #87).

**Comment by pixelzoom** [comment]
#83 is apparently nothing to worry about, see https://github.com/phetsims/graphing-quadratics/issues/83#issuecomment-434116186.

@phet-steele you can now provide specifics for this issue.  Which features, configurations, etc. are slow/laggy?

**Comment by pixelzoom** [comment]
@KatieWoe feel free to chime in too.

**Comment by phet-steele** [comment]
Testing in 1.0.0-dev.38:

Using sliders is slow. Holding down pickers might also be worse than normal, but not by that much. Sliders are slow even if no checkboxes are enabled, and only slightly worse when all are enabled. Sliders are also slow if the curve is hidden (so maybe it's more about calculating the curve, rather than drawing it?).

Explore screen:

| | FPS |
| --- | --- |
| Idle | 60 |
| Using sliders | 38 |
| Using sliders (curve hidden) | 38 |

Everything else is fine for me, which mostly just includes the point tools. And to be honest, this performance is really not that bad.

**Comment by KatieWoe** [comment]
@pixelzoom I'm seeing a bit more lagging than @phet-steele seems to.  Mostly on the Explore screen when everything is checked, and dragging the point tools seems much slower to me in those conditions.

**Comment by phet-steele** [comment]
> Are sliders slower in the _Explore_ screen, where 4 curves are being redrawn?

Visually, these screens have very similar performance. The Explore screen is maybe on average 5 fps slower than the Focus and Directrix screen with all boxes checked.

**Comment by pixelzoom** [comment]
@phet-steele said:
> Everything else is fine for me, which mostly just includes the point tools. And to be honest, this performance is really not that bad.

@KatieWoe @phet-steele would it be fair to change the title of this issue to "performance is slow but acceptable"?

**Comment by KatieWoe** [comment]
Should be @pixelzoom

**Comment by pixelzoom** [comment]
I'm going to investigate installing a Win10 + Edge VM so that I can experiment.

**Comment by pixelzoom** [comment]
An idea that might speed things up a bit on Edge... An equation on a line consists of 2 nodes - RichText to display the equation, and Rectangle to put a translucent background behind it. See `GQEquationFactory`.  Instead of creating new Nodes each time the equation changes (and doing `removeChild` and `addChild`), just modify `RichText.text` and `Rectangle.setRect`.

**Comment by pixelzoom** [comment]
I suspect that Edge may be more sensitive to changes to the structure of the scenegraph.  So in the above commit, Nodes for equations are now mutated instead of being removed/added each time the interactive quadratic changes. 

@KatieWoe @phet-steele:
Is the responsiveness on Edge improved in [1.0.0-dev.44](https://phet-dev.colorado.edu/html/graphing-quadratics/1.0.0-dev.44/phet/graphing-quadratics_en_phet.html)?  
You can compare to [1.0.0-dev.43](https://phet-dev.colorado.edu/html/graphing-quadratics/1.0.0-dev.43/phet/graphing-quadratics_en_phet.html)

**Comment by KatieWoe** [comment]
@pixelzoom it looks much better.  The sliders drag behind the mouse just a tad, but the frame rate is much, much better.

**Comment by pixelzoom** [comment]
Disregard the 5 commits immediately above. They should be associated with #102.

**Comment by pixelzoom** [comment]
It sounds like performance is now acceptable.  But I'd like to see with my own eyes, so I'll leave this open and have a look at @KatieWoe's Edge test machine on Thursday.

@amanda-phet Since the lead designer needs to sign off on performance (see #48), it would be good to get your input on this issue.  When you're in the office, please test drive 1.0.0-dev.44 (or higher) on @KatieWoe's Edge test machine.

**Comment by pixelzoom** [comment]
@amanda-phet and I tested on @KatieWoe's Edge machine.  With the performance improvements made in 1.0.0-dev.44, the sim's responsiveness is more than acceptable.
