### ISSUE TITLE
[Chrome] ?profiler is showing this sim runs at 120 fps

### ISSUE THREAD

**Issue by phet-steele** [phetsims/graphing-quadratics#83]
When I run this link in Win 10 Chrome, `?profiler` shows the sim running at 120 fps: https://phet-dev.colorado.edu/html/graphing-quadratics/1.0.0-dev.38/phet/graphing-quadratics_all_phet.html?profiler

Last time we saw a number greater than 60 it was because there were multiple simulation steps per animation frame (instead of just one). That was in https://github.com/phetsims/joist/issues/447 although that issue was different than this in most regards. This issue has nothing to do with LoL; I simply see 120 fps from startup while not running in LoL.

@pixelzoom @jonathanolson can you make sure nothing is odd here? And that someone other than me can reproduce?

For phetsims/QA/issues/211.

**Comment by KatieWoe** [comment]
I just ran the link with Win 10 chrome and was only getting 60 fps or so.

**Comment by pixelzoom** [comment]
Running 1.0.0-dev.38 with `?profiler` on Chrome 70.0.3538.67 + macOS 10.11.6, I see 40-60fps, depending what I'm doing.

**Comment by jonathanolson** [comment]
It looks like there are flags that disable VSYNC that would allow higher framerates. Is anything like that set on your browser?

**Comment by phet-steele** [comment]
My version is 70.0.3538.67 as well.

> It looks like there are flags that disable VSYNC that would allow higher framerates. Is anything like that set on your browser?

@jonathanolson I don't see anything in chrome://flags that mentions vsync and is disabled. I also never mess around with flags so nothing would have changed recently.

<details>
<summary>Troubleshooting Information</summary>

URL: https://phet-dev.colorado.edu/html/graphing-quadratics/1.0.0-dev.38/phet/graphing-quadratics_all_phet.html?profiler
Version: 1.0.0-dev.38 2018-10-18 21:15:53 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.67 Safari/537.36
Language: en-US
Window: 1920x938
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4095
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"master"},"axon":{"sha":"644353d6","branch":"master"},"brand":{"sha":"1fd6682e","branch":"master"},"chipper":{"sha":"fc5919bb","branch":"master"},"dot":{"sha":"dcccfddd","branch":"master"},"graphing-lines":{"sha":"08b2b43e","branch":"master"},"graphing-quadratics":{"sha":"9b807638","branch":"master"},"joist":{"sha":"b12072c7","branch":"master"},"kite":{"sha":"380cef53","branch":"master"},"phet-core":{"sha":"269c4c8a","branch":"master"},"phet-io":{"sha":"ce77e241","branch":"master"},"phet-io-wrapper-classroom-activity":{"sha":"534dc595","branch":"master"},"phet-io-wrapper-hookes-law-energy":{"sha":"3372700d","branch":"master"},"phet-io-wrapper-lab-book":{"sha":"09507f4d","branch":"master"},"phet-io-wrappers":{"sha":"0a4a3153","branch":"master"},"phetcommon":{"sha":"a2a1aaba","branch":"master"},"query-string-machine":{"sha":"9ae63aab","branch":"master"},"scenery":{"sha":"d7e6c53e","branch":"master"},"scenery-phet":{"sha":"344597e6","branch":"master"},"sherpa":{"sha":"0989d371","branch":"master"},"sun":{"sha":"289fce23","branch":"master"},"tambo":{"sha":"fe63321c","branch":"master"},"tandem":{"sha":"2c4b970a","branch":"master"}}
</details>

**Comment by jonathanolson** [comment]
@phet-steele is there a time where I could work with you on this issue? I'm curious about adding in certain types of logging to see exactly what the situation is.

**Comment by jonathanolson** [comment]
Looked into it more. @phet-steele's 120fps is legitimate (not a code bug on our side), and looks like it relates to how the browser interacts with VSYNC. https://github.com/w3c/html/issues/375 has more information about how it works, and proposals for the future (supporting higher framerates).

@ariel-phet I'm not that concerned here. The only case where higher framerates would be worse is generally if it's way above the monitor refresh rate (thus essentially wasting power/battery). The browser/spec devs are aware of this, and it looks like we'd generally need to opt-in in the future.

Anything else to do here?

**Comment by pixelzoom** [comment]
@ariel-phet's call here.  If this is something we need to address, let's move it to a new issue in an appropriate common-code repo.

**Comment by ariel-phet** [comment]
No, I think nothing else to do here. Glad we investigated, and glad that it is not particularly concerning. Closing.
