### ISSUE TITLE
prevent overlap of vertex coordinates and 'NO REAL ROOTS'

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/graphing-quadratics#88]
Moving this issue here from https://github.com/phetsims/graphing-quadratics/issues/75#issuecomment-431427448, related to dev test phetsims/QA#211.

The vertex coordinates and 'NO REAL ROOTS' label can overlap, like in this scenario:

![overlaps](https://user-images.githubusercontent.com/41024075/47232439-e96e4400-d38c-11e8-8306-64199b499fee.PNG)

For this case, we decided to try putting the vertex coordinates to the left of the vertex point.

**Comment by pixelzoom** [comment]
In [1.0.0-dev.39](https://phet-dev.colorado.edu/html/graphing-quadratics/1.0.0-dev.39/phet/graphing-quadratics_en_phet.html), the vertex coordinates move to the left of the vertex point when it would overlap with the 'NO REAL ROOTS' label.  For example on the _Standard Form_ screen with a=-1, b=0, c=-1:

![screenshot_803](https://user-images.githubusercontent.com/3046552/47402351-63daf300-d702-11e8-8e30-c11148d0ceb6.png)

Unfortunately, this is the case whether or not the 'Roots' checkbox is checked. For example, the above example looks like this with 'Roots' unchecked:

![screenshot_804](https://user-images.githubusercontent.com/3046552/47402394-8f5ddd80-d702-11e8-81d4-a1a32fb3517d.png)

To evaluate, you might want to try these steps, with and without the 'Roots' checkbox checked:

1. Go to _Standard Form_ screen
2. Check Vertex checkbox
3. Set equation to a=-1, b=0, c=0
4. Set c=-1
5. Set c=-2

When 'Roots' is unchecked, it seems a little odd that the vertex coordinates move around.  So this is a tradeoff.  @amanda-phet please let me know which you'd prefer - a bit of movement for the vertex coordinates, or the overlap that was originally reported.

**Comment by pixelzoom** [comment]
Another idea would be to keep the layout of the vertex coordinates the same, but vary the location of 'NO REAL ROOTS'. When the parabola opens up, put 'NO REAL ROOTS' below the x axis; when the parabola opens down, put 'NO REAL ROOTS' above the x axis. This would keep the vertex coordinates from jumping around, and 'NO REAL ROOTS' would only change when the sign of "a" changes.

**Comment by pixelzoom** [comment]
The more I see it, the more I don't like the vertex coordinates jumping around. So I decided to try what I suggested in https://github.com/phetsims/graphing-quadratics/issues/88#issuecomment-432770003.   See [1.0.0-dev.40](https://phet-dev.colorado.edu/html/graphing-quadratics/1.0.0-dev.40/phet/graphing-quadratics_en_phet.html).  In this version, 'NO REAL ROOTS' is positioned above or below the x axis, but only if there's an overlap, and only when the vertex coordinates are actually visible.  For example, see screenshots below with 'Coordinates' on and off.

@amanda-phet please review.  @KatieWoe feel free to take a peek too.

![screenshot_807](https://user-images.githubusercontent.com/3046552/47458285-6b4bdc00-d796-11e8-86d0-e0baf6f2f4b3.png)

![screenshot_808](https://user-images.githubusercontent.com/3046552/47458298-6edf6300-d796-11e8-9f3f-8a4ab04a80f4.png)

**Comment by pixelzoom** [comment]
The approach in 1.0.0-dev.40 also makes it possible to compute the potential area of overlap, which is important since the 'NO REAL ROOTS' string is translatable.

**Comment by amanda-phet** [comment]
I'm happy with this. Thanks for pursuing it!

**Comment by amanda-phet** [comment]
Just wanted to confirm with the "team" at design today. Kathy agrees it is a good way to go.

**Comment by phet-steele** [comment]
There is a tiny bit of overlap here. It's not terrible, but hey it's my job to point it out:

![image](https://user-images.githubusercontent.com/5863899/49324158-9e943000-f4e5-11e8-85cd-364f5c0641d4.png)

Seen on Win 10 Chrome. For phetsims/QA/issues/227.

<details>
<summary>Troubleshooting Information</summary>

URL: https://phet-dev.colorado.edu/html/graphing-quadratics/1.0.0-rc.1/phet/graphing-quadratics_en_phet.html
Version: 1.0.0-rc.1 2018-11-30 19:42:25 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36
Language: en-US
Window: 1920x938
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4095
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"HEAD"},"axon":{"sha":"61dd41f7","branch":"HEAD"},"brand":{"sha":"1fd6682e","branch":"HEAD"},"chipper":{"sha":"0097c5ac","branch":"HEAD"},"dot":{"sha":"266d3b7a","branch":"HEAD"},"graphing-lines":{"sha":"bff7f97c","branch":"HEAD"},"graphing-quadratics":{"sha":"e121e149","branch":"HEAD"},"joist":{"sha":"88658dbb","branch":"HEAD"},"kite":{"sha":"f3e96e5b","branch":"HEAD"},"phet-core":{"sha":"2e54db08","branch":"HEAD"},"phet-io":{"sha":"1acc6dc2","branch":"HEAD"},"phet-io-wrapper-classroom-activity":{"sha":"5dea7f54","branch":"HEAD"},"phet-io-wrapper-hookes-law-energy":{"sha":"b42eaef7","branch":"HEAD"},"phet-io-wrapper-lab-book":{"sha":"b884e9c1","branch":"HEAD"},"phet-io-wrappers":{"sha":"9d0c5205","branch":"HEAD"},"phetcommon":{"sha":"869b2561","branch":"HEAD"},"query-string-machine":{"sha":"c4d4a81e","branch":"HEAD"},"scenery":{"sha":"4618d52a","branch":"HEAD"},"scenery-phet":{"sha":"e5fa975a","branch":"HEAD"},"sherpa":{"sha":"2134a0d1","branch":"HEAD"},"sun":{"sha":"6887a29a","branch":"HEAD"},"tambo":{"sha":"9b56e6cd","branch":"HEAD"},"tandem":{"sha":"3f6559f4","branch":"HEAD"}}
</details>

**Comment by pixelzoom** [comment]
There's also a bit of overlap when "NO REAL ROOTS" has been moved above/below the x axis.  E.g.:

![screenshot_906](https://user-images.githubusercontent.com/3046552/49395136-eb008b00-f6f2-11e8-998a-66c8e5daa8b1.png)

**Comment by pixelzoom** [comment]
The problem here is that 'NO REAL ROOTS' was simply centered on y=1 or y=-1 when it would overlap the vertex.  The above commit changes that, and positions 'NO REAL ROOTS' related to the vertex (2 units above or below vertex.y, depending on which way the parabola opens).

Below are some screenshots that demonstrate.

@phet-steele please review in master. 

![screenshot_907](https://user-images.githubusercontent.com/3046552/49396263-f43f2700-f6f5-11e8-822c-00f1b1a23693.png)
![screenshot_908](https://user-images.githubusercontent.com/3046552/49396267-f6a18100-f6f5-11e8-9b7d-94472f1e2095.png)
![screenshot_909](https://user-images.githubusercontent.com/3046552/49396273-f99c7180-f6f5-11e8-8e2d-a14eb6d071a9.png)
![screenshot_910](https://user-images.githubusercontent.com/3046552/49396282-fbfecb80-f6f5-11e8-8294-15e13aff35e4.png)

**Comment by pixelzoom** [comment]
@amanda-phet FYI, there has been a change to how overlap of vertex and 'NO REAL ROOTS' is handled. See above comment.

**Comment by KatieWoe** [comment]
It can be quite a bit more severe than shown.  On the Standard form screen, enter 5 for a, 4 for b, and 1 for c as an example (with vertex, coordinates, and roots selected)

**Comment by KatieWoe** [comment]
![overlap](https://user-images.githubusercontent.com/41024075/49398463-bb09b580-f6fb-11e8-964b-696032d53e0f.PNG)

**Comment by pixelzoom** [comment]
@KatieWoe please review @phet-steele's report in https://github.com/phetsims/graphing-quadratics/issues/88#issuecomment-443398269 and my subsequent fix.   Is this issue a duplicate, and is the issue addressed by the fix in master?

**Comment by pixelzoom** [comment]
Oops, @KatieWoe I didn't realize this is the same issue.  I'll delete my comment above.

**Comment by pixelzoom** [comment]
@KatieWoe This should be handled by the above fix.  Please verify in master.

**Comment by pixelzoom** [comment]
Patched in 1.0 release branch.

**Comment by pixelzoom** [comment]
Thanks @JRomero0613.  That particular case is an overlap that we have decided not to address. See https://github.com/phetsims/graphing-quadratics/issues/39#issuecomment-426700426.

**Comment by KatieWoe** [comment]
New note.  The fix doesn't seem to work with short strings.  This was taken on master.
![master](https://user-images.githubusercontent.com/41024075/49409064-409d5d80-f71c-11e8-8200-c59bb387f3d4.PNG)

**Comment by pixelzoom** [comment]
Good catch. The "overlap area" is computed based on the width of the "NO REAL ROOTS" string.  Perhaps I should base it on the `maxWidth` of that Node.

**Comment by pixelzoom** [comment]
Okey dokey, overlap bounds are now based on maxWidth, so should work for all translated string lengths.  @KatieWoe please verify in master.

**Comment by KatieWoe** [comment]
Looks good on master @pixelzoom

**Comment by pixelzoom** [comment]
Labeled with "fixed-pending-testing" for regression testing in 1.0.0-rc.2.

**Comment by phet-steele** [comment]
Good in 1.0.0-rc.2.

**Comment by KatieWoe** [comment]
One extra note @pixelzoom.  I would still say this is fixed and leave closed, but I do see the "no real roots" box move when it doesn't need to.
![needed](https://user-images.githubusercontent.com/41024075/49527163-89fdc200-f86e-11e8-8959-49d2caa85dd6.gif)

**Comment by pixelzoom** [comment]
The "other way" proved to be full of minefields, so I abandoned. Closing.
