### ISSUE TITLE
Cannot register two different instances to the same id

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/graphing-quadratics#89]
When running Studio with `?sim=graphing-quadratics&ea&phetioValidateTandems=true`, I'm seeing the Error shown in the screenshot below.

At first I thought that this was related to https://github.com/phetsims/graphing-quadratics/issues/80, where `visibleProperty` in a subclass of Manipulator was shadowing `visibleProperty` in NodeIO.  But I don't have any of those `visibleProperty` instances instrumented -- search for `createTandem( 'visibleProperty' )` to confirm.  The tandem for `vertexManipulator` is created on line 47 of VertexFormGraphNode. 

@samreid @zepumph what am I doing wrong? 

![screenshot_809](https://user-images.githubusercontent.com/3046552/47475621-83911a80-d7d9-11e8-9cab-f72dfdb8a882.png)

**Comment by samreid** [comment]
This is the code at the end of the constructor in Manipulator.js:

```js
    var sphereNode = new ShadedSphereNode( 2 * radius, options );
    this.addChild( sphereNode );

    this.mutate( options );
```

The same tandem is getting passed to both the `ShadedSphereNode` and the `Manipulator` and hence they are both trying to register their `graphingQuadratics.vertexFormScreen.view.vertexManipulator.visibleProperty`

**Comment by pixelzoom** [comment]
Great, thanks for identifying.

**Comment by pixelzoom** [comment]
Fixed, verified in Studio, closing.
