### ISSUE TITLE
Point on Parabola coordinates can be off the left edge of the screen

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/graphing-quadratics#91]
When the Point on Parabola is at the far left edge of the graph, its coordinates fall off the left edge of the screen.  See example screenshot below with `?dev`.   Moving the coordinates to the other side of the point would address this, but would overlap the dashed line connecting the point to the focus, and would probably overlap other things in other configurations.  

This is probably not a big deal. After having used the point, they should be able to know that the coordinates in this example are (-10, 2).

@amanda-phet are you OK with leaving this as is, or would you like it addressed in some way? 

![screenshot_811](https://user-images.githubusercontent.com/3046552/47509465-2aaa9c00-d844-11e8-9dfe-16389fa72f69.png)

**Comment by pixelzoom** [comment]
Note that it's not just at x=-10, the coordinates start to fall off the left edge for x <= -7.5.

**Comment by amanda-phet** [comment]
I am OK with this. Thanks for finding it.

**Comment by KatieWoe** [comment]
Seen in https://github.com/phetsims/QA/issues/233.  Adding this to note that is more obvious on iPad screens as they are always sized so that this occurs.

**Comment by pixelzoom** [comment]
Thank for noting @KatieWoe. We decided that this is the lesser of 2 evils.  If we start trying to flip the coordinates to the right of the point, we run into all kinds of scenarios where there is overlap with vertex and focus.
