### ISSUE TITLE
reevaluate whether to include PhET-iO in 1.0 release

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/graphing-quadratics#92]
From 10/25/18 notes in the "PhET Developer Meeting 2018" Google doc, there are currently 13 common-code issues that are related to PhET-iO and are blocking Graphing Quadratics 1.0:

> - phet-io status:block-publication GitHub issues (17)
>     * CM: I’m not clear on which of these is required for Graphing Quadratic PhET-iO 1.0 publication.
>     * We removed Faraday’s law specific issues from this list (2 of them).
>     * Everything on this list applies to GQ except specific Component issues that don’t apply (like for ComboBox and SimpleDragHandle). I count 13 total for GQ.
 
The graphing-quadratics repo has an addition 4 issues labeled "dev:phet-io" and 1 labeled "design:phet-io".  

So there are 19 PhET-iO issues that are blocking Graphing Quadratics 1.0.  And there will undoubtedly be more when we start official testing.  Based on the rate at which PhET-iO issues are being addressed, it could be some time before the PhET-iO version is ready.

@amanda-phet @ariel-phet Should we reevaluate whether to publish brand=phet-io as part of the 1.0 release?

**Comment by ariel-phet** [comment]
@pixelzoom publishing 1.0 is the priority, I would look at publishing the phet-io version as gravy. At this point, if you are feeling that it will be a somewhat herculean effort, there is no need to stress about it. No funders or clients expect this sim to have iO to the best of my knowledge. I think the fact that you have done instrumentation during development has been a step in the right direction for our process, but it has clearly revealed plenty of outstanding issues.

Keep the focus on the brand=phet version, and let's not worry about iO for the 1.0 release.

**Comment by pixelzoom** [comment]
@samreid @zepumph @chrisklus FYI.  Let's keep the heat on for addressing PhET-iO issues.  But if it's not ready when brand=phet is ready, I'm going to defer all work and QA related to brand=phet-io, to be revisited at a later date.

**Comment by samreid** [comment]
> But if it's not ready when brand=phet is ready,

What is the anticipated timeline for when brand=phet is ready?

**Comment by pixelzoom** [comment]
> What is the anticipated timeline for when brand=phet is ready?

Code review later this week, ready to begin RC testing sometime next week.  So we have ~1 week to address PhET-iO issues.
