### ISSUE TITLE
Some options extend but apply the same value

### ISSUE THREAD

**Issue by samreid** [phetsims/graphing-quadratics#94]
Discovered during https://github.com/phetsims/graphing-quadratics/issues/14

I noted this code:

```js
  class ExploreEquationAccordionBox extends GQEquationAccordionBox {

    /**
     * @param {ExploreModel} model
     * @param {Object} [options]
     */
    constructor( model, options ) {
                                              
      options = _.extend( {
        tandem: Tandem.required
      }, options );
```

And also this code:
```js
  class GQEquationAccordionBox extends AccordionBox {

    /**
     * @param {ExploreModel} model
     * @param {Node} content
     * @param {Object} [options]
     * @abstract
     */
    constructor( model, content, options ) {

      options = _.extend( {
        tandem: Tandem.required,
```

Since the tandem is required in the base class, it is redundant to specify its default as required in the subclass.  When is it appropriate to have subclasses re-specify the same default value for an option?  Only in cases where the base class value is likely to change.

I haven't checked if this pattern appears elsewhere, I thought I would bring up this case as one occurrence to be addressed, and @pixelzoom can resolve any other cases that are using this same pattern.

**Comment by pixelzoom** [comment]
`tandem: Tandem.required` (as I understand it) serves to indicate that instances of a class must be instrumented.  I see no harm whatsoever in duplicating this, it's a non-issue.  Efforts would be better focused on identifying common code that should _not_ be specifying `tandem: Tandem.required` (which I believe is most common code).

Closing.

**Comment by samreid** [comment]
I'm trying to understand the scope of your argument with a thought experiment.  For instance, let's say I had a base class with a default of `stroke: 'blue'`.  Then I put a default of `stroke:'blue'` in the subclass.  Then the argument would be: "stroke: 'blue' serves to indicate that instances of the class have a blue stroke.  I see no harm whatsoever in duplicating this, it's a non-issue.".  Is this a reasonable comparison?  If not, why would the argument apply for tandem but not for stroke?  Shouldn't the subclass be aware of its parents' defaults?  I'm happy if we close this issue without taking action, but I would like to better understand your viewpoint.

**Comment by samreid** [comment]
> And the base class AccordionBox has no default value for tandem option.

Please see 
https://github.com/phetsims/sun/blob/11e15ecb24967fd010b93c3ffacef01eb989d629/js/AccordionBox.js#L45-L46

```js
  function AccordionBox( contentNode, options ) {

    var self = this;

    options = _.extend( {

      // {Tandem}
      tandem: Tandem.required,
```

> tandem: Tandem.required is required in both superclass (GQEquationAccordionBox) and subclass (ExploreEquationAccordionBox ) because options.tandem.createTandem is called in both the superclass and subclass.

I see, that makes sense.

> Reasons why a subclass may redundantly specify an option value:

These sound reasonable, should we add them to the phet-info/doc/phet-software-design-patterns.md or some other document?  I'm not sure everyone on the team is aware of those points.

**Comment by pixelzoom** [comment]
Mea culpa - I looked for `tandem` where it's supposed to be.  AccordionBox violates the "group phet-io options at the end of defaults" convention. `tandem` and other phet-io options are separated by 50 lines.  Should it be fixed? (This btw is another good example of why it's expensive to comb through superclasses looking for default values.)

```js
  function AccordionBox( contentNode, options ) {

    var self = this;

    options = _.extend( {

      // {Tandem}
46      tandem: Tandem.required,

...

96      // phet-io support
97      phetioType: AccordionBoxIO,
98      phetioEventType: 'user',

      // a11y options
      tagName: 'div',

      // Options will be provided to both title bar nodes
      titleBarOptions: null
    }, options );
```

> These sound reasonable, should we add them to the phet-info/doc/phet-software-design-patterns.md or some other document? I'm not sure everyone on the team is aware of those points.

These seem like common sense to me.  But if you think they would be useful in a document, feel free to add them.
