### ISSUE TITLE
undefined values cannot be saved by phet-io, sims should be written to use null instead.

### ISSUE THREAD

**Issue by samreid** [phetsims/graphing-quadratics#95]
From #14 
The PhET-iO instrumentation checklist indicates:

> undefined values cannot be saved by phet-io, sims should be written to use null instead.

However, I saw code like this:
```js
    /**
     * Encodes a Quadratic instance as a PhET-iO state object
     * @returns {*}
     * @public
     */
    toStateObject() {
      return {

        // These properties are sufficient to restore a Quadratic, see fromStateObject.
        a: this.a,
        b: this.b,
        c: this.c,
        color: Color.toColor( this.color ).toStateObject(),

        // These properties are desired in the data stream, but will be undefined for non-parabolas (a===0).
        // Because PhET-iO values are based on JSON.stringify, undefined properties will not be present in the
        // data stream.
        p: this.p,
        h: this.h,
        k: this.k,
        vertex: ( this.vertex ? this.vertex.toStateObject() : undefined ),
        focus: ( this.focus ? this.focus.toStateObject() : undefined ),
        directrix: this.directrix,
        axisOfSymmetry: this.axisOfSymmetry
      };
    }
```

Note in particular this documentation:

```js
        // These properties are desired in the data stream, but will be undefined for non-parabolas (a===0).
        // Because PhET-iO values are based on JSON.stringify, undefined properties will not be present in the
        // data stream.
```

Should we update the checklist to indicate that undefined values are ok where desired?

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/graphing-quadratics/issues/38#issuecomment-426329415, I was specifically instructed to use `undefined`:

@zepumph said:
> I think it would be preferable to have consistent values with undefined, for consistency. I also think that would be easier to document.

@samreid said:
> For simplicity on the implementation side, it seems best to include the values even when undefined, but be aware they will not show up on the client frame

Please clarify what is needed for PhET-iO.

**Comment by samreid** [comment]
Self-unassigning until hearing back from @zepumph.

**Comment by pixelzoom** [comment]
Removing block-sim-publication label, since brand=phet-io is no longer required for 1.0.  See https://github.com/phetsims/graphing-quadratics/issues/92#issuecomment-434083952.

**Comment by pixelzoom** [comment]
Semantically, the proper values for these fields (vertex, focus, directrix, h, k,...) is `undefined`, since they are undefined for non-parabolas.

**Comment by zepumph** [comment]
>In https://github.com/phetsims/graphing-quadratics/issues/38#issuecomment-426329415, I was specifically instructed to use `undefined`:

And the next comment was @samreid pointing out concerns with the idea, https://github.com/phetsims/graphing-quadratics/issues/38#issuecomment-426407177.

For this case, it makes sense to me that they would be `undefined`, therefore stripped out on the way to the client side frame. That said it may be more confusing for the Type to sometimes have these properties, and sometimes omit them. I could see it both ways.

**Comment by pixelzoom** [comment]
@zepumph said:
> And the next comment was @samreid pointing out concerns with the idea, https://github.com/phetsims/graphing-quadratics/issues/38#issuecomment-426407177.

@samreid's comment concluded:
> For simplicity on the implementation side, it seems best to include the values even when undefined, but be aware they will not show up on the client frame. 

I may be misinterpreting, but "include the values even when undefined" sure sounds like it's recommending to set the values to undefined in `toStateObject`.  @zepumph How do you interpret it?  @samreid How did you intend it?

**Comment by zepumph** [comment]
That makes a lot of sense. I misunderstood.  @samreid I think it is alright to exclude some pieces when undefined if desired, but I think with a large note in the doc that normally it should be null.

**Comment by pixelzoom** [comment]
I'm torn about what to do here.  

The `documentation` for QuadraticIO includes:

`'Non-parabolas (a=0) will have a subset of the properties that parabolas have.' +`

so it seems like the absence of some fields is (adequately?) documented. 

On the other hand, if the convention is use `null`, then it would be straightforward to add an `else` clause to `Quadratic` constructor, i.e.:

```js
else {

  // For non-parabolas, these fields have no value and are therefore set to null for PhET-iO.
  this.p = null;
  this.h = null;
  this.k = null;
  this.vertex = null;
  this.focus = null;
  this.directrix = null;
  this.axisOfSymmetry = null;
}
```

...and modify the encoding of `vertex` and `focus` in `toStateObject`, and modify the QuadraticIO `documentation` to say something like "Fields that are applicable only to parabolas will be null when the quadratic does not describe a parabola."

That said... any strong opinions?

**Comment by pixelzoom** [comment]
Btw... I don't believe any other code will be affected by this decision, because client code does not test for `undefined` or `null` fields, it calls Quadratic `isaParabola`.

**Comment by samreid** [comment]
The original checklist item read:

- [ ] `undefined` values cannot be saved by phet-io, sims should be written to use `null` instead.

I will rewrite this as 

- [ ] Like JSON, keys for `undefined` values are omitted in the state--consider this when determining whether toStateObject should use null or undefined values.

I think this is the appropriate course of action and I'm ready to close this issue.  Sound OK @pixelzoom and @zepumph?

**Comment by pixelzoom** [comment]
Sounds good.  So stick with undefined in QuadraticIO, no code changes required.  Closing.
