### ISSUE TITLE
Incorrect tandems for coefficients?

### ISSUE THREAD

**Issue by samreid** [phetsims/graphing-quadratics#96]
During review #14 I noticed this code:

```js
      const hProperty = new NumberProperty( H_RANGE.defaultValue, {
        range: H_RANGE,
        numberType: COEFFICIENT_NUMBER_TYPE,
        tandem: tandem.createTandem( 'bProperty' ),
        phetioDocumentation: 'coefficient h for the interactive quadratic'
      } );
      phet.log && hProperty.link( h => { phet.log( 'h=' + h ); } );

      const kProperty = new NumberProperty( K_RANGE.defaultValue, {
        range: K_RANGE,
        numberType: COEFFICIENT_NUMBER_TYPE,
        tandem: tandem.createTandem( 'cProperty' ),
        phetioDocumentation: 'coefficient k for the interactive quadratic'
      } );
      phet.log && kProperty.link( k => { phet.log( 'k=' + k ); } );
```

Notice that the `hProperty` is called `bProperty` and the `kProperty` is called `cProperty`.  Is this intentional?  Does this pattern happen elsewhere?

**Comment by pixelzoom** [comment]
>  Is this intentional?
Nope. Good catch, thanks.  Fixed the cases that I could identify in *Model classes.

> Does this pattern happen elsewhere?

Probably.  Instrumentation (in my experience so far) is heavily based on copy-paste.  So I predict that copy-paste will be a common type of error.
