### ISSUE TITLE
grunt find-duplicates

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/graphing-quadratics#98]
Related to https://github.com/phetsims/graphing-quadratics/issues/43, this checklist item:

> - [ ] Are any significant chunks of code duplicated? This will be checked manually as well as with https://github.com/danielstjules/jsinspect or `grunt find-duplicates`.

I haven't done this yet, so self assigning.

**Comment by pixelzoom** [comment]
I took the verbose output from `grunt find-duplicates` and converted it to this checklist to investigate:

- [ ] ExploreInteractiveEquationNode.js: 105-131, FocusAndDirectrixInteractiveEquationNode.js: 109-135

- [ ] FocusManipulator.js: 5-21, PointOnParabolaManipulator.js: 4-20

- [ ] VertexManipulator.js: 89-104, VertexNode.js: 72-87

- [ ] StandardFormModel.js: 5-25, VertexFormModel.js: 5-25

- [ ] FocusAndDirectrixModel.js: 53-72, VertexFormModel.js: 51-70

- [ ] StandardFormGraphControlPanel.js: 4-21, VertexFormGraphControlPanel.js: 4-21

- [ ] StandardFormInteractiveEquationNode.js: 4-24, VertexFormInteractiveEquationNode.js: 4-24

- [ ] StandardFormInteractiveEquationNode.js: 60-72, VertexFormInteractiveEquationNode.js: 60-72

**Comment by pixelzoom** [comment]
The first one in the list was legitimate duplication oversight, and I addressed it as described above. 
The majority were false positives, as described above. 

Assigning to @chrisklus in case he wants to review.  Feel free to close if everything looks OK.

**Comment by chrisklus** [comment]
I reran `grunt find-duplicates` and confirmed that everything it printed was part of the no-op list in https://github.com/phetsims/graphing-quadratics/issues/98#issuecomment-435225405. Closing.
